/* Author: ramanpal singh | URL: https://kwebby.com */
import {notFound,permanentRedirect} from 'next/navigation';
import {headers} from 'next/headers';
import {getSite,getPublicPage,pageMetadata,schemaScript,publicAddress,locationPage,reviewDate} from '@/lib/public';
import {telHref} from '@/lib/website-display';
import {SiteFrame,ServiceList,DoctorList} from '@/components/public-site';
import {LocationDetails} from '@/components/website-sections';
import {Blocks} from '@/components/blocks';
export const dynamic='force-dynamic';
// Only a real 404 becomes notFound(); an API outage reaches the error boundary (5xx) so crawlers keep the page.
const load=getPublicPage;
const builtinPages:Record<string,{title:string;kind:string}>={services:{title:'Care at our clinic',kind:'directory'},doctors:{title:'Meet your care team',kind:'directory'},contact:{title:'Plan your visit',kind:'contact'}};
const builtins=(slug:string)=>Object.hasOwn(builtinPages,slug)?builtinPages[slug]:undefined;
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const{slug:parts}=await params;const slug=parts.join('/');const[site,page]=await Promise.all([getSite(),load(slug)]);const location=site.locations?.find(l=>l.slug===slug);return pageMetadata(page||(location?locationPage(location):undefined)||{id:slug,version:1,slug,...(builtins(slug)||{title:'Page not found',kind:'page'}),seo:{indexable:Boolean(builtins(slug))}},site)}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const{slug:parts}=await params;const slug=parts.join('/');const[site,page,h]=await Promise.all([getSite(),load(slug),headers()]);if(page?.redirect&&/^[a-zA-Z0-9/_-]+$/.test(String(page.redirect))&&!String(page.redirect).startsWith('/'))permanentRedirect('/'+String(page.redirect));const location=site.locations?.find(l=>l.slug===slug);const builtin=builtins(slug);if(!page&&!location&&!builtin)notFound();const data=page||(location?locationPage(location):undefined)||{id:slug,version:1,slug,...builtin};const reviewed=page?.reviewedBy?reviewDate(page.reviewedAt,site):undefined;return <SiteFrame site={site}><script nonce={h.get('x-nonce')||undefined} type="application/ld+json" dangerouslySetInnerHTML={{__html:schemaScript(data,site)}}/><article className="public-content"><h1>{String(data.title)}</h1>{location?<LocationDetails location={location} heading={false}/>:page?<><Blocks value={page.content}/>{page.reviewedBy?<p className="reviewed-note">Clinically reviewed{reviewed?<> · <time dateTime={String(page.reviewedAt)}>{reviewed}</time></>:null}</p>:null}{Array.isArray(page.citations)&&page.citations.length>0&&<aside className="source-list"><h2>Sources</h2><ul>{page.citations.map((c,i)=>{const x=c as Record<string,string>;return <li key={i}><a href={/^https:\/\//.test(x.url)?x.url:undefined} rel="noopener noreferrer">{x.title}</a></li>})}</ul></aside>}</>:slug==='services'?<ServiceList site={site}/>:slug==='doctors'?<DoctorList site={site}/>:site.locations?.length?<div className="website-locations">{site.locations.map(location=><LocationDetails key={location.id} location={location}/>)}</div>:<><p>{publicAddress(site)||'Contact our team for clinic details and opening hours.'}</p>{site.phone&&<p><a href={telHref(site.phone)}>{site.phone}</a></p>}{site.email&&<p><a href={`mailto:${site.email}`}>{site.email}</a></p>}<a href="/booking" className="button primary">Request an appointment</a></>}</article></SiteFrame>}
