/* Author: ramanpal singh | URL: https://kwebby.com */
import {notFound,permanentRedirect} from 'next/navigation';
import {headers} from 'next/headers';
import {getSite,publicApi,pageMetadata,schemaScript,publicAddress,locationPage} from '@/lib/public';
import {SiteFrame,ServiceList,DoctorList} from '@/components/public-site';
import {LocationDetails} from '@/components/website-sections';
import {Blocks} from '@/components/blocks';
import type {RecordData} from '@/lib/types';
export const dynamic='force-dynamic';
async function load(slug:string){try{return await publicApi<RecordData>(`/pages/${encodeURIComponent(slug)}`)}catch{return undefined}}
const builtins:Record<string,{title:string;kind:string}>={services:{title:'Care at our clinic',kind:'directory'},doctors:{title:'Meet your care team',kind:'directory'},contact:{title:'Plan your visit',kind:'contact'}};
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const{slug:parts}=await params;const slug=parts.join('/');const[site,page]=await Promise.all([getSite(),load(slug)]);const location=site.locations?.find(l=>l.slug===slug);return pageMetadata(page||(location?locationPage(location):undefined)||{id:slug,version:1,slug,...(builtins[slug]||{title:'Page not found',kind:'page'}),seo:{indexable:Boolean(builtins[slug])}},site)}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const{slug:parts}=await params;const slug=parts.join('/');const[site,page,h]=await Promise.all([getSite(),load(slug),headers()]);if(page?.redirect&&/^[a-zA-Z0-9/_-]+$/.test(String(page.redirect))&&!String(page.redirect).startsWith('/'))permanentRedirect('/'+String(page.redirect));const location=site.locations?.find(l=>l.slug===slug);if(!page&&!location&&!builtins[slug])notFound();const data=page||(location?locationPage(location):undefined)||{id:slug,version:1,slug,...builtins[slug]};return <SiteFrame site={site}><script nonce={h.get('x-nonce')||undefined} type="application/ld+json" dangerouslySetInnerHTML={{__html:schemaScript(data,site)}}/><article className="public-content"><h1>{String(data.title)}</h1>{location?<LocationDetails location={location} heading={false}/>:page?<><Blocks value={page.content}/>{page.reviewedBy&&<p className="reviewed-note">Clinically reviewed · {new Date(String(page.updatedAt)).toLocaleDateString()}</p>}{Array.isArray(page.citations)&&page.citations.length>0&&<aside className="source-list"><h2>Sources</h2><ul>{page.citations.map((c,i)=>{const x=c as Record<string,string>;return <li key={i}><a href={/^https:\/\//.test(x.url)?x.url:undefined} rel="noopener noreferrer">{x.title}</a></li>})}</ul></aside>}</>:slug==='services'?<ServiceList site={site}/>:slug==='doctors'?<DoctorList site={site}/>:site.locations?.length?<div className="website-locations">{site.locations.map(location=><LocationDetails key={location.id} location={location}/>)}</div>:<><p>{publicAddress(site)||'Contact our team for clinic details and opening hours.'}</p>{site.phone&&<p><a href={`tel:${site.phone.replace(/[^+\d]/g,'')}`}>{site.phone}</a></p>}{site.email&&<p><a href={`mailto:${site.email}`}>{site.email}</a></p>}<a href="/booking" className="button primary">Request an appointment</a></>}</article></SiteFrame>}
