/* Author: ramanpal singh | URL: https://kwebby.com */
import { describe,it,expect,beforeAll,afterAll } from 'vitest';
import { randomBytes,randomUUID } from 'node:crypto';
import { createApp } from '../../apps/api/src/main.js';
import { Runtime } from '../../apps/api/src/runtime.js';
import type { INestApplication } from '@nestjs/common';
import * as OTPAuth from 'otpauth';
const enabled=!!process.env.REDIS_TEST_URL;
describe.skipIf(!enabled)('HTTP security with isolated test sessions',()=>{
 let app:INestApplication,url:string,cookie:string,csrf:string,ownerId:string;
 const origin='http://localhost:3000',password='Unique test password 456!';
 const request=async(path:string,body?:unknown,options:{cookie?:string;csrf?:string;origin?:string}={})=>{const response=await fetch(url+'/api/v1'+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',origin:options.origin??origin,...((options.cookie??cookie)?{cookie:options.cookie??cookie}:{}),...((options.csrf??csrf)?{'x-csrf-token':options.csrf??csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {response,result:await response.json() as any};};
 beforeAll(async()=>{process.env.DATABASE_DRIVER='memory';process.env.NODE_ENV='test';process.env.REDIS_URL=process.env.REDIS_TEST_URL;process.env.INSTALLATION_ID='test-'+randomUUID();process.env.APP_ENCRYPTION_KEY=randomBytes(32).toString('base64');process.env.BOOTSTRAP_TOKEN=randomBytes(32).toString('hex');process.env.REQUIRE_STAFF_MFA='false';process.env.PUBLIC_URL=origin;process.env.ALLOWED_ORIGINS=origin;app=await createApp();await app.listen(0,'127.0.0.1');url=await app.getUrl();},20000);
 afterAll(async()=>{await app?.close();});
 it('bootstraps once and never exposes password material',async()=>{const r=await request('/auth/bootstrap',{token:process.env.BOOTSTRAP_TOKEN,name:'Test owner',email:'owner@example.test',password,clinicName:'Test clinic',timezone:'UTC',currency:'USD'});expect(r.response.status).toBe(201);cookie=r.response.headers.get('set-cookie')!.split(';')[0];csrf=r.result.data.csrfToken;ownerId=r.result.data.user.id;expect(r.result.data.user.passwordHash).toBeUndefined();const again=await request('/auth/bootstrap',{token:process.env.BOOTSTRAP_TOKEN,name:'Other owner',email:'second@example.test',password,clinicName:'Test clinic',timezone:'UTC',currency:'USD'});expect(again.response.status).toBe(409);});
 it('requires both CSRF and trusted origins for mutations',async()=>{expect((await request('/records/patients',{branchId:'main',name:'Test person'},{csrf:'wrong'})).response.status).toBe(403);expect((await request('/records/patients',{branchId:'main',name:'Test person'},{origin:'https://evil.example'})).response.status).toBe(403);});
 it('prevents privileged public registration and avoids identity auto-linking',async()=>{const escalation=await request('/auth/register',{name:'Patient',email:'p@example.test',password,roles:['owner']});expect(escalation.response.status).toBe(400);const r=await request('/auth/register',{name:'Patient',email:'p@example.test',password});expect(r.response.status).toBe(201);expect(r.result.data.user.roles).toEqual(['patient']);expect(r.result.data.user.patientIds).toEqual([]);const patientCookie=r.response.headers.get('set-cookie')!.split(';')[0];const denied=await request('/records/patients',{branchId:'main',name:'Someone else'},{cookie:patientCookie,csrf:r.result.data.csrfToken});expect(denied.response.status).toBe(403);const settings=await request('/integrations',undefined,{cookie:patientCookie});expect(settings.response.status).toBe(403);});
 it('publishes no draft content or configuration secrets',async()=>{const r=await request('/public/site');expect(r.response.status).toBe(200);expect(JSON.stringify(r.result)).not.toContain('password');expect(r.result.data.pages).toEqual([]);expect(r.response.headers.get('cache-control')).toContain('no-store');});
 it('enforces staff MFA gating when enabled',async()=>{process.env.REQUIRE_STAFF_MFA='true';expect((await request('/dashboard')).response.status).toBe(403);expect((await request('/auth/session')).result.data.mfaRequired).toBe(true);process.env.REQUIRE_STAFF_MFA='false';});
 it('enrolls MFA, rejects OTP replay, and consumes recovery codes once',async()=>{process.env.REQUIRE_STAFF_MFA='true';const setup=await request('/auth/mfa/begin',{});expect(setup.response.status).toBe(201);const otp=new OTPAuth.TOTP({secret:OTPAuth.Secret.fromBase32(setup.result.data.secret)});const confirmed=await request('/auth/mfa/confirm',{code:otp.generate()});expect(confirmed.response.status).toBe(201);expect(confirmed.result.data.recoveryCodes).toHaveLength(8);expect((await request('/dashboard')).response.status).toBe(200);expect((await request('/auth/login',{email:'owner@example.test',password})).response.status).toBe(401);const recovery=confirmed.result.data.recoveryCodes[0];expect((await request('/auth/login',{email:'owner@example.test',password,totp:recovery})).response.status).toBe(201);expect((await request('/auth/login',{email:'owner@example.test',password,totp:recovery})).response.status).toBe(401);const fresh=otp.generate();expect((await request('/auth/login',{email:'owner@example.test',password,totp:fresh})).response.status).toBe(201);expect((await request('/auth/login',{email:'owner@example.test',password,totp:fresh})).response.status).toBe(401);});
 it('revokes sessions server-side',async()=>{expect((await request('/auth/revoke-sessions',{})).response.status).toBe(201);expect((await request('/dashboard')).response.status).toBe(401);});
});
