/* Author: ramanpal singh | URL: https://kwebby.com */
import type { Field, ModuleDefinition } from './types';
const field=(key:string,label:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label,type,...extra});
const branch=field('branchId','Branch','text',{required:true});
const patient=field('patientId','Patient','select',{reference:'patients',required:true});
const doctor=field('doctorId','Doctor','select',{required:true,reference:'@doctors'});
const content=field('content','Document','blocks',{full:true,default:[]});
const notes=field('notes','Notes','blocks',{full:true,default:[]});
const staff=['owner','admin','manager'];
const clinical=['doctor','nurse'];
const operations=[...staff,...clinical,'receptionist'];
const finance=[...staff,'accountant'];
const editors=[...staff,'editor'];
const column=(key:string,label:string)=>({key,label});
export const modules:Record<string,ModuleDefinition>={
 patients:{title:'Patients',singular:'Patient',description:'A clear record for every person in your care.',icon:'patients',group:'Care',roles:operations,fields:[branch,field('name','Full name','text',{required:true}),field('dateOfBirth','Date of birth','date'),field('email','Email','email'),field('phone','Phone','tel'),field('address','Address','textarea'),field('allergies','Allergies','json',{default:[],hint:'List of recorded allergies.'}),field('medicines','Current medicines','json',{default:[]}),field('emergencyContact','Emergency contact','json',{hint:'Name, phone, relationship.'})],columns:[column('name','Patient'),column('phone','Phone'),column('email','Email'),column('dateOfBirth','Date of birth')]},
 appointments:{title:'Appointments',singular:'Appointment',description:'Plan the day and keep the queue moving.',icon:'calendar',group:'Care',roles:operations,fields:[branch,patient,doctor,field('startsAt','Starts','datetime-local',{required:true}),field('endsAt','Ends','datetime-local',{required:true}),field('kind','Visit type','select',{options:['consultation','follow-up','walk-in'],default:'consultation'}),field('reason','Reason for visit','textarea')],columns:[column('startsAt','Time'),column('patientId','Patient'),column('doctorId','Doctor'),column('kind','Visit'),column('status','Status')],actions:[{action:'appointments.status',label:'Update arrival / status',fields:[field('status','Status','select',{required:true,options:['arrived','in-progress','completed','cancelled','no-show']})]},{action:'appointments.reschedule',label:'Reschedule',fields:[field('startsAt','New start','datetime-local',{required:true}),field('endsAt','New end','datetime-local',{required:true})]}]},
 encounters:{title:'Consultations',singular:'Consultation',description:'Review the history, write your notes, and sign with confidence.',icon:'notes',group:'Care',roles:clinical,fields:[branch,patient,doctor,field('appointmentId','Appointment','select',{reference:'appointments'}),content,field('observations','Observations','json',{default:{},hint:'bloodPressure, pulse, temperature, weight, height'}),field('diagnosis','Recorded diagnoses','json',{default:[]}),field('followUpAt','Follow-up date','datetime-local')],columns:[column('patientId','Patient'),column('doctorId','Doctor'),column('status','Status'),column('updatedAt','Last updated')],actions:[{action:'encounters.sign',label:'Sign consultation',roles:['doctor'],match:{status:['draft']},hint:'Signing freezes this version. Corrections will be recorded as amendments.'},{action:'encounters.amend',label:'Add amendment',roles:['doctor'],match:{status:['signed']},fields:[field('reason','Reason for amendment','textarea',{required:true}),content]}]},
 prescriptions:{title:'Prescriptions',singular:'Prescription',description:'Draft and sign treatment instructions from the consultation.',icon:'prescription',group:'Care',roles:clinical,fields:[branch,patient,field('encounterId','Consultation','select',{reference:'encounters',required:true}),field('medications','Medicines','json',{full:true,required:true,default:[{name:'',dose:'',route:'oral',frequency:'',duration:'',instructions:''}],hint:'The prescribing doctor must check every medicine and instruction.'}),field('instructions','Additional instructions','textarea')],columns:[column('patientId','Patient'),column('encounterId','Consultation'),column('status','Status'),column('createdAt','Created')],actions:[{action:'prescriptions.sign',label:'Sign prescription',roles:['doctor'],match:{status:['draft']}}]},
 results:{title:'Results & follow-up',singular:'Result',description:'Every result has an owner, review, and communication record.',icon:'results',group:'Care',roles:clinical,fields:[branch,patient,field('title','Report title','text',{required:true}),field('reviewerId','Reviewing doctor','select',{required:true,reference:'@doctors'}),field('coveringReviewerId','Covering doctor','select',{reference:'@doctors'}),field('fileId','Secure report file ID'),field('critical','Critical result','boolean'),field('dueAt','Review due','datetime-local')],columns:[column('title','Report'),column('patientId','Patient'),column('reviewState','Review'),column('contactState','Communication'),column('actionState','Action')],actions:[{action:'results.review',label:'Record clinical review',roles:['doctor'],fields:[field('summary','Review summary','textarea',{required:true}),field('actionRequired','Further action required','boolean')]},{action:'results.contact',label:'Record patient contact',fields:[field('outcome','Outcome','select',{options:['attempted','communicated'],required:true}),field('note','Contact note','textarea',{required:true})]},{action:'results.action',label:'Complete follow-up action',roles:['doctor','nurse'],fields:[field('note','Action taken','textarea',{required:true})]},{action:'results.reassign',label:'Assign review cover',fields:[field('reviewerId','Reviewer','select',{required:true,reference:'@doctors'}),field('coveringReviewerId','Covering reviewer','select',{reference:'@doctors'})]},{action:'results.release',label:'Release to patient',roles:['doctor']}]},
 tasks:{title:'Care tasks',singular:'Task',description:'Keep important work visible until it is finished.',icon:'tasks',group:'Care',roles:operations,fields:[branch,field('title','Task','text',{required:true}),field('assignedTo','Assigned to','select',{required:true,reference:'@staff'}),field('patientId','Patient','select',{reference:'patients'}),field('dueAt','Due','datetime-local'),field('priority','Priority','select',{options:['normal','high','urgent'],default:'normal'}),field('category','Category','select',{options:['administrative','clinical','finance'],default:'administrative'}),field('description','Description','textarea')],columns:[column('title','Task'),column('assignedTo','Owner'),column('dueAt','Due'),column('priority','Priority'),column('status','Status')],actions:[{action:'tasks.complete',label:'Complete task',roles:['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee'],fields:[field('note','Completion note','textarea')]}]},
 referrals:{title:'Referrals',singular:'Referral',description:'Coordinate the next step in a patient’s care.',icon:'results',group:'Care',roles:clinical,fields:[branch,patient,field('encounterId','Consultation','select',{reference:'encounters'}),field('destination','Referral destination','text',{required:true}),field('reason','Reason','textarea',{required:true}),field('assignedTo','Assigned to','select',{reference:'@staff'})],columns:[column('patientId','Patient'),column('destination','Destination'),column('reason','Reason'),column('status','Status')],actions:[{action:'referrals.complete',label:'Complete referral',fields:[field('note','Completion note','textarea')]},{action:'referrals.release',label:'Release referral to patient',roles:['doctor'],fields:[field('note','Release note','textarea')]}]},
 leads:{title:'Patient inquiries',singular:'Inquiry',description:'Give every inquiry a clear next step.',icon:'leads',group:'Relationships',roles:[...staff,'receptionist'],fields:[branch,field('name','Name','text',{required:true}),field('email','Email','email'),field('phone','Phone','tel'),field('source','Source','text',{required:true,default:'phone'}),field('interest','Interested in'),field('assignedTo','Assigned to','select',{reference:'@staff'}),field('callbackAt','Callback due','datetime-local'),field('marketingConsent','Marketing consent recorded','boolean'),notes],columns:[column('name','Name'),column('source','Source'),column('interest','Interest'),column('callbackAt','Callback'),column('stage','Stage')],actions:[{action:'leads.transition',label:'Move inquiry',fields:[field('stage','Stage','select',{options:['new','contacted','qualified','booked','closed'],required:true}),field('closureReason','Closure reason'),field('appointmentId','Booked appointment','select',{reference:'appointments'})]},{action:'leads.contact',label:'Log contact',fields:[field('note','Contact note','textarea',{required:true}),field('outcome','Outcome','text',{required:true}),field('callbackAt','Next callback','datetime-local')]}]},
 conversations:{title:'Messages',singular:'Conversation',description:'A shared inbox for your team and patients.',icon:'chat',group:'Relationships',fields:[branch,field('title','Subject','text',{required:true}),field('kind','Conversation type','select',{options:['staff','patient-service','clinical'],default:'staff'}),field('participantIds','Participant account IDs','json',{required:true,default:[]}),field('patientId','Patient','select',{reference:'patients'}),field('assignedTo','Assigned to','select',{reference:'@staff'})],columns:[column('title','Conversation'),column('kind','Type'),column('updatedAt','Last activity')]},
 invoices:{title:'Invoices',singular:'Invoice',description:'Accurate charges and a clear balance for every visit.',icon:'invoices',group:'Business',roles:finance.concat('receptionist'),fields:[branch,patient,field('currency','Currency','text',{required:true,default:'INR'}),field('lines','Invoice items','lines',{full:true,required:true}),notes,field('dueAt','Due date','datetime-local'),field('templateId','Document template','select',{reference:'templates'})],columns:[column('number','Invoice'),column('patientId','Patient'),column('total','Total'),column('paidAmount','Paid'),column('status','Status')],actions:[{action:'invoices.issue',label:'Issue invoice',match:{status:['draft']},hint:'This freezes the invoice details and allocates its invoice number.'},{action:'payments.record',label:'Record payment',roles:['owner','admin','accountant'],idKey:'invoiceId',fields:[field('amount','Amount','text',{required:true}),field('method','Payment method','select',{options:['cash','bank'],required:true}),field('reference','Payment reference')]},{action:'invoices.credit',label:'Issue credit note',roles:['owner','admin','accountant'],idKey:'invoiceId',match:{status:['issued','partially-paid']},fields:[field('amount','Credit amount','text',{required:true}),field('reason','Credit reason','textarea',{required:true})],hint:'Credits reduce the unpaid balance and preserve the issued invoice. Refund paid funds before applying a credit.'}]},
 payments:{title:'Payments',singular:'Payment',description:'Reconcile receipts and record approved refunds.',icon:'invoices',group:'Business',roles:finance,readonly:true,fields:[],columns:[column('invoiceId','Invoice'),column('amount','Amount'),column('method','Method'),column('status','Status'),column('createdAt','Date')],actions:[{action:'refunds.record',label:'Record manual refund',match:{method:['cash','bank']},idKey:'paymentId',fields:[field('amount','Refund amount','text',{required:true}),field('reason','Reason','textarea',{required:true})]}]},
 services:{title:'Services & fees',singular:'Service',description:'Maintain booking durations and published clinic fees.',icon:'services',group:'Business',roles:staff,fields:[branch,field('name','Service name','text',{required:true}),field('description','Description','textarea'),field('price','Price','text',{required:true}),field('currency','Currency','text',{required:true,default:'INR'}),field('durationMinutes','Duration (minutes)','number',{required:true,default:30,min:5}),field('taxRate','Tax rate (%)','text',{default:'0'}),field('public','Publish on website','boolean',{default:false})],columns:[column('name','Service'),column('price','Fee'),column('currency','Currency'),column('durationMinutes','Minutes'),column('public','Published')]},
 employees:{title:'Team',singular:'Employee',description:'People, responsibilities, and salary agreements.',icon:'team',group:'Team',roles:[...staff,'hr'],fields:[branch,field('userId','Login account','select',{reference:'@staff'}),field('name','Full name','text',{required:true}),field('email','Email','email',{required:true}),field('jobTitle','Job title','text',{required:true}),field('role','Staff role','select',{options:['doctor','nurse','receptionist','manager','accountant','hr','editor','employee'],default:'employee'}),field('registrationNumber','Professional registration'),field('specialty','Specialty'),field('publicProfile','Publish professional profile','boolean'),field('joinedOn','Join date','date'),field('salary','Salary structure','json',{full:true,required:true,default:{currency:'INR',base:'0',earnings:[],deductions:[]}})],columns:[column('name','Employee'),column('jobTitle','Role'),column('email','Email'),column('joinedOn','Joined')]},
 payroll:{title:'Payroll',singular:'Pay run',description:'Prepare, approve, and record employee salary payments.',icon:'payroll',group:'Team',roles:[...staff,'hr','accountant'],fields:[branch,field('period','Pay month','text',{required:true,hint:'YYYY-MM'}),field('employeeIds','Employees','json',{required:true,default:[],hint:'Employee record IDs included in this pay run.'}),field('adjustments','Earnings and deductions','json',{default:[],hint:'employeeId, label, amount, kind (earning or deduction).'}),field('templateId','Payslip template','select',{reference:'templates'})],columns:[column('period','Period'),column('status','Status'),column('total','Total'),column('createdAt','Created')],actions:[{action:'payroll.approve',label:'Approve pay run',match:{status:['draft']},hint:'Approving freezes the salary calculations and produces individual payslips.'},{action:'payroll.pay',label:'Record salary payment',roles:['owner','admin','hr','accountant'],match:{status:['approved']},fields:[field('reference','Bank / payment reference','text',{required:true})]}]},
 availability:{title:'Working hours',singular:'Availability',description:'Set local clinic hours for each doctor.',icon:'calendar',group:'Team',roles:staff,fields:[branch,doctor,field('weekday','Day of week','select',{required:true,options:['0','1','2','3','4','5','6'],hint:'0 Sunday, 1 Monday, through 6 Saturday.'}),field('startTime','Start time','text',{required:true,default:'09:00'}),field('endTime','End time','text',{required:true,default:'17:00'}),field('timezone','Timezone','text',{required:true,default:'Asia/Kolkata'}),field('slotMinutes','Slot duration','number',{required:true,default:30,min:5})],columns:[column('doctorId','Doctor'),column('weekday','Day'),column('startTime','Start'),column('endTime','End'),column('timezone','Timezone')]},
 leave:{title:'Time off',singular:'Leave request',description:'Plan cover before a member of the team is away.',icon:'calendar',group:'Team',roles:[...staff,'hr','employee','doctor','nurse'],fields:[branch,field('employeeId','Employee','select',{reference:'employees',required:true}),field('startsAt','Starts','datetime-local',{required:true}),field('endsAt','Ends','datetime-local',{required:true}),field('reason','Reason','textarea')],columns:[column('employeeId','Employee'),column('startsAt','From'),column('endsAt','To'),column('status','Status')],actions:[{action:'leave.approve',label:'Review leave request',roles:[...staff,'hr'],fields:[field('approved','Approve leave','boolean')]}]},
 pages:{title:'Website pages',singular:'Page',description:'Useful, reviewed content with search and social controls built in.',icon:'website',group:'Website',roles:[...editors,'doctor'],fields:[field('title','Page title','text',{required:true}),field('slug','URL slug','text',{required:true,hint:'Use home for the homepage.'}),field('kind','Page type','select',{required:true,default:'article',options:['home','location','doctor','service','medical','article','faq','about','contact','directory','tool','vendor']}),field('locale','Language','text',{required:true,default:'en-IN'}),content,field('reviewedBy','Clinical reviewer','select',{reference:'@doctors'}),field('citations','Sources','json',{default:[],hint:'Each source has a title and an https URL.'}),field('seo','Search and social settings','json',{full:true,default:{indexable:true},hint:'Use the guided Search & social editor below.'})],columns:[column('title','Page'),column('slug','URL'),column('kind','Type'),column('locale','Language'),column('status','Status')],actions:[{action:'pages.review',label:'Record clinical review',roles:['doctor'],fields:[field('note','Review note','textarea')]},{action:'pages.publish',label:'Publish page',hint:'Publishes this page revision. If a theme is active, use Website themes → Publish website to include it in the current website.'},{action:'pages.restore',label:'Restore revision',fields:[field('revisionId','Revision ID','text',{required:true})]}]},
 templates:{title:'Document designer',singular:'Template',description:'Design invoices and payslips around your clinic’s identity.',icon:'design',group:'Business',roles:[...staff,'accountant','hr'],fields:[field('name','Template name','text',{required:true}),field('kind','Document type','select',{required:true,options:['invoice','payslip'],default:'invoice'}),content,field('design','Design settings','json',{full:true,required:true,default:{accent:'#25645d',font:'system',showLogo:true,columns:['description','quantity','unitPrice','total'],footer:'Thank you for choosing our clinic.',terms:''}})],columns:[column('name','Template'),column('kind','Type'),column('status','Status'),column('updatedAt','Updated')],actions:[{action:'templates.publish',label:'Publish template'}]},
 documents:{title:'Documents',singular:'Document',description:'Approved patient documents and private employee payslips.',icon:'notes',group:'Business',readonly:true,fields:[],columns:[column('title','Document'),column('kind','Type'),column('patientId','Patient'),column('status','Status'),column('createdAt','Created')],actions:[{action:'documents.release',label:'Release to patient',roles:['doctor','owner','admin']}]},
 consents:{title:'Consent records',singular:'Consent',description:'Record each purpose and keep consent history clear.',icon:'security',group:'Care',roles:operations,fields:[branch,patient,field('purpose','Purpose','select',{required:true,options:['care','marketing','reminders','ai','caregiver']}),field('granted','Consent granted','boolean'),field('versionLabel','Consent text version','text',{required:true}),field('source','Recorded source','text',{required:true})],columns:[column('patientId','Patient'),column('purpose','Purpose'),column('granted','Granted'),column('createdAt','Recorded')]},
 notifications:{title:'Notifications',singular:'Notification',description:'Your updates, grouped by what needs your attention.',icon:'bell',group:'Workspace',readonly:true,fields:[],columns:[column('title','Notification'),column('category','Category'),column('status','Status'),column('createdAt','Received')],actions:[{action:'notifications.read',label:'Mark as read'}]}
};
/** Own-property check: route segments such as `toString` must not resolve to Object.prototype members. */
export const isModule=(name:string)=>Object.hasOwn(modules,name);
export function canAccess(roles:string[], allowed?:string[]) { return !allowed||roles.some(x=>allowed.includes(x)); }

export const writeRoles:Record<string,string[]>={patients:['owner','admin','manager','doctor','nurse','receptionist'],appointments:['owner','admin','manager','doctor','nurse','receptionist','patient'],encounters:['doctor','nurse'],prescriptions:['doctor'],results:['doctor','nurse'],referrals:['doctor','nurse'],tasks:['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor'],leads:['owner','admin','manager','receptionist'],employees:['owner','admin','hr'],invoices:['owner','admin','accountant','receptionist'],payroll:['owner','admin','hr'],pages:['owner','admin','editor'],templates:['owner','admin','accountant','hr','editor'],conversations:['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee','patient'],consents:['owner','admin','manager','doctor','nurse','receptionist','patient'],settings:['owner','admin'],availability:['owner','admin','manager','doctor'],leave:['owner','admin','manager','hr','doctor','nurse','receptionist','employee'],services:['owner','admin','manager','accountant']};
// Match server read permissions for navigation; these are presentation hints, never authority.
modules.patients.roles=[...operations,'accountant'];
modules.tasks.roles=['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee'];
modules.employees.roles=['owner','admin','manager','hr','employee','doctor','nurse','receptionist','accountant','editor'];
modules.payroll.roles=['owner','admin','hr','accountant'];
modules.templates.roles=['owner','admin','manager','accountant','hr','editor'];
modules.availability.roles=operations;
modules.leave.roles=['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee'];
modules.services.roles=['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee'];
modules.notifications.actions![0].roles=['owner','admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee','patient'];
modules.documents.actions![0].roles=['doctor','accountant','hr','owner','admin'];
