/* Author: ramanpal singh | URL: https://kwebby.com */
import 'server-only';
import {cache} from 'react';
import {headers} from 'next/headers';
import {unstable_rethrow} from 'next/navigation';
import type {Metadata} from 'next';
import type {WebsiteSettings,WebsiteLocation,WebsiteBranding} from '../../../packages/contracts/src/website';
import {addressText} from './website-display';
export {publicAddress} from './website-display';
import {buildSeo,jsonLdScript,type SeoPage,type SiteIdentity} from '../../../packages/platform/src/seo';
import type {RecordData} from './types';
import type {Theme} from '@/components/themes';
export interface PublicSite {website?:WebsiteSettings;locations?:WebsiteLocation[];branding?:WebsiteBranding;homepage?:WebsiteSettings['homepage'];header?:WebsiteSettings['header'];footer?:WebsiteSettings['footer'];navigation?:WebsiteSettings['navigation'];displayPhone?:string;socialProfiles?:string[];socialImageAlt?:string;name:string;description:string;url:string;locale:string;currency:string;timezone:string;address?:string|Record<string,string>;email?:string;phone?:string;logo?:string;doctors:RecordData[];services:RecordData[];pages:RecordData[];theme?:{manifest:Theme;publicationId?:string;themeId?:string};audience?:'patient'|'business';mode?:string;socialImage?:string;socialHandle?:string;searchConsoleVerification?:string;unavailable?:boolean}
/** The visitor's address chain, so the API rate-limits each visitor rather than one shared server bucket. */
async function forwardedFor():Promise<string|undefined>{try{return (await headers()).get('x-forwarded-for')?.slice(0,512)||undefined}catch(error){unstable_rethrow(error);return undefined}}
export async function publicApi<T>(path:string):Promise<T>{const forwarded=await forwardedFor();const response=await fetch(`${process.env.API_INTERNAL_URL||'http://127.0.0.1:4000'}/api/v1/public${path}`,{cache:'no-store',signal:AbortSignal.timeout(6000),headers:forwarded?{'x-forwarded-for':forwarded}:undefined});if(!response.ok)throw Object.assign(new Error(response.status===404?'Page not found':'Clinic website is temporarily unavailable'),{status:response.status});const result=await response.json();return result.data as T}
export const isNotFound=(error:unknown)=>(error as {status?:unknown}|null)?.status===404;
// One /public/site request per render; AbortSignal opts fetch out of Next's own memoization.
const loadSite=cache(()=>publicApi<PublicSite>('/site'));
/** Throws while the API is unavailable so public pages answer 5xx through the error boundary and crawlers retry, rather than indexing a placeholder. */
export function getSite():Promise<PublicSite>{return loadSite()}
/** For the shell, robots and sitemaps, which handle an unavailable site themselves. */
export async function getSiteOrFallback():Promise<PublicSite>{try{return await loadSite()}catch(error){unstable_rethrow(error);return{name:'Clinic',description:'Contact your clinic to arrange your next visit.',url:process.env.PUBLIC_APP_URL||'http://localhost:3000',locale:'en',currency:'USD',timezone:'UTC',doctors:[],services:[],pages:[],unavailable:true}}}
/** A published page, or undefined only when the API answers 404. Other failures propagate. */
export const getPublicPage=cache(async(slug:string):Promise<RecordData|undefined>=>{try{return await publicApi<RecordData>(`/pages/${encodeURIComponent(slug)}`)}catch(error){if(isNotFound(error))return undefined;throw error}});
export interface ClinicLocalization {timezone:string;locale:string;currency:string;branchTimezones:Record<string,string>}
export function siteLocalization(site:PublicSite):ClinicLocalization|undefined{if(site.unavailable)return;try{new Intl.DateTimeFormat(site.locale,{timeZone:site.timezone});return{timezone:site.timezone,locale:site.locale,currency:site.currency,branchTimezones:Object.fromEntries((site.locations??[]).filter(l=>l.branchId&&l.timezone).map(l=>[l.branchId,l.timezone]))}}catch{return}}
export function htmlLang(site:PublicSite):string{try{return Intl.getCanonicalLocales(site.locale)[0]||'en'}catch{return 'en'}}
/** Review date in the clinic's own locale and timezone. */
export function reviewDate(value:unknown,site:PublicSite):string|undefined{const date=new Date(String(value??''));if(!value||Number.isNaN(date.getTime()))return;try{return new Intl.DateTimeFormat(site.locale,{timeZone:site.timezone,dateStyle:'long'}).format(date)}catch{return new Intl.DateTimeFormat('en',{timeZone:'UTC',dateStyle:'long'}).format(date)}}
export function seoPage(page:RecordData,site:PublicSite):SeoPage{const seo=(page.seo||{}) as Record<string,unknown>;const kind=String(page.kind||'page');const translations=Array.isArray(seo.translations)?(seo.translations as {locale:string;slug:string}[]).map(t=>{const target=site.pages.find(p=>p.slug===t.slug&&p.locale===t.locale&&p.status==='published');const targetSeo=target?.seo as {translations?:{locale:string;slug:string}[]}|undefined;return{...t,published:Boolean(target),reciprocal:Boolean(targetSeo?.translations?.some(x=>x.slug===page.slug&&x.locale===page.locale))}}):[];return {location:site.locations?.find(l=>l.slug===page.slug),id:page.id,slug:String(page.slug||'home'),title:String(page.title||site.name),type:(kind==='location'?'branch':kind==='vendor'?'software':kind) as SeoPage['type'],status:String(page.status||'published'),locale:String(page.locale||site.locale),seoTitle:seo.title as string|undefined,seoDescription:seo.description as string|undefined,canonical:seo.canonical as string|undefined,indexable:seo.indexable!==false,socialTitle:seo.socialTitle as string|undefined,socialDescription:seo.socialDescription as string|undefined,socialImage:seo.socialImage as string|undefined,socialImageAlt:(seo.socialImageAlt??site.socialImageAlt) as string|undefined,customSchema:seo.schema as Record<string,unknown>|undefined,schemaTypes:seo.schemaTypes as string[]|undefined,translations,updatedAt:page.updatedAt,publishedAt:page.publishedAt as string|undefined,reviewedAt:page.reviewedAt as string|undefined,reviewer:page.reviewer&&typeof page.reviewer==='object'&&typeof (page.reviewer as Record<string,unknown>).name==='string'?page.reviewer as {name:string;url?:string}:undefined,citations:Array.isArray(page.citations)?page.citations.map(x=>String((x as Record<string,unknown>).url)):undefined}}
export function identity(site:PublicSite):SiteIdentity{return{url:site.url,name:site.name,description:site.description,locale:site.locale,telephone:site.phone,logo:site.logo,address:typeof site.address==='string'?{streetAddress:site.address}:site.address,defaultSocialImage:site.socialImage,socialHandle:site.socialHandle,socialProfiles:site.socialProfiles,locations:site.locations}}
export function pageMetadata(page:RecordData,site:PublicSite):Metadata{const seo=buildSeo(seoPage(page,site),identity(site));return{title:{absolute:seo.title},description:seo.description,metadataBase:new URL(site.url),robots:site.unavailable?{index:false,follow:false}:seo.robots,alternates:seo.alternates,openGraph:seo.openGraph as Metadata['openGraph'],twitter:seo.twitter as Metadata['twitter'],verification:site.searchConsoleVerification?{google:site.searchConsoleVerification}:undefined}}
export function schemaScript(page:RecordData,site:PublicSite){return jsonLdScript(buildSeo(seoPage(page,site),identity(site)).jsonLd)}

export function locationPage(location:WebsiteLocation):RecordData{return {id:location.id,version:1,slug:location.slug,title:location.name,kind:'location',status:'published',seo:{description:`Visit ${location.name} at ${addressText(location.address)}. Contact details, opening hours, directions and appointment information.`}};}
