/* Author: ramanpal singh | URL: https://kwebby.com */
import 'server-only';
import type {Metadata} from 'next';
import type {WebsiteSettings,WebsiteLocation,WebsiteBranding} from '../../../packages/contracts/src/website';
import {addressText} from './website-display';
import {buildSeo,jsonLdScript,type SeoPage,type SiteIdentity} from '../../../packages/platform/src/seo';
import type {RecordData} from './types';
import type {Theme} from '@/components/themes';
export interface PublicSite {website?:WebsiteSettings;locations?:WebsiteLocation[];branding?:WebsiteBranding;homepage?:WebsiteSettings['homepage'];header?:WebsiteSettings['header'];footer?:WebsiteSettings['footer'];navigation?:WebsiteSettings['navigation'];displayPhone?:string;socialProfiles?:string[];socialImageAlt?:string;name:string;description:string;url:string;locale:string;currency:string;timezone:string;address?:string|Record<string,string>;email?:string;phone?:string;logo?:string;doctors:RecordData[];services:RecordData[];pages:RecordData[];theme?:{manifest:Theme;publicationId?:string;themeId?:string};audience?:'patient'|'business';mode?:string;socialImage?:string;socialHandle?:string;searchConsoleVerification?:string;unavailable?:boolean}
export async function publicApi<T>(path:string):Promise<T>{const response=await fetch(`${process.env.API_INTERNAL_URL||'http://127.0.0.1:4000'}/api/v1/public${path}`,{cache:'no-store',signal:AbortSignal.timeout(6000)});if(!response.ok)throw Object.assign(new Error(response.status===404?'Page not found':'Clinic website is temporarily unavailable'),{status:response.status});const result=await response.json();return result.data as T}
export async function getSite():Promise<PublicSite>{try{return await publicApi<PublicSite>('/site')}catch{return{name:'Clinic',description:'Contact your clinic to arrange your next visit.',url:process.env.PUBLIC_APP_URL||'http://localhost:3000',locale:'en-IN',currency:'INR',timezone:'Asia/Kolkata',doctors:[],services:[],pages:[],unavailable:true}}}
export function seoPage(page:RecordData,site:PublicSite):SeoPage{const seo=(page.seo||{}) as Record<string,unknown>;const kind=String(page.kind||'page');const translations=Array.isArray(seo.translations)?(seo.translations as {locale:string;slug:string}[]).map(t=>{const target=site.pages.find(p=>p.slug===t.slug&&p.locale===t.locale&&p.status==='published');const targetSeo=target?.seo as {translations?:{locale:string;slug:string}[]}|undefined;return{...t,published:Boolean(target),reciprocal:Boolean(targetSeo?.translations?.some(x=>x.slug===page.slug&&x.locale===page.locale))}}):[];return {location:site.locations?.find(l=>l.slug===page.slug),id:page.id,slug:String(page.slug||'home'),title:String(page.title||site.name),type:(kind==='location'?'branch':kind==='vendor'?'software':kind) as SeoPage['type'],status:String(page.status||'published'),locale:String(page.locale||site.locale),seoTitle:seo.title as string|undefined,seoDescription:seo.description as string|undefined,canonical:seo.canonical as string|undefined,indexable:seo.indexable!==false,socialTitle:seo.socialTitle as string|undefined,socialDescription:seo.socialDescription as string|undefined,socialImage:seo.socialImage as string|undefined,socialImageAlt:(seo.socialImageAlt??site.socialImageAlt) as string|undefined,customSchema:seo.schema as Record<string,unknown>|undefined,schemaTypes:seo.schemaTypes as string[]|undefined,translations,updatedAt:page.updatedAt,publishedAt:page.publishedAt as string|undefined,reviewer:page.reviewer&&typeof page.reviewer==='object'&&typeof (page.reviewer as Record<string,unknown>).name==='string'?page.reviewer as {name:string;url?:string}:undefined,citations:Array.isArray(page.citations)?page.citations.map(x=>String((x as Record<string,unknown>).url)):undefined}}
export function identity(site:PublicSite):SiteIdentity{return{url:site.url,name:site.name,description:site.description,locale:site.locale,telephone:site.phone,logo:site.logo,address:typeof site.address==='string'?{streetAddress:site.address}:site.address,defaultSocialImage:site.socialImage,socialHandle:site.socialHandle,socialProfiles:site.socialProfiles,locations:site.locations}}
export function pageMetadata(page:RecordData,site:PublicSite):Metadata{const seo=buildSeo(seoPage(page,site),identity(site));return{title:{absolute:seo.title},description:seo.description,metadataBase:new URL(site.url),robots:site.unavailable?{index:false,follow:false}:seo.robots,alternates:seo.alternates,openGraph:seo.openGraph as Metadata['openGraph'],twitter:seo.twitter as Metadata['twitter'],verification:site.searchConsoleVerification?{google:site.searchConsoleVerification}:undefined}}
export function schemaScript(page:RecordData,site:PublicSite){return jsonLdScript(buildSeo(seoPage(page,site),identity(site)).jsonLd)}
export function publicAddress(site:PublicSite){return addressText(site.address)}

export function locationPage(location:WebsiteLocation):RecordData{return {id:location.id,version:1,slug:location.slug,title:location.name,kind:'location',status:'published',seo:{description:`Visit ${location.name} at ${addressText(location.address)}. Contact details, opening hours, directions and appointment information.`}};}
