/* Author: ramanpal singh | URL: https://kwebby.com */
import type {Field} from './types';
export const toolDefinitions:Record<string,{title:string;description:string;audience:'patient'|'business';fields:Field[]}>= {
 'visit-preparation':{title:'Prepare for your visit',description:'A short checklist to help you arrive ready for your appointment.',audience:'patient',fields:[{key:'visitType',label:'Visit type',type:'select',options:['first','followup','routine'],default:'first'},{key:'needsInterpreter',label:'I need language assistance',type:'boolean'},{key:'bringingReports',label:'I am bringing previous reports',type:'boolean'}]},
 'questions-for-doctor':{title:'Questions for your doctor',description:'Build a useful list of questions to bring to your consultation.',audience:'patient',fields:[{key:'topic',label:'What would you like to discuss?',type:'select',options:['general','followup','medicine'],default:'general'}]},
 'caregiver-planner':{title:'Caregiver visit planner',description:'Plan the practical details when helping someone attend a clinic visit.',audience:'patient',fields:[{key:'mobilitySupport',label:'Mobility support is needed',type:'boolean'},{key:'interpreter',label:'Language assistance is needed',type:'boolean'},{key:'accompanyingAdult',label:'An adult will accompany the patient',type:'boolean',default:true}]},
 'record-checklist':{title:'Organize your health records',description:'Know which records to bring and how to keep them easy to find.',audience:'patient',fields:[]},
 'visit-budget':{title:'Plan your visit budget',description:'Estimate costs using the clinic’s published service fees.',audience:'patient',fields:[{key:'serviceIds',label:'Selected service IDs',type:'json',default:[],required:true},{key:'transportCost',label:'Travel cost',type:'number',default:0,min:0}]},
 'no-show-calculator':{title:'No-show cost calculator',description:'Estimate the booking value associated with missed appointments.',audience:'business',fields:[{key:'appointmentsPerMonth',label:'Appointments per month',type:'number',required:true,min:0},{key:'noShowPercent',label:'No-show percentage',type:'number',required:true,min:0,max:100},{key:'averageFee',label:'Average consultation fee',type:'number',required:true,min:0}]},
 'admin-workload':{title:'Administrative workload estimator',description:'Understand the time spent on repeat clinic administration.',audience:'business',fields:[{key:'visitsPerDay',label:'Visits per day',type:'number',required:true,min:0},{key:'minutesPerVisit',label:'Administrative minutes per visit',type:'number',required:true,min:0},{key:'workingDays',label:'Working days per month',type:'number',required:true,min:0},{key:'staffHourlyCost',label:'Staff cost per hour',type:'number',default:0,min:0}]},
 'operations-scorecard':{title:'Clinic operations scorecard',description:'Check the everyday processes that help a clinic run reliably.',audience:'business',fields:[{key:'reminders',label:'We send appointment reminders',type:'boolean'},{key:'resultsOwnership',label:'Every result has a reviewing clinician',type:'boolean'},{key:'paymentReconciliation',label:'We reconcile payments against invoices',type:'boolean'},{key:'rolePermissions',label:'Access is limited by staff role',type:'boolean'},{key:'testedBackups',label:'We have tested a full backup restore',type:'boolean'}]},
 'queue-planner':{title:'Queue and staffing planner',description:'Compare expected arrivals with consultation capacity.',audience:'business',fields:[{key:'arrivalsPerHour',label:'Arrivals per hour',type:'number',required:true,min:0},{key:'averageMinutes',label:'Average consultation minutes',type:'number',required:true,min:1},{key:'clinicians',label:'Available clinicians',type:'number',required:true,min:1},{key:'targetUtilization',label:'Target utilization',type:'number',default:0.8,min:0.5,max:0.95}]},
 'website-analyzer':{title:'Booking website analyzer',description:'Check whether one public website page makes it easy to find care and book.',audience:'business',fields:[{key:'url',label:'Public website URL',type:'text',required:true,hint:'Include https://'}]}
};
