/* Author: ramanpal singh | URL: https://kwebby.com */
import { expect,test } from 'vitest';
import { ClinicController,publicJob } from '../../apps/api/src/controllers.js';
import { AuthService } from '../../apps/api/src/auth.js';
import { MemoryDatabase } from './memory.js';
import type { Actor,Entity } from '../../packages/contracts/src/index.js';
const owner:Actor={id:'owner',organizationId:'clinic',roles:['owner'],branchIds:['main'],patientIds:[],name:'Owner',email:'owner@example.test'};
const row=(id:string,extra:Record<string,unknown>={}):Entity=>({id,organizationId:'clinic',version:1,createdAt:'2026-10-09T00:00:00Z',updatedAt:'2026-10-09T00:00:00Z',...extra});
test('failed job retries never reveal password-reset or invitation token payloads',async()=>{const db=new MemoryDatabase();await db.put('outbox',row('job',{status:'failed',type:'email.send',attempts:5,payload:{to:'owner@example.test',template:'reset-password',data:{url:'https://clinic.example/reset?token=SECRET'}}}));const controller=new ClinicController({db,auth:{require:async()=>owner}} as any);const response:any=await controller.retry('job',{} as any);expect(response.data.status).toBe('pending');expect(JSON.stringify(response)).not.toContain('SECRET');expect(response.data.payload).toBeUndefined();expect((await db.list('audit'))[0].action).toBe('outbox.retry');expect(publicJob(row('x',{providerSecret:'SECRET',status:'failed'}))).not.toHaveProperty('providerSecret');});
test('staff directory hides patient associations and unrelated branches from non-admins',async()=>{const db=new MemoryDatabase();await db.put('users',row('main-doctor',{name:'Doctor',email:'doctor@example.test',roles:['doctor'],branchIds:['main'],patientIds:['private-family-id'],mfaEnabled:true,status:'active'}));await db.put('users',row('other-doctor',{name:'Other Doctor',email:'other@example.test',roles:['doctor'],branchIds:['elsewhere'],patientIds:[],mfaEnabled:true,status:'active'}));const service=new AuthService(db,{} as any,{} as any);const team=await service.team({...owner,id:'staff',roles:['receptionist']});expect(team).toHaveLength(1);expect(team[0]).not.toHaveProperty('patientIds');expect(team[0]).not.toHaveProperty('mfaEnabled');expect(await service.team(owner)).toHaveLength(2);});
