/* Author: ramanpal singh | URL: https://kwebby.com */
import { beforeEach, describe, expect, test, vi } from 'vitest';
import { ClinicService } from '../../packages/core/src/index.js';
import type { Actor, Entity } from '../../packages/contracts/src/index.js';
import { MemoryDatabase } from './memory.js';

const makeActor=(id:string,roles:Actor['roles'],branchIds=['main'],patientIds:string[]=[]):Actor=>({id,organizationId:'clinic',name:id,email:`${id}@example.test`,roles,branchIds,patientIds});
const owner=makeActor('owner',['owner']);const doctor=makeActor('doctor',['doctor']);const nurse=makeActor('nurse',['nurse']);const reception=makeActor('reception',['receptionist']);const hr=makeActor('hr',['hr']);const accountant=makeActor('accountant',['accountant']);const editor=makeActor('editor',['editor']);let patient:Actor;
let db:MemoryDatabase;let core:ClinicService;let patientRow:Entity;
const content=[{id:'paragraph',type:'paragraph',props:{},content:[{type:'text',text:'Consultation note',styles:{}}],children:[]}];
async function raw(collection:string,id:string,data:Record<string,unknown>){const stamp=new Date().toISOString();return db.put(collection,{...data,id,organizationId:'clinic',version:1,createdAt:stamp,updatedAt:stamp});}
async function invoice(){return core.create('invoices',{branchId:'main',patientId:patientRow.id,currency:'USD',lines:[{description:'Consultation',quantity:'1',unitPrice:'100.00',taxRate:'10',discount:'10.00'}]},accountant);}
async function encounter(){return core.create('encounters',{branchId:'main',patientId:patientRow.id,doctorId:'doctor',content},doctor);}
async function book(startsAt='2026-10-12T10:00:00Z',endsAt='2026-10-12T10:30:00Z'){return core.create('appointments',{branchId:'main',patientId:patientRow.id,doctorId:'doctor',startsAt,endsAt},reception);}
beforeEach(async()=>{
 db=new MemoryDatabase();core=new ClinicService(db);
 for(const actor of [owner,doctor,nurse,reception,hr,accountant,editor])await raw('users',actor.id,{...actor,status:'active'});
 patientRow=await core.create('patients',{branchId:'main',name:'Alex Patient',phone:'123456789',email:'family@example.test'},reception);
 patient=makeActor('patient',['patient'],[],[patientRow.id]);await raw('users',patient.id,{...patient,status:'active'});
 await core.create('settings',{key:'business',value:{clinicName:'Example Clinic',country:'US',currency:'USD',timezone:'UTC',locale:'en-US',address:'1 Clinic Street',email:'clinic@example.test',phone:'12345'}},owner);
 await core.create('availability',{branchId:'main',doctorId:'doctor',weekday:1,startTime:'09:00',endTime:'17:00',timezone:'UTC',slotMinutes:30},owner);
});

describe('identity and authorization',()=>{
 test('shared contact details never link or merge patient records',async()=>{const other=await core.create('patients',{branchId:'main',name:'Family Member',email:'family@example.test',phone:'123456789'},reception);expect(other.id).not.toBe(patientRow.id);expect(await core.list('patients',patient)).toHaveLength(1);await expect(core.get('patients',other.id,patient)).rejects.toMatchObject({status:404});});
 test('rejects organization, branch and lifecycle field injection',async()=>{await expect(core.create('patients',{branchId:'main',name:'x',organizationId:'other'},reception)).rejects.toMatchObject({code:'VALIDATION'});await expect(core.create('patients',{branchId:'other',name:'x'},reception)).rejects.toMatchObject({status:403});await expect(core.create('payments',{status:'succeeded'},patient)).rejects.toMatchObject({status:403});});
 test('does not disclose disabled user identity through booking',async()=>{const user=await db.get('users','doctor');await db.put('users',{...user!,status:'disabled',version:2},1);await expect(book()).rejects.toMatchObject({code:'VALIDATION'});});
 test('stale generic edits conflict and arbitrary ownership updates are rejected',async()=>{const updated=await core.update('patients',patientRow.id,{expectedVersion:1,name:'Updated'},reception);expect(updated.version).toBe(2);await expect(core.update('patients',patientRow.id,{expectedVersion:1,name:'Stale'},reception)).rejects.toMatchObject({status:409});await expect(core.update('patients',patientRow.id,{expectedVersion:2,branchId:'other'},reception)).rejects.toMatchObject({code:'IMMUTABLE'});});
});

describe('appointments and clinical integrity',()=>{
 test('only one simultaneous overlapping booking succeeds',async()=>{const results=await Promise.allSettled([book(),book('2026-10-12T10:15:00Z','2026-10-12T10:45:00Z')]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await core.list('appointments',doctor)).length).toBe(1);});
 test('honors availability and approved leave',async()=>{await expect(book('2026-10-12T18:00:00Z','2026-10-12T18:30:00Z')).rejects.toMatchObject({code:'OUTSIDE_AVAILABILITY'});const employee=await core.create('employees',{branchId:'main',userId:'doctor',name:'Doctor',email:'doctor@example.test',jobTitle:'Doctor',role:'doctor',salary:{currency:'USD',base:'1000'}},hr);const leave=await core.create('leave',{branchId:'main',employeeId:employee.id,startsAt:'2026-10-12T09:00:00Z',endsAt:'2026-10-12T17:00:00Z'},doctor);await core.execute('leave.approve',{id:leave.id,expectedVersion:1,approved:true},hr);await expect(book()).rejects.toMatchObject({code:'DOCTOR_ABSENT'});});
 test('patients can book their linked patient and cannot appoint themselves doctor',async()=>{await expect(core.create('appointments',{branchId:'main',patientId:patientRow.id,doctorId:'patient',startsAt:'2026-10-12T09:00:00Z',endsAt:'2026-10-12T09:30:00Z'},patient)).rejects.toMatchObject({code:'VALIDATION'});expect((await core.create('appointments',{branchId:'main',patientId:patientRow.id,doctorId:'doctor',startsAt:'2026-10-12T09:00:00Z',endsAt:'2026-10-12T09:30:00Z'},patient)).status).toBe('booked');});
 test('only responsible doctor signs; amendments preserve signature and original JSON',async()=>{const e=await encounter();await expect(core.execute('encounters.sign',{id:e.id,expectedVersion:1},nurse)).rejects.toMatchObject({status:403});await expect(core.get('encounters',e.id,patient)).rejects.toMatchObject({status:404});const signed=await core.execute('encounters.sign',{id:e.id,expectedVersion:1},doctor);const amended=await core.execute('encounters.amend',{id:e.id,expectedVersion:2,reason:'Correction',content:[{type:'paragraph',content:[]}]},doctor);expect(amended.signedSnapshot).toEqual(signed.signedSnapshot);expect(amended.signatureHash).toEqual(signed.signatureHash);expect(amended.amendments).toHaveLength(1);expect((await core.get('encounters',e.id,patient)).status).toBe('signed');await expect(core.execute('encounters.save',{id:e.id,expectedVersion:3,content},doctor)).rejects.toMatchObject({code:'IMMUTABLE'});});
 test('results review, communication, required action and release are independent',async()=>{const result=await core.create('results',{branchId:'main',patientId:patientRow.id,title:'Lab result',reviewerId:'doctor'},nurse);await expect(core.execute('results.contact',{id:result.id,expectedVersion:1,outcome:'communicated',note:'Called'},nurse)).rejects.toMatchObject({code:'STATE'});await core.execute('results.review',{id:result.id,expectedVersion:1,summary:'Reviewed',actionRequired:true},doctor);const contacted=await core.execute('results.contact',{id:result.id,expectedVersion:2,outcome:'communicated',note:'Called'},nurse);expect(contacted.actionState).toBe('required');await expect(core.get('results',result.id,patient)).rejects.toMatchObject({status:404});const released=await core.execute('results.release',{id:result.id,expectedVersion:3},doctor);expect(released.actionState).toBe('required');expect((await core.execute('results.action',{id:result.id,expectedVersion:4,note:'Follow-up arranged'},doctor)).actionState).toBe('completed');});
 test('rejects unsafe BlockNote content',async()=>{await expect(core.create('encounters',{branchId:'main',patientId:patientRow.id,doctorId:'doctor',content:[{type:'paragraph',content:[{type:'link',href:'javascript:alert(1)'}]}]},doctor)).rejects.toMatchObject({code:'VALIDATION'});});
});

describe('money and payroll',()=>{
 test('exact decimal totals, immutable issue snapshots, atomic numbering and delivery',async()=>{const draft=await invoice();expect(draft.total).toBe('99.00');const issued=await core.execute('invoices.issue',{id:draft.id,expectedVersion:1},accountant);expect(issued.number).toContain('INV-main-');expect(issued.snapshot.total).toBe('99.00');expect((await db.list('outbox')).some(e=>e.type==='invoice.issued')).toBe(true);await core.update('settings','business',{expectedVersion:1,value:{clinicName:'New name',country:'US',currency:'USD',timezone:'UTC',locale:'en-US',address:'Changed',email:'x@example.test',phone:'123'}},owner);expect((await core.get('invoices',draft.id,accountant)).snapshot.business.clinicName).toBe('Example Clinic');await expect(core.update('invoices',draft.id,{expectedVersion:2,notes:[]},accountant)).rejects.toMatchObject({code:'IMMUTABLE'});});
 test('concurrent issuance produces unique sequential invoice numbers',async()=>{const one=await invoice(),two=await invoice();const issued=await Promise.all([one,two].map(v=>core.execute('invoices.issue',{id:v.id,expectedVersion:1},accountant)));expect(new Set(issued.map(v=>v.number)).size).toBe(2);});
 test('manual payment replay is idempotent and refunds update balances',async()=>{const draft=await invoice();await core.execute('invoices.issue',{id:draft.id,expectedVersion:1},accountant);const input={invoiceId:draft.id,amount:'40.00',method:'cash',idempotencyKey:'payment-key-0001'};const one=await core.execute('payments.record',input,accountant);const replay=await core.execute('payments.record',input,accountant);expect(replay.id).toBe(one.id);expect((await core.get('invoices',draft.id,accountant)).balance).toBe('59.00');await expect(core.execute('payments.record',{...input,amount:'20'},accountant)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});await core.execute('refunds.record',{paymentId:one.id,amount:'10.00',reason:'Adjustment',idempotencyKey:'refund-key-0001'},accountant);expect((await core.get('invoices',draft.id,accountant)).balance).toBe('69.00');await expect(core.execute('refunds.record',{paymentId:one.id,amount:'31.00',reason:'Too much',idempotencyKey:'refund-key-0002'},accountant)).rejects.toMatchObject({code:'OVER_REFUND'});});
 test('payslips are frozen and other employees cannot read them',async()=>{const employee=await core.create('employees',{branchId:'main',userId:'doctor',name:'Doctor',email:'doctor@example.test',jobTitle:'Doctor',salary:{currency:'USD',base:'1000',earnings:[{label:'Bonus',amount:'100'}],deductions:[{label:'Deduction',amount:'50'}]}},hr);const run=await core.create('payroll',{branchId:'main',period:'2026-10',employeeIds:[employee.id]},hr);expect(run.slips[0].net).toBe('1050.00');const approved=await core.execute('payroll.approve',{id:run.id,expectedVersion:1},hr);const doc=await core.get('documents',approved.documentIds[0],doctor);expect(doc.snapshot.net).toBe('1050.00');await expect(core.get('documents',doc.id,nurse)).rejects.toMatchObject({status:404});const duplicate=await core.create('payroll',{branchId:'main',period:'2026-10',employeeIds:[employee.id]},hr);await expect(core.execute('payroll.approve',{id:duplicate.id,expectedVersion:1},hr)).rejects.toMatchObject({code:'DUPLICATE_PAYROLL'});});
});

describe('content and conversations',()=>{
 test('draft edits preserve published snapshot and old slugs redirect directly',async()=>{const page=await core.create('pages',{title:'About',slug:'about',kind:'about',locale:'en-US',content},editor);const published=await core.execute('pages.publish',{id:page.id,expectedVersion:1},editor);expect(published.publishedSnapshot.slug).toBe('about');const draft=await core.update('pages',page.id,{expectedVersion:2,slug:'our-story',title:'Our story'},editor);expect(draft.publishedSnapshot.slug).toBe('about');await core.execute('pages.publish',{id:page.id,expectedVersion:3},editor);const routes=await db.list('pageRoutes');expect(routes.find(v=>v.slug==='about')).toMatchObject({status:'redirect',redirectSlug:'our-story'});await core.update('pages',page.id,{expectedVersion:4,slug:'about'},editor);await core.execute('pages.publish',{id:page.id,expectedVersion:5},editor);expect((await db.list('pageRoutes')).find(v=>v.slug==='about')).toMatchObject({status:'active'});});
 test('only participants see messages and duplicate sends are not duplicated',async()=>{const thread=await core.create('conversations',{branchId:'main',title:'Patient service',kind:'patient-service',patientId:patientRow.id,participantIds:['reception','patient']},reception);const data={conversationId:thread.id,body:'Appointment inquiry',idempotencyKey:'message-key-0001'};const message=await core.execute('conversations.send',data,patient);expect((await core.execute('conversations.send',data,patient)).id).toBe(message.id);expect(await core.list('messages',doctor)).toEqual([]);await expect(core.get('messages',message.id,doctor)).rejects.toMatchObject({status:404});expect((await core.get('messages',message.id,reception)).body).toBe('Appointment inquiry');expect((await db.list('outbox')).some(r=>r.type==='notification.requested'&&(r.payload as any).userId===reception.id&&(r.payload as any).category==='messages')).toBe(true);});
 test('rejects unaffiliated patient participants',async()=>{await raw('users','stranger',{...makeActor('stranger',['patient'],[],[]),status:'active'});await expect(core.create('conversations',{branchId:'main',title:'Care',kind:'patient-service',patientId:patientRow.id,participantIds:['patient','stranger']},reception)).rejects.toMatchObject({code:'VALIDATION'});});
});

describe('release and draft controls',()=>{
 test('medical publication requires actual review of exact content',async()=>{const page=await core.create('pages',{title:'Medical education',slug:'education',kind:'medical',locale:'en-US',content,reviewedBy:'doctor'},editor);await expect(core.execute('pages.publish',{id:page.id,expectedVersion:1},editor)).rejects.toMatchObject({code:'VALIDATION'});await core.execute('pages.review',{id:page.id,expectedVersion:1},doctor);const publication=await core.execute('pages.publish',{id:page.id,expectedVersion:2},editor);expect(publication.publishedSnapshot.reviewer).toEqual({name:'doctor'});expect(publication.publishedSnapshot.reviewedAt).toBeTruthy();await core.update('pages',page.id,{expectedVersion:3,title:'Changed medical content'},editor);await expect(core.execute('pages.publish',{id:page.id,expectedVersion:4},editor)).rejects.toMatchObject({code:'VALIDATION'});});
 test('patient intake remains scoped and does not overwrite signed clinical data',async()=>{const doc=await core.execute('patients.intake',{patientId:patientRow.id,content,allergies:['Self reported']},patient);expect(doc.kind).toBe('intake');expect((await core.get('patients',patientRow.id,reception)).allergies).toEqual([]);expect((await core.get('documents',doc.id,doctor)).snapshot.allergies).toEqual(['Self reported']);await expect(core.get('documents',doc.id,reception)).rejects.toMatchObject({status:404});});
 test('credit notes are capped at unpaid balance and replay safely',async()=>{const draft=await invoice();await core.execute('invoices.issue',{id:draft.id,expectedVersion:1},accountant);const input={invoiceId:draft.id,amount:'20.00',reason:'Courtesy adjustment',idempotencyKey:'credit-note-0001'};const credit=await core.execute('invoices.credit',input,accountant);expect((await core.execute('invoices.credit',input,accountant)).id).toBe(credit.id);expect((await core.get('invoices',draft.id,accountant)).balance).toBe('79.00');await expect(core.execute('invoices.credit',{...input,idempotencyKey:'credit-note-0002',amount:'80'},accountant)).rejects.toMatchObject({code:'CREDIT_EXCEEDS_BALANCE'});expect((await core.get('invoices',draft.id,accountant)).snapshot.total).toBe('99.00');});
 test('draft prescription edits require prescribing doctor, then signing freezes it',async()=>{const e=await encounter();const prescription=await core.create('prescriptions',{branchId:'main',patientId:patientRow.id,encounterId:e.id,medications:[{name:'Example medicine',dose:'1 tablet',route:'oral',frequency:'daily',duration:'3 days'}]},doctor);await expect(core.execute('prescriptions.sign',{id:prescription.id,expectedVersion:1},doctor)).rejects.toMatchObject({code:'STATE'});const edited=await core.execute('prescriptions.save',{id:prescription.id,expectedVersion:1,medications:prescription.medications,instructions:'With food'},doctor);await core.execute('encounters.sign',{id:e.id,expectedVersion:1},doctor);const signed=await core.execute('prescriptions.sign',{id:prescription.id,expectedVersion:edited.version},doctor);expect(signed.signedSnapshot.instructions).toBe('With food');await expect(core.execute('prescriptions.save',{id:prescription.id,expectedVersion:signed.version,medications:prescription.medications},doctor)).rejects.toMatchObject({code:'IMMUTABLE'});});
});


describe('pagination and final publication invariants',()=>{
 test('queries beyond 10,000 records forward the cursor and filter branch scope in bounded batches',async()=>{
  const stamp=new Date().toISOString();for(let index=0;index<10600;index++){const id=`record-${String(index).padStart(5,'0')}`;db.data.set(`patients/${id}`,{id,organizationId:'clinic',version:1,createdAt:stamp,updatedAt:stamp,branchId:index<10500?'other':'main',name:id});}
  const list=vi.spyOn(db,'list');const page=await core.list('patients',reception,{after:'record-09999',limit:25});expect(page).toHaveLength(25);expect(page[0].id).toBe('record-10500');expect(page[24].id).toBe('record-10524');expect(list.mock.calls[0][1]).toMatchObject({after:'record-09999',limit:500});expect(list.mock.calls.every(([,query])=>(query?.limit??0)<=500)).toBe(true);expect(await core.list('patients',reception,{after:'record-10599',limit:Number.NaN})).toEqual([]);
 });
 test('nonmedical publications omit stale reviewer attribution after content edits',async()=>{const page=await core.create('pages',{title:'Visit preparation',slug:'prepare',kind:'article',locale:'en-US',content},editor);await core.execute('pages.review',{id:page.id,expectedVersion:1},doctor);await core.update('pages',page.id,{expectedVersion:2,title:'New preparation guidance'},editor);const publication=await core.execute('pages.publish',{id:page.id,expectedVersion:3},editor);expect(publication.publishedSnapshot.reviewer).toBeUndefined();expect(publication.publishedSnapshot.reviewedAt).toBeUndefined();expect(publication.publishedSnapshot.reviewedBy).toBeUndefined();});
 test('signed clinical files release only with signature and remain tied to their patient',async()=>{await raw('files','scan-one',{scope:'clinical',scanStatus:'clean',patientId:patientRow.id,ownerId:doctor.id});const fileContent=[{type:'file',props:{url:'/api/v1/files/scan-one',name:'Report'},children:[]}];const draft=await core.create('encounters',{branchId:'main',patientId:patientRow.id,doctorId:doctor.id,content:fileContent},doctor);expect((await db.get('files','scan-one'))?.released).toBeUndefined();await core.execute('encounters.sign',{id:draft.id,expectedVersion:1},doctor);expect(await db.get('files','scan-one')).toMatchObject({released:true,patientId:patientRow.id,releasedBy:doctor.id});});
 test('prices obey currency precision and fully discounted invoices settle at zero',async()=>{await expect(core.create('invoices',{branchId:'main',patientId:patientRow.id,currency:'USD',lines:[{description:'Invalid fractional cent',quantity:'1',unitPrice:'1.001'}]},accountant)).rejects.toMatchObject({code:'MONEY'});const zero=await core.create('invoices',{branchId:'main',patientId:patientRow.id,currency:'USD',lines:[{description:'Complimentary visit',quantity:'1',unitPrice:'20',discount:'20'}]},accountant);expect(await core.execute('invoices.issue',{id:zero.id,expectedVersion:1},accountant)).toMatchObject({status:'paid',balance:'0.00'});await expect(core.create('employees',{branchId:'main',name:'Invalid salary',email:'salary@example.test',jobTitle:'Employee',salary:{currency:'JPY',base:'1.5'}},hr)).rejects.toMatchObject({code:'MONEY'});});
});
