/* Author: ramanpal singh | URL: https://kwebby.com */
import { beforeEach, describe, expect, test, vi } from 'vitest';
import { createHmac } from 'node:crypto';
import Stripe from 'stripe';
import { ClinicService } from '../../packages/core/src/index.js';
import { PaymentService, providerMinor, type IntegrationService } from '../../apps/api/src/integrations.js';
import type { Actor, Entity } from '../../packages/contracts/src/index.js';
import { MemoryDatabase } from '../../packages/persistence/src/memory.js';
const actor:Actor={id:'owner',organizationId:'clinic',roles:['owner'],branchIds:['main'],patientIds:[],name:'Owner',email:'owner@example.test'};
const otherBranch:Actor={...actor,id:'accountant',roles:['accountant'],branchIds:['another']};
let db:MemoryDatabase;let core:ClinicService;let payment:PaymentService;let invoice:Record<string,any>;let stripeMock:any;let network:ReturnType<typeof vi.fn>;const stripe=new Stripe('sk_test_fake_key_only');
const config={stripe:{secretKey:'sk_test_fake_key_only',webhookSecret:'whsec_fixture_only'},razorpay:{keyId:'rzp_test_fixture',keySecret:'fixture-secret',webhookSecret:'fixture-webhook'}};
async function stripeEvent(type:string,object:Record<string,any>,id='evt_test_1'){const raw=Buffer.from(JSON.stringify({id,type,data:{object}}));const signature=stripe.webhooks.generateTestHeaderString({payload:raw.toString(),secret:config.stripe.webhookSecret});return payment.webhook('stripe',raw,signature);}
async function razorEvent(type:string,object:Record<string,any>,id='evt_razor_1'){const raw=Buffer.from(JSON.stringify({event:type,payload:{payment:{entity:object}}}));return payment.webhook('razorpay',raw,createHmac('sha256',config.razorpay.webhookSecret).update(raw).digest('hex'),id);}
beforeEach(async()=>{
 process.env.ORGANIZATION_ID='clinic';process.env.PUBLIC_ORIGIN='https://clinic.example';db=new MemoryDatabase();core=new ClinicService(db);
 const patient=await core.create('patients',{branchId:'main',name:'Patient'},actor);
 await core.create('settings',{key:'business',value:{clinicName:'Test clinic',country:'US',currency:'USD',timezone:'UTC',locale:'en-US',address:'Street',email:'clinic@example.test',phone:'123'}},actor);
 const draft=await core.create('invoices',{branchId:'main',patientId:patient.id,currency:'USD',lines:[{description:'Visit',quantity:'1',unitPrice:'100'}]},actor);invoice=await core.execute('invoices.issue',{id:draft.id,expectedVersion:1},actor);
 stripeMock={checkout:{sessions:{create:vi.fn(async(params:any)=>({id:'cs_fixture',url:'https://checkout.stripe.com/fixture',metadata:params.metadata})),retrieve:vi.fn()}},refunds:{create:vi.fn(async(params:any)=>({id:'re_fixture',amount:params.amount,currency:'usd',payment_intent:params.payment_intent,status:'succeeded',metadata:params.metadata})),retrieve:vi.fn()}};
 network=vi.fn(async(_url:string,options:any)=>{const body=JSON.parse(options.body);return new Response(JSON.stringify({id:'order_fixture',amount:body.amount,currency:body.currency,receipt:body.receipt,notes:body.notes}),{status:200});});
 const integrations={config:async(provider:keyof typeof config)=>config[provider]} as unknown as IntegrationService;
 payment=new PaymentService(db,integrations,{stripeFactory:()=>stripeMock,fetch:network as unknown as typeof fetch});
});

describe('gateway integrity',()=>{
 test('checkout uses current balance after manual payments and rejects branch access',async()=>{await core.execute('payments.record',{invoiceId:invoice.id,amount:'30',method:'cash',idempotencyKey:'manual-fixture-key'},actor);await expect(payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},otherBranch)).rejects.toMatchObject({status:403});const result=await payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor);expect(result.url).toContain('stripe.com');expect(stripeMock.checkout.sessions.create.mock.calls[0][0].line_items[0].price_data.unit_amount).toBe(7000);const repeated=await payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor);expect(repeated).toEqual(result);expect(stripeMock.checkout.sessions.create).toHaveBeenCalledTimes(1);});
 test('forged signature changes no financial records',async()=>{await expect(payment.webhook('stripe',Buffer.from('{}'),'forged')).rejects.toMatchObject({code:'SIGNATURE'});expect(await db.list('payments')).toHaveLength(0);});
 test('delayed, duplicate and reordered Stripe events settle exactly once',async()=>{const checkout=await payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor);const object={id:'cs_fixture',metadata:{attemptId:checkout.attemptId},currency:'usd',amount_total:10000,payment_intent:'pi_fixture',payment_status:'unpaid'};await stripeEvent('checkout.session.completed',object,'evt_pending');expect(await db.list('payments')).toHaveLength(0);await stripeEvent('checkout.session.async_payment_succeeded',{...object,payment_status:'paid'},'evt_paid');await stripeEvent('checkout.session.async_payment_succeeded',{...object,payment_status:'paid'},'evt_paid');await stripeEvent('checkout.session.completed',{...object,payment_status:'paid'},'evt_paid_again');await stripeEvent('checkout.session.async_payment_failed',object,'evt_late_failure');expect(await db.list('payments')).toHaveLength(1);expect(await db.get('invoices',invoice.id)).toMatchObject({status:'paid',balance:'0.00',paidAmount:'100.00'});expect(await db.get('paymentAttempts',checkout.attemptId)).toMatchObject({status:'settled'});});
 test('valid signatures with mismatched amount do not settle',async()=>{const checkout=await payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor);await expect(stripeEvent('checkout.session.completed',{id:'cs_fixture',metadata:{attemptId:checkout.attemptId},currency:'usd',amount_total:1,payment_intent:'pi_fixture',payment_status:'paid'})).rejects.toMatchObject({code:'AMOUNT_MISMATCH'});expect(await db.list('payments')).toHaveLength(0);});
 test('captured overpayment is recorded and flagged without a negative invoice balance',async()=>{const checkout=await payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor);await core.execute('payments.record',{invoiceId:invoice.id,amount:'20',method:'cash',idempotencyKey:'manual-fixture-key'},actor);await expect(payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor)).rejects.toMatchObject({code:'BALANCE_CHANGED'});await stripeEvent('checkout.session.completed',{id:'cs_fixture',metadata:{attemptId:checkout.attemptId},currency:'usd',amount_total:10000,payment_intent:'pi_fixture',payment_status:'paid'});const gateway=(await db.list('payments')).find(p=>p.method==='stripe')!;expect(gateway).toMatchObject({allocatedAmount:'80.00',unallocatedAmount:'20.00',reconciliationState:'overpayment'});expect(await db.get('invoices',invoice.id)).toMatchObject({balance:'0.00',paidAmount:'100.00'});expect((await db.list('outbox')).some(v=>v.type==='payment.reconciliation-required')).toBe(true);});
 test('Razorpay unknown outcome is never automatically retried',async()=>{network.mockRejectedValue(new Error('Connection closed after request'));await expect(payment.checkout('razorpay',{invoiceId:invoice.id,idempotencyKey:'razor-unknown'},actor)).rejects.toThrow('Connection closed');await expect(payment.checkout('razorpay',{invoiceId:invoice.id,idempotencyKey:'razor-unknown'},actor)).rejects.toMatchObject({code:'CHECKOUT_PENDING'});expect(network).toHaveBeenCalledTimes(1);const attempt=(await db.list('paymentAttempts'))[0];expect(attempt.status).toBe('needs-reconciliation');});
 test('Razorpay capture maps order ID when payment notes are absent',async()=>{await payment.checkout('razorpay',{invoiceId:invoice.id,idempotencyKey:'razor-checkout'},actor);await razorEvent('payment.captured',{id:'pay_fixture',order_id:'order_fixture',amount:10000,currency:'USD',status:'captured'});expect(await db.get('invoices',invoice.id)).toMatchObject({status:'paid',balance:'0.00'});expect((await db.list('payments'))[0]).toMatchObject({providerReference:'pay_fixture',method:'razorpay'});});
 test('provider currency rules preserve exact amounts',()=>{expect(providerMinor('1.23','USD','stripe')).toBe(123);expect(providerMinor('100','JPY','stripe')).toBe(100);expect(providerMinor('5','ISK','stripe')).toBe(500);expect(providerMinor('5','UGX','stripe')).toBe(500);expect(providerMinor('1.230','KWD','razorpay')).toBe(1230);expect(()=>providerMinor('1.231','KWD','razorpay')).toThrow();expect(()=>providerMinor('1.001','USD','stripe')).toThrow();});
});

describe('provider refunds',()=>{
 async function pay(){const checkout=await payment.checkout('stripe',{invoiceId:invoice.id,idempotencyKey:'checkout-fixture'},actor);await stripeEvent('checkout.session.completed',{id:'cs_fixture',metadata:{attemptId:checkout.attemptId},currency:'usd',amount_total:10000,payment_intent:'pi_fixture',payment_status:'paid'});return (await db.list('payments'))[0];}
 test('refund is idempotent and updates paid/balance only after provider success',async()=>{const p=await pay();const input={paymentId:p.id,amount:'20',reason:'Adjustment',idempotencyKey:'refund-fixture-key'};const r=await payment.refund('stripe',input,actor);expect(r.status).toBe('succeeded');expect(await db.get('invoices',invoice.id)).toMatchObject({status:'partially-paid',paidAmount:'80.00',balance:'20.00'});expect(await payment.refund('stripe',input,actor)).toMatchObject({status:'succeeded'});expect(stripeMock.refunds.create).toHaveBeenCalledTimes(1);await expect(payment.refund('stripe',{...input,idempotencyKey:'refund-too-big',amount:'81'},actor)).rejects.toMatchObject({code:'OVER_REFUND'});});
 test('pending refund reserves funds without marking them refunded',async()=>{const p=await pay();stripeMock.refunds.create.mockImplementation(async(params:any)=>({id:'re_pending',amount:params.amount,currency:'usd',payment_intent:params.payment_intent,status:'pending',metadata:params.metadata}));const input={paymentId:p.id,amount:'80',reason:'Refund',idempotencyKey:'refund-pending-key'};expect(await payment.refund('stripe',input,actor)).toMatchObject({status:'pending'});expect(await db.get('invoices',invoice.id)).toMatchObject({balance:'0.00'});await expect(payment.refund('stripe',{...input,idempotencyKey:'another-refund-key',amount:'30'},actor)).rejects.toMatchObject({code:'OVER_REFUND'});});
 test('dashboard refund event applies once and late pending events cannot revert success',async()=>{const p=await pay();const refund={id:'re_dashboard',amount:1250,currency:'usd',payment_intent:'pi_fixture',status:'succeeded',metadata:{}};await stripeEvent('refund.created',refund,'evt_refund');await stripeEvent('refund.updated',refund,'evt_refund_update');await stripeEvent('refund.updated',{...refund,status:'pending'},'evt_late_pending');expect(await db.list('refunds')).toHaveLength(1);expect(await db.get('payments',p.id)).toMatchObject({refundedAmount:'12.50'});expect(await db.get('invoices',invoice.id)).toMatchObject({balance:'12.50'});});
});
