/* Author: ramanpal singh | URL: https://kwebby.com */
import { afterAll, beforeAll, describe, expect, test } from 'vitest';
import { randomUUID,randomBytes } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { exportInstallation,importInstallation } from '../../packages/persistence/src/transfer.js';
import { ClinicService } from '../../packages/core/src/index.js';
import type { Actor, Database, Entity } from '../../packages/contracts/src/index.js';
import { certificationProfiles,parityCollections,serverVersion } from './profiles.js';

for(const profile of certificationProfiles())describe(`adapter certification: ${profile.name}`,()=>{
 let db:Database,core:ClinicService;const org=`cert-${randomUUID()}`;const prefix=randomUUID().slice(0,8);const branch=`branch-${prefix}`;let patientId:string;let initialized=false;
 const owner:Actor={id:`owner-${prefix}`,organizationId:org,roles:['owner'],branchIds:[branch],patientIds:[],name:'Certification owner',email:`owner-${prefix}@example.test`};
 const doctor:Actor={...owner,id:`doctor-${prefix}`,roles:['doctor'],name:'Certification doctor'};
 const receptionist:Actor={...owner,id:`receptionist-${prefix}`,roles:['receptionist']};
 const row=(id:string,data:Record<string,unknown>={}):Entity=>({id,organizationId:org,version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...data});
 const content=[{id:'p1',type:'paragraph',props:{},content:[{type:'text',text:'Certification sample, synthetic data only.',styles:{}}],children:[]}];
 async function draftInvoice(){return core.create('invoices',{branchId:branch,patientId,currency:'USD',lines:[{description:'Synthetic visit',quantity:'1',unitPrice:'10.25',taxRate:'10'}]},owner);}
 beforeAll(async()=>{
  db=profile.create();await db.initialize();initialized=true;
  const existing=await db.get('settings','business');if(existing)throw new Error('Target already contains business settings. Refusing to overwrite an existing installation; use an empty disposable database.');
  const version=await serverVersion(db);if(profile.expectedMajor)expect(version).toMatch(new RegExp(`(?:PostgreSQL )?${profile.expectedMajor.replace('.','\\.')}[.\\s-]`));
  if(profile.driver==='mysql')expect(version).toMatch(/^8\.4\./);
  core=new ClinicService(db);
  for(const user of [owner,doctor,receptionist])await db.put('users',row(user.id,{...user,status:'active'}));
  await core.create('settings',{key:'business',value:{clinicName:'Synthetic certification clinic',country:'US',currency:'USD',timezone:'UTC',locale:'en-US',address:'Synthetic address',email:'certification@example.test',phone:'000000'}},owner);
  const patient=await core.create('patients',{branchId:branch,name:'Synthetic test patient'},receptionist);patientId=patient.id;
  await core.create('availability',{branchId:branch,doctorId:doctor.id,weekday:1,startTime:'09:00',endTime:'17:00',timezone:'UTC',slotMinutes:30},owner);
 },60000);
 afterAll(async()=>{
  if(!db)return;
  try{if(initialized)for(const collection of parityCollections){const records=await db.list(collection,{eq:{organizationId:org},limit:10000});for(const record of records)await db.remove(collection,record.id,record.version);}}finally{await db.close();}
 },60000);
 test('all module collections preserve JSON, decimal strings, revisions and boolean/null filters',async()=>{
  for(const collection of parityCollections){
   const id=`parity-${prefix}-${collection}`;const value=row(id,{label:'Synthetic parity probe',amount:'12345.678',active:true,empty:null,nested:{text:'Résumé 🩺',blocks:content,list:[1,'2',false,null],matrix:[[1,2],[3,4]]}});
   await db.put(collection,value);expect(await db.get(collection,id)).toEqual(value);
   expect((await db.list(collection,{eq:{organizationId:org,id,active:true},limit:5})).map(r=>r.id)).toEqual([id]);
   expect((await db.list(collection,{eq:{organizationId:org,id,empty:null},limit:5})).map(r=>r.id)).toEqual([id]);
   const updated={...value,version:2,label:'Updated'};await db.put(collection,updated,1);expect(await db.get(collection,id)).toEqual(updated);await db.remove(collection,id,2);expect(await db.get(collection,id)).toBeNull();
  }
 },120000);
 test('compare-and-swap rejects stale and duplicate writes',async()=>{const id=`cas-${prefix}`;const first=row(id,{value:1});await db.put('certificationProbe',first);await expect(db.put('certificationProbe',first)).rejects.toMatchObject({code:'CONFLICT'});await db.put('certificationProbe',{...first,value:2,version:2},1);await expect(db.put('certificationProbe',{...first,value:3,version:2},1)).rejects.toMatchObject({code:'CONFLICT'});expect((await db.get('certificationProbe',id))?.value).toBe(2);});
 test('transaction rollback leaves no business write or outbox event',async()=>{const id=`rollback-${prefix}`;await expect(db.transaction([id],async tx=>{await tx.put('certificationProbe',row(id));await tx.put('outbox',row(`event-${id}`,{type:'probe',status:'pending'}));throw new Error('Rollback probe');})).rejects.toThrow('Rollback probe');expect(await db.get('certificationProbe',id)).toBeNull();expect(await db.get('outbox',`event-${id}`)).toBeNull();});
 test('transaction reads observe staged writes and can read after writing',async()=>{const id=`staged-${prefix}`;await db.transaction([id],async tx=>{await tx.put('certificationProbe',row(id,{value:1}));const afterWrite=await tx.get('settings','business');expect(afterWrite?.organizationId).toBe(org);const own=await tx.get('certificationProbe',id);expect(own?.value).toBe(1);await tx.put('certificationProbe',{...own!,version:2,value:2},1);expect((await tx.list('certificationProbe',{eq:{organizationId:org,id}}))[0].value).toBe(2);});expect((await db.get('certificationProbe',id))?.version).toBe(2);});
 test('parallel overlapping bookings admit exactly one; adjacent slot succeeds',async()=>{const input={branchId:branch,patientId,doctorId:doctor.id,startsAt:'2026-10-12T10:00:00Z',endsAt:'2026-10-12T10:30:00Z'};const results=await Promise.allSettled([core.create('appointments',input,receptionist),core.create('appointments',{...input,startsAt:'2026-10-12T10:15:00Z',endsAt:'2026-10-12T10:45:00Z'},receptionist)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);const booked=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value;await core.create('appointments',{...input,startsAt:booked.endsAt,endsAt:new Date(Date.parse(booked.endsAt)+1800000).toISOString()},receptionist);},60000);
 test('parallel invoice issue has unique numbers and atomic snapshots/outbox',async()=>{const drafts=await Promise.all(Array.from({length:4},()=>draftInvoice()));const issued=await Promise.all(drafts.map(d=>core.execute('invoices.issue',{id:d.id,expectedVersion:1},owner)));expect(new Set(issued.map(i=>i.number)).size).toBe(4);for(const invoice of issued){expect(invoice.snapshot.total).toBe('11.28');expect(await db.get('documents',invoice.documentId)).not.toBeNull();}const events=await db.list('outbox',{eq:{organizationId:org,type:'invoice.issued'},limit:10000});expect(events).toHaveLength(4);},60000);
 test('clinical signature/amendment and independent result lifecycle persist',async()=>{const encounter=await core.create('encounters',{branchId:branch,patientId,doctorId:doctor.id,content},doctor);const signed=await core.execute('encounters.sign',{id:encounter.id,expectedVersion:1},doctor);const amended=await core.execute('encounters.amend',{id:encounter.id,expectedVersion:2,reason:'Synthetic correction',content},doctor);expect(amended.signedSnapshot).toEqual(signed.signedSnapshot);const result=await core.create('results',{branchId:branch,patientId,title:'Synthetic result',reviewerId:doctor.id},doctor);await core.execute('results.review',{id:result.id,expectedVersion:1,summary:'Synthetic review',actionRequired:true},doctor);const released=await core.execute('results.release',{id:result.id,expectedVersion:2},doctor);expect(released.contactState).toBe('pending');expect(released.actionState).toBe('required');},60000);
 test('idempotent payment, refund and immutable invoice snapshots persist',async()=>{const draft=await draftInvoice();const issued=await core.execute('invoices.issue',{id:draft.id,expectedVersion:1},owner);const input={invoiceId:issued.id,amount:'5.00',method:'cash',idempotencyKey:`pay-${prefix}-0001`};const results=await Promise.all([core.execute('payments.record',input,owner),core.execute('payments.record',input,owner)]);expect(results[0].id).toBe(results[1].id);await core.execute('refunds.record',{paymentId:results[0].id,amount:'1.00',reason:'Synthetic refund',idempotencyKey:`refund-${prefix}-0001`},owner);const current=await core.get('invoices',issued.id,owner);expect(current.balance).toBe('7.28');expect(current.snapshot).toEqual(issued.snapshot);},60000);
 test('payroll snapshots, content publication, chat and notifications persist across modules',async()=>{const employee=await core.create('employees',{branchId:branch,userId:doctor.id,name:'Synthetic doctor',email:'doctor@example.test',jobTitle:'Doctor',salary:{currency:'USD',base:'1000'}},owner);const payrun=await core.create('payroll',{branchId:branch,period:'2026-10',employeeIds:[employee.id]},owner);const approved=await core.execute('payroll.approve',{id:payrun.id,expectedVersion:1},owner);expect((await core.get('documents',approved.documentIds[0],doctor)).snapshot.net).toBe('1000.00');const page=await core.create('pages',{title:'Synthetic public page',slug:`synthetic-${prefix}`,kind:'about',locale:'en',content},owner);const published=await core.execute('pages.publish',{id:page.id,expectedVersion:1},owner);expect(published.publishedSnapshot.content).toEqual(content);const conversation=await core.create('conversations',{branchId:branch,title:'Synthetic staff chat',kind:'staff',participantIds:[owner.id,doctor.id]},owner);await core.execute('conversations.send',{conversationId:conversation.id,body:'Synthetic message',idempotencyKey:`message-${prefix}-001`},owner);expect(await core.list('messages',doctor)).toHaveLength(1);expect((await db.list('outbox',{eq:{organizationId:org,type:'notification.requested'}})).some(n=>(n.payload as any).userId===doctor.id&&(n.payload as any).category==='messages')).toBe(true);},60000);
 test('patient identity isolation, prescriptions, referral release and reminder consent use the same rules',async()=>{
  const second=await core.create('patients',{branchId:branch,name:'Another synthetic patient',email:'shared@example.test',phone:'000000'},receptionist);const third=await core.create('patients',{branchId:branch,name:'Same-contact synthetic patient',email:'shared@example.test',phone:'000000'},receptionist);expect(second.id).not.toBe(third.id);
  const portal:Actor={...owner,id:`portal-${prefix}`,roles:['patient'],branchIds:[],patientIds:[second.id]};await db.put('users',row(portal.id,{...portal,status:'active'}));await expect(core.get('patients',third.id,portal)).rejects.toMatchObject({code:'NOT_FOUND'});
  const visit=await core.create('encounters',{branchId:branch,patientId:second.id,doctorId:doctor.id,content},doctor);const prescription=await core.create('prescriptions',{branchId:branch,patientId:second.id,encounterId:visit.id,medications:[{name:'Synthetic medication',dose:'Synthetic dose',route:'oral',frequency:'daily',duration:'one day'}]},doctor);
  await expect(core.execute('prescriptions.sign',{id:prescription.id,expectedVersion:1},doctor)).rejects.toMatchObject({code:'STATE'});await core.execute('encounters.sign',{id:visit.id,expectedVersion:1},doctor);await core.execute('prescriptions.sign',{id:prescription.id,expectedVersion:1},doctor);expect((await core.get('prescriptions',prescription.id,portal)).status).toBe('signed');await expect(core.update('prescriptions',prescription.id,{expectedVersion:2,status:'draft'},owner)).rejects.toMatchObject({code:'FORBIDDEN'});
  const referral=await core.create('referrals',{branchId:branch,patientId:second.id,encounterId:visit.id,destination:'Synthetic specialist',reason:'Synthetic reason'},doctor);await expect(core.get('referrals',referral.id,portal)).rejects.toMatchObject({code:'NOT_FOUND'});await core.execute('referrals.release',{id:referral.id,expectedVersion:1},doctor);expect((await core.get('referrals',referral.id,portal)).released).toBe(true);
  const consent=await core.execute('consents.record',{branchId:branch,patientId:second.id,purpose:'reminders',granted:true,versionLabel:'1',source:'portal'},portal);expect(consent.recordedBy).toBe(portal.id);await expect(core.execute('consents.record',{branchId:branch,patientId:third.id,purpose:'reminders',granted:true,versionLabel:'1',source:'portal'},portal)).rejects.toMatchObject({code:'FORBIDDEN'});
 },60000);
 test('CRM contact history, task completion and immutable credit notes remain consistent',async()=>{
  const lead=await core.create('leads',{branchId:branch,name:'Synthetic inquiry',source:'contract-test',assignedTo:receptionist.id,email:'lead@example.test'},receptionist);const contacted=await core.execute('leads.contact',{id:lead.id,expectedVersion:1,note:'Synthetic callback',outcome:'Reached'},receptionist);expect(contacted.stage).toBe('contacted');expect(contacted.contactAttempts).toHaveLength(1);await core.execute('leads.transition',{id:lead.id,expectedVersion:2,stage:'qualified'},receptionist);await expect(core.execute('leads.transition',{id:lead.id,expectedVersion:3,stage:'closed'},receptionist)).rejects.toMatchObject({code:'VALIDATION'});
  const task=await core.create('tasks',{branchId:branch,patientId,title:'Synthetic clinical follow-up',assignedTo:doctor.id,category:'clinical'},doctor);await core.execute('tasks.complete',{id:task.id,expectedVersion:1,note:'Synthetic action completed'},doctor);await expect(core.execute('tasks.complete',{id:task.id,expectedVersion:2},doctor)).rejects.toMatchObject({code:'STATE'});
  const draft=await draftInvoice();const issued=await core.execute('invoices.issue',{id:draft.id,expectedVersion:1},owner);const input={invoiceId:issued.id,amount:'2.00',reason:'Synthetic credit',idempotencyKey:`credit-${prefix}-001`};const first=await core.execute('invoices.credit',input,owner),replay=await core.execute('invoices.credit',input,owner);expect(first.id).toBe(replay.id);const after=await core.get('invoices',issued.id,owner);expect(after.balance).toBe('9.28');expect(after.creditedAmount).toBe('2.00');expect(after.snapshot).toEqual(issued.snapshot);
 },60000);
 test('offline encrypted roundtrip preserves historical versions on this adapter',async()=>{
  const directory=await mkdtemp(join(tmpdir(),'adapter-transfer-'));try{
   const before=await db.list('invoices',{eq:{organizationId:org},limit:10000});const opts={database:db,storageRoot:join(directory,'source-files'),file:join(directory,'snapshot.backup'),transferKey:randomBytes(32).toString('base64'),appEncryptionKey:randomBytes(32).toString('base64'),maintenance:true,outboundEnabled:false};
   await exportInstallation(opts);
   // The certification target was explicitly confirmed disposable, and this suite owns every application record.
   const inventory=await (db as Database&{listCollections():Promise<string[]>}).listCollections();
   for(const collection of inventory){const entries=await db.list(collection,{limit:10000});expect(entries.every(e=>e.organizationId===org)).toBe(true);for(const item of entries)await db.remove(collection,item.id,item.version);}
   const restored=await importInstallation({...opts,storageRoot:join(directory,'restored-files')});expect(restored.sessionsInvalidated).toBe(true);expect(await db.list('invoices',{eq:{organizationId:org},limit:10000})).toEqual(before);expect((await db.get('users',doctor.id))?.sessionVersion).toBe(1);
  }finally{await rm(directory,{recursive:true,force:true});}
 },120000);

});
