/* Author: ramanpal singh | URL: https://kwebby.com */
import { Body,Controller,Get,Post,Patch,Put,Param,Query,Req,Res,Inject,UploadedFile,UseInterceptors } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import type { Request,Response } from 'express';
import { z } from 'zod';
import { assert,isCollection,type Collection,type Entity } from '../../../packages/contracts/src/index.js';
import { AiDraftService,runPublicTool,renderFinancialPdf,renderFinancialHtml,PUBLIC_TOOLS,analyzePublicWebsite } from '../../../packages/platform/src/index.js';
import { Runtime } from './runtime.js';
import { SecureUpload } from './guards.js';
import { entity } from './auth.js';
import { assertOrigin,publicOrigin,digest } from './security.js';
const ok=(data:unknown)=>({data});
export const publicJob=(row:Entity)=>Object.fromEntries(['id','version','createdAt','updatedAt','type','status','attempts','nextAttemptAt','startedAt','completedAt','failureCode'].filter(key=>row[key]!==undefined).map(key=>[key,row[key]]));
type Upload={buffer:Buffer;originalname:string;mimetype:string};

@Controller('api/v1/auth')
export class AuthController {
 constructor(@Inject(Runtime) private r:Runtime){}
 @Get('status') async status(){return ok(await this.r.auth.status());}
 @Get('session') async session(@Req() req:Request){return ok(await this.r.auth.session(req));}
 @Post('bootstrap') async bootstrap(@Body() body:unknown,@Req() req:Request,@Res({passthrough:true}) res:Response){return ok(await this.r.auth.bootstrap(body,req,res));}
 @Post('register') async register(@Body() body:unknown,@Req() req:Request,@Res({passthrough:true}) res:Response){return ok(await this.r.auth.register(body,req,res));}
 @Post('login') async login(@Body() body:unknown,@Req() req:Request,@Res({passthrough:true}) res:Response){return ok(await this.r.auth.login(body,req,res));}
 @Post('revoke-sessions') async revoke(@Req() req:Request){return ok(await this.r.auth.revokeSessions(req));}
 @Post('logout') async logout(@Req() req:Request,@Res({passthrough:true}) res:Response){return ok(await this.r.auth.logout(req,res));}
 @Post('mfa/begin') async mfa(@Req() req:Request){return ok(await this.r.auth.mfaBegin(req));}
 @Post('mfa/confirm') async confirm(@Body() body:unknown,@Req() req:Request){return ok(await this.r.auth.mfaConfirm(body,req));}
 @Get('team') async team(@Req() req:Request){return ok(await this.r.auth.team(await this.r.auth.require(req)));}
 @Post('invite') async invite(@Body() body:unknown,@Req() req:Request){return ok(await this.r.auth.invite(body,await this.r.auth.require(req)));}
 @Post('accept-invite') async accept(@Body() body:unknown,@Req() req:Request,@Res({passthrough:true}) res:Response){return ok(await this.r.auth.acceptInvite(body,req,res));}
 @Patch('team/:id') async change(@Param('id') id:string,@Body() body:Record<string,unknown>,@Req() req:Request){return ok(await this.r.auth.changeUser({...body,id},await this.r.auth.require(req)));}
 @Post('reset-password') async reset(@Body() body:unknown,@Req() req:Request){return ok(await this.r.auth.requestReset(body,req));}
 @Post('consume-token') async consume(@Body() body:unknown,@Req() req:Request){return ok(await this.r.auth.consumeToken(body,req));}
}

@Controller('api/v1')
export class ClinicController {
 constructor(@Inject(Runtime) private r:Runtime){}
 @Get('health') health(){return ok({status:'ok',version:'0.1.0'});}
 @Get('ready') async ready(){await this.r.redis.ping();await this.r.db.list('settings',{limit:1});return ok({ready:true,database:this.r.db.driver});}
 @Get('dashboard') async dashboard(@Req() req:Request){return ok(await this.r.clinic.dashboard(await this.r.auth.require(req)));}
 @Get('directory') async directory(@Req() req:Request){const actor=await this.r.auth.require(req),patient=actor.roles.every(r=>r==='patient');const branches=new Set(actor.branchIds);if(patient)for(const id of actor.patientIds){const p=await this.r.db.get('patients',id);if(p?.organizationId===actor.organizationId)branches.add(String(p.branchId));}const users=await this.r.db.list('users',{eq:{organizationId:actor.organizationId,status:'active'}});return ok(users.filter(u=>{const roles=u.roles as string[],scopes=u.branchIds as string[];if(!Array.isArray(roles)||roles.every(r=>r==='patient'))return false;if(patient&&!roles.some(r=>['owner','admin','manager','receptionist'].includes(r)))return false;return actor.roles.some(r=>['owner','admin'].includes(r))||scopes.some(b=>branches.has(b));}).map(u=>({id:u.id,name:u.name,roles:u.roles,branchIds:(u.branchIds as string[]).filter(b=>actor.roles.some(r=>['owner','admin'].includes(r))||branches.has(b))})));}
 @Get('records/:collection') async list(@Param('collection') c:string,@Query() q:Record<string,string>,@Req() req:Request){assert(isCollection(c),'NOT_FOUND','Collection not found',404);const actor=await this.r.auth.require(req);const eq:Record<string,string|boolean>={};for(const [key,value]of Object.entries(q)){if(!['limit','after'].includes(key)){assert(/^[a-zA-Z][a-zA-Z0-9_]{0,63}$/.test(key),'QUERY','Invalid filter');eq[key]=['true','false'].includes(value)?value==='true':value;}}return ok(await this.r.clinic.list(c,actor,{limit:q.limit?Number(q.limit):100,after:q.after,eq}));}
 @Get('records/:collection/:id') async get(@Param('collection') c:string,@Param('id') id:string,@Req() req:Request){assert(isCollection(c),'NOT_FOUND','Collection not found',404);return ok(await this.r.clinic.get(c,id,await this.r.auth.require(req)));}
 @Post('records/:collection') async create(@Param('collection') c:string,@Body() body:unknown,@Req() req:Request){assert(isCollection(c),'NOT_FOUND','Collection not found',404);return ok(await this.r.clinic.create(c,body,await this.r.auth.require(req)));}
 @Patch('records/:collection/:id') async update(@Param('collection') c:string,@Param('id') id:string,@Body() body:Record<string,unknown>,@Req() req:Request){assert(isCollection(c),'NOT_FOUND','Collection not found',404);const {expectedVersion,...data}=body;assert(Number.isInteger(expectedVersion),'VERSION','An expected version is required');return ok(await this.r.clinic.update(c,id,{...data,expectedVersion:Number(expectedVersion)},await this.r.auth.require(req)));}
 @Post('actions/:action') async action(@Param('action') action:string,@Body() body:unknown,@Req() req:Request){return ok(await this.r.clinic.execute(action,body,await this.r.auth.require(req)));}
 @Get('integrations') async integrations(@Req() req:Request){return ok(await this.r.integrations.list(await this.r.auth.require(req)));}
 @Get('integrations/:name') async integration(@Param('name') name:string,@Req() req:Request){return ok(await this.r.integrations.get(name,await this.r.auth.require(req)));}
 @Put('integrations/:name') async configure(@Param('name') name:string,@Body() body:unknown,@Req() req:Request){return ok(await this.r.integrations.save(name,body,await this.r.auth.require(req)));}
 @Post('integrations/smtp/test') async testMail(@Body() body:unknown,@Req() req:Request){return ok(await this.r.integrations.testMail(body,await this.r.auth.require(req)));}
 @Get('payments/activity') async paymentActivity(@Req() req:Request){const actor=await this.r.auth.require(req);assert(actor.roles.some(r=>['owner','admin','accountant'].includes(r)),'FORBIDDEN','Finance access required',403);const invoices=await this.r.clinic.list('invoices',actor,{limit:500}),ids=new Set(invoices.map(i=>i.id));const view=(row:Entity,fields:string[])=>Object.fromEntries(fields.filter(k=>row[k]!==undefined).map(k=>[k,row[k]]));const attempts=(await this.r.db.list('paymentAttempts',{eq:{organizationId:actor.organizationId},limit:10000})).filter(r=>ids.has(String(r.invoiceId))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,500).map(r=>view(r,['id','invoiceId','provider','amount','currency','status','providerReference','createdAt']));const refunds=(await this.r.db.list('refundRequests',{eq:{organizationId:actor.organizationId},limit:10000})).filter(r=>ids.has(String(r.invoiceId))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,500).map(r=>view(r,['id','paymentId','invoiceId','provider','amount','status','providerRefundId','createdAt']));return ok({attempts,refunds,limit:500});}
 @Post('payments/:provider/checkout') async checkout(@Param('provider') provider:string,@Body() body:unknown,@Req() req:Request){return ok(await this.r.payments.checkout(provider,body,await this.r.auth.require(req)));}
 @Post('payments/:provider/refund/reconcile') async reconcileRefund(@Param('provider') provider:string,@Body() body:unknown,@Req() req:Request){return ok(await this.r.payments.reconcileRefund(provider,body,await this.r.auth.require(req)));}
 @Post('payments/:provider/refund') async refund(@Param('provider') provider:string,@Body() body:unknown,@Req() req:Request){return ok(await this.r.payments.refund(provider,body,await this.r.auth.require(req)));}
 @Post('payments/:provider/reconcile') async reconcile(@Param('provider') provider:string,@Body() body:unknown,@Req() req:Request){return ok(await this.r.payments.reconcile(provider,body,await this.r.auth.require(req)));}
 @Post('webhooks/:provider') async webhook(@Param('provider') provider:string,@Req() req:Request&{rawBody?:Buffer}){assert(req.rawBody,'BODY','A raw webhook body is required');return ok(await this.r.payments.webhook(provider,req.rawBody,req.get(provider==='stripe'?'stripe-signature':'x-razorpay-signature')??'',req.get('x-razorpay-event-id')));}
 @Post('public-assets') @SecureUpload('owner','admin','editor') @UseInterceptors(FileInterceptor('file',{limits:{fileSize:10*1024*1024,files:1,fields:1}}))
 async publicAssetUpload(@UploadedFile() file:Upload,@Body() body:unknown,@Req() req:Request){const actor=await this.r.auth.require(req);assert(file,'FILE','Choose an image');const {alt}=z.object({alt:z.string().min(1).max(500)}).strict().parse(body);return ok(await this.r.publicAssets.upload({bytes:file.buffer,mime:file.mimetype,alt},actor));}
 @Post('files') @SecureUpload() @UseInterceptors(FileInterceptor('file',{limits:{fileSize:20*1024*1024,files:1,fields:4}}))
 async upload(@UploadedFile() file:Upload,@Body() body:Record<string,string>,@Req() req:Request){const actor=await this.r.auth.require(req);assert(file,'FILE','Choose a file');const options=z.object({patientId:z.string().optional(),scope:z.enum(['clinical','conversation','personal','payroll']).optional()}).strict().parse(body);return ok(await this.r.files.upload({bytes:file.buffer,name:file.originalname,mime:file.mimetype,...options},actor));}
 @Get('files/:id') async file(@Param('id') id:string,@Req() req:Request,@Res() res:Response){const data=await this.r.files.read(id,await this.r.auth.require(req));res.type(String(data.record.mime)).setHeader('Content-Disposition',`attachment; filename="document"; filename*=UTF-8''${encodeURIComponent(String(data.record.originalName??'document'))}`);res.send(data.bytes);}
 @Post('themes/import') @SecureUpload('owner','admin','editor') @UseInterceptors(FileInterceptor('file',{limits:{fileSize:25*1024*1024,files:1,fields:0}}))
 async importTheme(@UploadedFile() file:Upload,@Req() req:Request){const actor=await this.r.auth.require(req);assert(file,'FILE','Choose a ZIP theme');return ok(await this.r.themes.importZip(file.buffer,actor));}
 @Get('themes/:id/preview') async preview(@Param('id') id:string,@Req() req:Request){return ok(await this.r.themes.preview(id,await this.r.auth.require(req)));}
 @Get('themes/:id/export') async exportTheme(@Param('id') id:string,@Req() req:Request,@Res() res:Response){const bytes=await this.r.themes.exportZip(id,await this.r.auth.require(req));res.type('application/zip').setHeader('Content-Disposition','attachment; filename="clinic-theme.zip"');res.send(bytes);}
 @Post('themes/:id/activate') async activate(@Param('id') id:string,@Body() body:unknown,@Req() req:Request){const data=z.object({expectedPublicationId:z.string().nullable().optional()}).strict().parse(body);return ok(await this.r.themes.activate(id,await this.r.auth.require(req),data.expectedPublicationId??undefined));}
 @Post('themes/rollback') async rollback(@Body() body:unknown,@Req() req:Request){const data=z.object({expectedPublicationId:z.string().optional()}).strict().parse(body);return ok(await this.r.themes.rollback(await this.r.auth.require(req),data.expectedPublicationId));}
 @Post('ai/draft') async ai(@Body() body:unknown,@Req() req:Request){const actor=await this.r.auth.require(req);await this.r.limiter.take(`ai:${actor.id}`,10,60);const data=z.object({task:z.enum(['note','intake','chart','extract','reply','tasks']),text:z.string().max(64000),patientId:z.string().optional()}).strict().parse(body);const cfg=await this.r.integrations.config('ai',actor.organizationId);assert(cfg,'AI_NOT_CONFIGURED','Configure an AI provider first',503);return ok(await new AiDraftService(this.r.db,cfg as any).draft(data.task,{text:data.text,patientId:data.patientId},actor));}
 @Post('ai/transcribe') @SecureUpload('doctor','nurse') @UseInterceptors(FileInterceptor('file',{limits:{fileSize:20*1024*1024,files:1,fields:0}}))
 async transcribe(@UploadedFile() file:Upload,@Req() req:Request){const actor=await this.r.auth.require(req);assert(file,'FILE','Choose an audio recording');await this.r.limiter.take(`ai:${actor.id}`,10,60);const cfg=await this.r.integrations.config('ai',actor.organizationId);assert(cfg,'AI_NOT_CONFIGURED','Configure an AI provider first',503);return ok(await new AiDraftService(this.r.db,cfg as any).transcribe(file.buffer,file.mimetype,actor));}
 @Get('documents/:id/pdf') async pdf(@Param('id') id:string,@Req() req:Request,@Res() res:Response){const doc=await this.r.clinic.get('documents',id,await this.r.auth.require(req));assert(['invoice','payslip','credit-note'].includes(String(doc.kind)),'DOCUMENT','This document has no financial PDF',400);const snapshot=doc.snapshot as any;const design=snapshot.template?.design??{};const logoDataUri=design.showLogo!==false&&snapshot.business?.logoFileId?await this.r.publicAssets.logoDataUri(String(snapshot.business.logoFileId),this.r.org):undefined;const template={accent:design.accent,font:design.font??'sans',footer:design.footer??'',terms:design.terms??'',columns:design.columns,showLogo:design.showLogo??true,...(logoDataUri?{logoDataUri}:{})};const bytes=await renderFinancialPdf({kind:doc.kind,snapshot} as any,template as any);res.type('application/pdf').setHeader('Content-Disposition','attachment; filename="clinic-document.pdf"');res.send(bytes);}
 @Get('audit') async audit(@Req() req:Request){const actor=await this.r.auth.require(req);assert(actor.roles.some(r=>['owner','admin'].includes(r)),'FORBIDDEN','Administrator access required',403);return ok(await this.r.db.list('audit',{eq:{organizationId:actor.organizationId},limit:500}));}
 @Get('jobs') async jobs(@Req() req:Request){const actor=await this.r.auth.require(req);assert(actor.roles.some(r=>['owner','admin'].includes(r)),'FORBIDDEN','Administrator access required',403);const rows=await this.r.db.list('outbox',{eq:{organizationId:actor.organizationId},limit:500});return ok(rows.map(publicJob));}
 @Post('jobs/:id/retry') async retry(@Param('id') id:string,@Req() req:Request){const actor=await this.r.auth.require(req);assert(actor.roles.some(r=>['owner','admin'].includes(r)),'FORBIDDEN','Administrator access required',403);return ok(await this.r.db.transaction([`outbox:${id}`],async tx=>{const row=await tx.get('outbox',id);assert(row&&row.organizationId===actor.organizationId&&row.status==='failed','JOB','Retry a failed job only',409);const updated=await tx.put('outbox',{...row,status:'pending',nextAttemptAt:new Date().toISOString(),version:row.version+1,updatedAt:new Date().toISOString()},row.version);await tx.put('audit',{...entity(actor.organizationId),actorId:actor.id,action:'outbox.retry',resourceId:row.id});return publicJob(updated);}));}
}

@Controller('api/v1/public')
export class PublicController {
 constructor(@Inject(Runtime) private r:Runtime){}
 @Get('assets/:id') async publicAsset(@Param('id') id:string,@Res() res:Response){const asset=await this.r.publicAssets.read(id,this.r.org);res.removeHeader('X-Robots-Tag');res.type(asset.mime).setHeader('Cache-Control','public, max-age=31536000, immutable');res.setHeader('ETag',`"${asset.sha256}"`);res.setHeader('Content-Disposition','inline');res.send(asset.bytes);}
 private async published():Promise<Record<string,any>[]>{const publication=await this.r.themes.publicSite(this.r.org);if(publication.pages!==null)return publication.pages.map(p=>({...p,status:'published'}));const pages=await this.r.db.list('pages',{eq:{organizationId:this.r.org}});return pages.filter(p=>p.publishedSnapshot).map(p=>({...p.publishedSnapshot as Record<string,unknown>,status:'published'}));}
 @Get('site') async site(){
  const b=await this.r.db.get('settings','business'),theme=await this.r.themes.publicSite(this.r.org);
  const business=(theme.settings?.business??b?.value??{}) as any;
  const rawWebsite=(theme.settings?.website??{}) as Record<string,any>;
  // Draft website settings never become public, including before the first publication.
  const website=Object.fromEntries(['siteName','origin','description','locale','socialImage','socialImageAlt','socialHandles','searchConsoleVerification','navigation','homepage','branding','locations','header','footer'].filter(key=>rawWebsite[key]!==undefined).map(key=>[key,rawWebsite[key]]));
  const locations=Array.isArray(website.locations)?website.locations:[],primaryLocation=locations.find(location=>location.primary)??locations[0];
  const availability=await this.r.db.list('availability',{eq:{organizationId:this.r.org,public:true}}),profiles=await this.r.db.list('employees',{eq:{organizationId:this.r.org,publicProfile:true}}),doctors=[];
  for(const id of new Set(availability.map(a=>String(a.doctorId)))){const u=await this.r.db.get('users',id),profile=profiles.find(p=>p.userId===id&&p.active!==false);if(u&&profile&&u.organizationId===this.r.org&&u.status==='active'&&(u.roles as string[])?.includes('doctor'))doctors.push({id:u.id,name:profile.name,branchIds:[...new Set(availability.filter(a=>a.doctorId===u.id).map(a=>String(a.branchId)))].filter(branchId=>Array.isArray(u.branchIds)&&u.branchIds.includes(branchId)),jobTitle:profile.jobTitle,specialty:profile.specialty??'',registrationNumber:profile.registrationNumber??''});}
  const logoId=website.branding?.logo?.assetId??business.logoFileId;
  return ok({audience:process.env.INSTALLATION_AUDIENCE==='business'?'business':'patient',name:website.siteName??business.clinicName??'Your clinic',description:website.description??'Personal care, thoughtfully organized.',url:publicOrigin(),locale:website.locale??business.locale??'en',currency:business.currency??'USD',timezone:primaryLocation?.timezone??business.timezone??'UTC',address:primaryLocation?.address??business.address??'',email:primaryLocation?.email??business.email??'',phone:primaryLocation?.phone??business.phone??'',displayPhone:primaryLocation?.displayPhone??primaryLocation?.phone??business.phone??'',logo:logoId?`/api/v1/public/assets/${encodeURIComponent(logoId)}`:null,socialImage:website.socialImage,socialImageAlt:website.socialImageAlt,socialHandle:website.socialHandles?.x,socialProfiles:Object.values(website.socialHandles??{}).filter(value=>typeof value==='string'&&/^https:\/\//.test(value)),searchConsoleVerification:website.searchConsoleVerification,navigation:website.navigation,homepage:website.homepage,branding:website.branding,header:website.header,footer:website.footer,locations,website,doctors,services:await this.publicServices(),theme:{manifest:theme.manifest,publicationId:theme.publicationId,themeId:'themeId' in theme?theme.themeId:undefined},pages:await this.published()});
 }
 private async publicServices(){const rows=await this.r.db.list('services',{eq:{organizationId:this.r.org,public:true}});return rows.map(r=>({id:r.id,branchId:r.branchId,name:r.name,description:r.description,price:r.price,currency:r.currency,durationMinutes:r.durationMinutes}));}
 @Get('services') async services(){return ok(await this.publicServices());}
 @Get('pages') async pages(){return ok(await this.published());}
 @Get('pages/:slug') async page(@Param('slug') slug:string,@Query('locale') locale:string){const pages=await this.published();const page=pages.find(p=>p.slug===slug&&(!locale||p.locale===locale));if(page)return ok(page);const routes=await this.r.db.list('pageRoutes',{eq:{organizationId:this.r.org,slug,...(locale?{locale}:{})}});const route=routes.find(r=>r.status==='redirect');assert(route,'NOT_FOUND','Page not found',404);return ok({redirect:route.redirectSlug,statusCode:308});}
 private async bookingBranch(requested?:string):Promise<string>{
  const site=await this.r.themes.publicSite(this.r.org),locations=(site.settings?.website?.locations??[]) as {branchId:string;primary?:boolean}[];
  const branchId=requested??locations.find(location=>location.primary)?.branchId??locations[0]?.branchId??'main';
  z.string().min(1).max(100).regex(/^[A-Za-z0-9_-]+$/).parse(branchId);
  assert(locations.length?locations.some(location=>location.branchId===branchId):branchId==='main','BOOKING_BRANCH','Choose a published clinic location',400);
  return branchId;
 }
 @Get('availability') async availability(@Query('doctorId') doctorId:string,@Query('date') date:string,@Query('branchId') branchId:string,@Req() req:Request){
  await this.r.limiter.take(`availability:${req.ip}`,10,60);z.string().min(1).max(128).parse(doctorId);const publicProfiles=await this.r.db.list('employees',{eq:{organizationId:this.r.org,userId:doctorId,publicProfile:true}});assert(publicProfiles.some(p=>p.active!==false),'NOT_FOUND','Practitioner availability is not public',404);z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(date);const center=Date.parse(date+'T00:00:00Z');assert(Number.isFinite(center)&&center>Date.now()-86400000&&center<Date.now()+366*86400000,'DATE','Choose a date within the next year');
  const chosenBranch=branchId?await this.bookingBranch(branchId):undefined;
  const rules=await this.r.db.list('availability',{eq:{organizationId:this.r.org,doctorId,public:true,...(chosenBranch?{branchId:chosenBranch}:{})}}),bookings=await this.r.db.list('appointments',{eq:{organizationId:this.r.org,doctorId}}),employees=await this.r.db.list('employees',{eq:{organizationId:this.r.org,userId:doctorId}}),leave=await this.r.db.list('leave',{eq:{organizationId:this.r.org,status:'approved'}});const slots:{startsAt:string;endsAt:string}[]=[];
  const busy=(start:number,end:number)=>bookings.some(b=>!['cancelled','no-show'].includes(String(b.status))&&Date.parse(String(b.startsAt))<end&&Date.parse(String(b.endsAt))>start)||leave.some(l=>employees.some(e=>e.id===l.employeeId)&&Date.parse(String(l.startsAt))<end&&Date.parse(String(l.endsAt))>start);
  assert(rules.length<=20,'AVAILABILITY_CONFIG','Contact the clinic to confirm availability',503);for(const rule of rules){const format=new Intl.DateTimeFormat('en-CA',{timeZone:String(rule.timezone),year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});for(let t=center-86400000;t<center+2*86400000;t+=60000){if(t<=Date.now())continue;const p=Object.fromEntries(format.formatToParts(t).map(v=>[v.type,v.value]));if(`${p.year}-${p.month}-${p.day}`!==date||['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(p.weekday)!==rule.weekday)continue;const minutes=Number(p.hour)*60+Number(p.minute),[h,m]=String(rule.startTime).split(':').map(Number),[eh,em]=String(rule.endTime).split(':').map(Number),duration=Number(rule.slotMinutes);if(minutes<h*60+m||(minutes-h*60-m)%duration||minutes+duration>eh*60+em)continue;const end=t+duration*60000;if(!busy(t,end))slots.push({startsAt:new Date(t).toISOString(),endsAt:new Date(end).toISOString()});}}
  return ok([...new Map(slots.map(slot=>[slot.startsAt,slot])).values()].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)));
 }
 @Post('booking') async booking(@Body() body:unknown,@Req() req:Request){
  assertOrigin(req);await this.r.limiter.take(`booking:${req.ip}`,5,3600);
  const data=z.object({name:z.string().min(2).max(120),phone:z.string().min(5).max(50),email:z.email().optional(),branchId:z.string().min(1).max(100).regex(/^[A-Za-z0-9_-]+$/).optional(),serviceId:z.string().max(128).optional(),doctorId:z.string().max(128).optional(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),startsAt:z.iso.datetime().optional(),endsAt:z.iso.datetime().optional(),reason:z.string().max(1000).optional(),contactConsent:z.literal(true)}).strict().parse(body);
  const branchId=await this.bookingBranch(data.branchId);
  if(data.serviceId){const service=await this.r.db.get('services',data.serviceId);assert(service&&service.organizationId===this.r.org&&service.public===true&&service.branchId===branchId,'BOOKING_SERVICE','Choose a public service at this clinic location',400);}
  if(data.doctorId){
   const doctor=await this.r.db.get('users',data.doctorId),profiles=await this.r.db.list('employees',{eq:{organizationId:this.r.org,userId:data.doctorId,publicProfile:true}}),rules=await this.r.db.list('availability',{eq:{organizationId:this.r.org,doctorId:data.doctorId,branchId,public:true}});
   assert(doctor&&doctor.organizationId===this.r.org&&doctor.status==='active'&&Array.isArray(doctor.roles)&&doctor.roles.includes('doctor')&&Array.isArray(doctor.branchIds)&&doctor.branchIds.includes(branchId)&&profiles.some(profile=>profile.active!==false)&&rules.length>0,'BOOKING_DOCTOR','Choose a public clinician at this clinic location',400);
  }
  await this.r.db.transaction([`booking-inquiry:${digest(data.phone)}`],async tx=>{const lead={...entity(this.r.org),name:data.name,phone:data.phone,...(data.email?{email:data.email}:{}),source:'appointment-request',interest:data.reason??'Appointment request',branchId,marketingConsent:false,contactConsentAt:new Date().toISOString(),requestedAppointment:{...data,branchId},stage:'new',contactAttempts:[]};await tx.put('leads',lead);await tx.put('outbox',{...entity(this.r.org),type:'lead.created',status:'pending',payload:{leadId:lead.id},attempts:0,nextAttemptAt:new Date().toISOString()});});return ok({received:true,reserved:false,branchId});
 }
 @Post('leads') async lead(@Body() body:unknown,@Req() req:Request){assertOrigin(req);await this.r.limiter.take(`lead:${req.ip}`,5,3600);const data=z.object({name:z.string().min(2).max(120),email:z.email(),phone:z.string().max(50).optional(),interest:z.string().max(1000).optional(),source:z.string().max(100).default('website'),marketingConsent:z.boolean().default(false),branchId:z.string().max(100).default('main'),attribution:z.object({utmSource:z.string().max(100).optional(),utmMedium:z.string().max(100).optional(),utmCampaign:z.string().max(100).optional(),referrer:z.string().max(200).optional()}).strict().optional()}).strict().parse(body);await this.r.db.transaction([`lead:${digest(data.email)}`],async tx=>{const lead={...entity(this.r.org),...data,stage:'new',contactAttempts:[]};await tx.put('leads',lead);await tx.put('outbox',{...entity(this.r.org),type:'lead.created',status:'pending',payload:{leadId:lead.id},attempts:0,nextAttemptAt:new Date().toISOString()});});return ok({received:true,message:'The clinic will contact you.'});}
 @Get('tools') tools(){const audience=process.env.INSTALLATION_AUDIENCE==='business'?'business':'patient';return ok(PUBLIC_TOOLS.filter(t=>t.audience===audience));}
 @Post('tools/:tool') async tool(@Param('tool') tool:string,@Body() body:unknown,@Req() req:Request){assertOrigin(req);await this.r.limiter.take(`tool:${req.ip}`,20,3600);const data=z.object({input:z.record(z.string(),z.unknown()),email:z.email().optional(),marketingConsent:z.boolean().default(false)}).strict().parse(body);const audience=process.env.INSTALLATION_AUDIENCE==='business'?'business':'patient';assert(tool!=='website-analyzer'||audience==='business','NOT_FOUND','Tool not available',404);const business=(await this.r.db.get('settings','business'))?.value as any;const services=await this.publicServices();const analysis=tool==='website-analyzer'?await analyzePublicWebsite(z.object({url:z.url().max(2048)}).strict().parse(data.input).url):null;const result=analysis?{summary:'Your booking website overview',items:[String(analysis.scope)],values:{score:analysis.score},...analysis}:runPublicTool(tool,data.input,{audience,currency:business?.currency,serviceFees:Object.fromEntries(services.map(s=>[s.id,Number(s.price)]))});if(data.email)await this.r.db.transaction([`tool-report:${digest(data.email)}`],async tx=>{await tx.put('outbox',{...entity(this.r.org),type:'email.send',status:'pending',payload:{to:data.email,template:'tool.report',data:{summary:result.summary,items:result.items,values:result.values}},attempts:0,nextAttemptAt:new Date().toISOString()});await tx.put('leads',{...entity(this.r.org),name:data.email,email:data.email,source:`tool:${tool}`,marketingConsent:data.marketingConsent,contactPurpose:'requested-tool-report',consentAt:new Date().toISOString(),stage:'new',branchId:'main',contactAttempts:[]});});return ok(audience==='business'&&!data.email?{summary:result.summary,items:[],values:{},detailedReportRequiresEmail:true}:result);}
 @Get('themes/:id/assets/*path') async asset(@Param('id') id:string,@Param('path') path:string|string[],@Req() req:Request,@Res() res:Response){const data=await this.r.themes.asset(id,Array.isArray(path)?path.join('/'):path,this.r.org);res.type(data.mime).send(data.bytes);}
}
