/* Author: ramanpal singh | URL: https://kwebby.com */
import { request } from 'node:http';
import { chromium } from '@playwright/test';
import { Decimal } from 'decimal.js';
import { z } from 'zod';
import { assert } from '../../contracts/src/index.js';
import { escapeHtml } from './common.js';
import { renderBlockNote } from './content.js';
import { detectMime } from './files.js';

const amount=z.string().regex(/^-?\d{1,13}(?:\.\d{1,6})?$/);
const business=z.object({clinicName:z.string().max(500).optional(),legalName:z.string().max(500).optional(),address:z.string().max(10000).optional(),email:z.string().max(254).optional(),phone:z.string().max(100).optional(),businessIds:z.unknown().optional(),bankDetails:z.string().max(10000).optional()});
const base=z.object({currency:z.string().regex(/^[A-Z]{3}$/),business,template:z.unknown().optional()});
const invoice=base.extend({number:z.string().max(256),issuedAt:z.string().max(100),patient:z.object({name:z.string().max(500),address:z.string().max(10000).optional(),email:z.string().max(254).optional()}),lines:z.array(z.object({description:z.string().max(1000),quantity:amount,unitPrice:amount,discount:amount.optional(),tax:amount.optional(),total:amount})).max(300),subtotal:amount,discountTotal:amount,taxTotal:amount,total:amount,notes:z.array(z.unknown()).max(1000).optional()});
const payslip=base.extend({employeeName:z.string().max(500),jobTitle:z.string().max(500).optional(),period:z.string().max(100),earnings:z.array(z.object({label:z.string().max(500),amount})).max(100),deductions:z.array(z.object({label:z.string().max(500),amount})).max(100),gross:amount,totalDeductions:amount,net:amount});
const creditNote=base.extend({number:z.string().max(256),issuedAt:z.string().max(100),invoiceNumber:z.string().max(256),patient:z.object({name:z.string().max(500),address:z.string().max(10000).optional(),email:z.string().max(254).optional()}),total:amount,reason:z.string().max(10000)});
const templateSchema=z.object({accent:z.string().regex(/^#[0-9a-fA-F]{6}$/).default('#18756B'),font:z.enum(['sans','system','serif','mono']).default('sans'),footer:z.string().max(10000).default(''),terms:z.string().max(10000).default(''),showQuantity:z.boolean().default(true),showLogo:z.boolean().default(true),logoDataUri:z.string().max(180000).regex(/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/).optional(),columns:z.array(z.enum(['description','quantity','unitPrice','discount','tax','total'])).min(1).max(6).optional()}).strict();
export type FinancialTemplate=z.input<typeof templateSchema>;
export type FinancialDocument={kind:'invoice';snapshot:z.input<typeof invoice>}|{kind:'payslip';snapshot:z.input<typeof payslip>}|{kind:'credit-note';snapshot:z.input<typeof creditNote>};
function money(value:string,currency:string,unitPrice=false):string {
 let digits:number;try{digits=new Intl.NumberFormat('en',{style:'currency',currency}).resolvedOptions().maximumFractionDigits??2;}catch{assert(false,'DOCUMENT_CURRENCY','Unsupported currency');}
 assert(digits<=3,'DOCUMENT_CURRENCY','Unsupported currency precision');
 const decimal=new Decimal(value);if(unitPrice)digits=Math.max(digits,decimal.decimalPlaces());assert(decimal.decimalPlaces()<=digits,'DOCUMENT_AMOUNT','Financial amount exceeds currency precision');const [whole,fraction]=decimal.abs().toFixed(digits).split('.');
 return `${currency} ${decimal.isNegative()?'-':''}${new Intl.NumberFormat('en').format(BigInt(whole))}${digits?'.'+fraction:''}`;
}
export function renderFinancialHtml(document:FinancialDocument,template:FinancialTemplate={}):string {
 const design=templateSchema.safeParse(template);assert(design.success,'DOCUMENT_TEMPLATE','Invalid financial document template');
 const result=(document.kind==='invoice'?invoice:document.kind==='credit-note'?creditNote:payslip).safeParse(document.snapshot);assert(result.success,'DOCUMENT_FORMAT','Invalid financial document snapshot');
 const data=result.data,style=design.data,company=data.business;let content='',subtitle='';
 if(style.logoDataUri){const binary=Buffer.from(style.logoDataUri.split(',')[1],'base64');assert(['image/png','image/jpeg','image/webp'].includes(detectMime(binary)??''),'DOCUMENT_LOGO','Logo content does not match an approved raster format');}
 const columns=[...new Set(style.columns??['description','quantity','unitPrice','total'])].filter(column=>style.showQuantity||column!=='quantity');
 const labels:Record<string,string>={description:'Description',quantity:'Quantity',unitPrice:'Unit price',discount:'Discount',tax:'Tax',total:'Total'};
 if(document.kind==='invoice') {
  const record=invoice.parse(data);subtitle=`Invoice ${record.number}`;
  content=`<div class="parties"><section><h2>Bill to</h2><strong>${escapeHtml(record.patient.name)}</strong><p>${escapeHtml(record.patient.address??'')}</p>${escapeHtml(record.patient.email??'')}</section><section><h2>Invoice details</h2><p>Number: ${escapeHtml(record.number)}</p><p>Issued: ${escapeHtml(record.issuedAt)}</p></section></div><table><thead><tr>${columns.map(column=>`<th class="${column==='description'?'':'number'}">${labels[column]}</th>`).join('')}</tr></thead><tbody>${record.lines.map(line=>`<tr>${columns.map(column=>`<td class="${column==='description'?'':'number'}">${column==='description'||column==='quantity'?escapeHtml(line[column]):escapeHtml(money((line as Record<string,string|undefined>)[column]??'0',record.currency,column==='unitPrice'))}</td>`).join('')}</tr>`).join('')}</tbody></table><dl class="totals"><dt>Subtotal</dt><dd>${escapeHtml(money(record.subtotal,record.currency))}</dd><dt>Discount</dt><dd>${escapeHtml(money(record.discountTotal,record.currency))}</dd><dt>Tax</dt><dd>${escapeHtml(money(record.taxTotal,record.currency))}</dd><dt class="grand">Total</dt><dd class="grand">${escapeHtml(money(record.total,record.currency))}</dd></dl>${record.notes?`<section>${renderBlockNote(record.notes)}</section>`:''}`;
 } else if(document.kind==='credit-note'){
  const record=creditNote.parse(data);subtitle=`Credit note ${record.number}`;
  content=`<div class="parties"><section><h2>Credit to</h2><strong>${escapeHtml(record.patient.name)}</strong><p>${escapeHtml(record.patient.address??'')}</p></section><section><h2>Credit note details</h2><p>Number: ${escapeHtml(record.number)}</p><p>Invoice: ${escapeHtml(record.invoiceNumber)}</p><p>Issued: ${escapeHtml(record.issuedAt)}</p></section></div><section><h2>Reason</h2><p>${escapeHtml(record.reason)}</p></section><dl class="totals"><dt class="grand">Credit total</dt><dd class="grand">${escapeHtml(money(record.total,record.currency))}</dd></dl>`;
 } else {
  const record=payslip.parse(data);subtitle=`Payslip · ${record.period}`;
  content=`<div class="parties"><section><h2>Employee</h2><strong>${escapeHtml(record.employeeName)}</strong><p>${escapeHtml(record.jobTitle??'')}</p></section><section><h2>Pay period</h2><p>${escapeHtml(record.period)}</p></section></div><table><thead><tr><th>Earnings</th><th class="number">Amount</th></tr></thead><tbody>${record.earnings.map(line=>`<tr><td>${escapeHtml(line.label)}</td><td class="number">${escapeHtml(money(line.amount,record.currency))}</td></tr>`).join('')}<tr class="grand"><td>Gross pay</td><td class="number">${escapeHtml(money(record.gross,record.currency))}</td></tr></tbody></table><table><thead><tr><th>Deductions</th><th class="number">Amount</th></tr></thead><tbody>${record.deductions.map(line=>`<tr><td>${escapeHtml(line.label)}</td><td class="number">${escapeHtml(money(line.amount,record.currency))}</td></tr>`).join('')}<tr><td>Total deductions</td><td class="number">${escapeHtml(money(record.totalDeductions,record.currency))}</td></tr></tbody></table><dl class="totals"><dt class="grand">Net pay</dt><dd class="grand">${escapeHtml(money(record.net,record.currency))}</dd></dl>`;
 }
 const identifiers=company.businessIds&&typeof company.businessIds==='object'?Object.entries(company.businessIds).filter(([,value])=>typeof value==='string').map(([key,value])=>`${escapeHtml(key)}: ${escapeHtml(value)}`).join(' · '):'';
 return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; script-src 'none'; connect-src 'none'"><title>${escapeHtml(subtitle)}</title><style>@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font-family:${style.font==='serif'?'Georgia,serif':style.font==='mono'?'monospace':'Arial,sans-serif'};font-size:11px;line-height:1.55;color:#1d2931}header{border-bottom:3px solid ${style.accent};padding-bottom:18px;margin-bottom:24px}h1{font-size:23px;margin:0;color:${style.accent}}h2{text-transform:uppercase;font-size:10px;letter-spacing:1px;color:#657478}p{white-space:pre-line;margin:3px 0}.subtitle{font-size:17px;margin-top:12px}.parties{display:flex;justify-content:space-between;gap:40px;margin:20px 0}table{width:100%;border-collapse:collapse;margin:20px 0}thead{display:table-header-group}tr{break-inside:avoid}th{background:#f3f6f5;text-align:left}th,td{padding:10px;border-bottom:1px solid #dde5e2}.number{text-align:right;white-space:nowrap}.totals{margin-left:auto;width:300px;display:grid;grid-template-columns:1fr 1fr}.totals dt,.totals dd{padding:7px;margin:0}.totals dd{text-align:right}.grand{font-weight:bold;border-top:2px solid ${style.accent}}footer{margin-top:32px;border-top:1px solid #dde5e2;padding-top:12px;color:#657478;white-space:pre-line}a{color:inherit;text-decoration:none}pre{white-space:pre-wrap}</style></head><body><header>${style.showLogo&&style.logoDataUri?`<img src="${style.logoDataUri}" alt="Clinic logo" style="max-width:160px;max-height:80px;margin-bottom:10px">`:''}<h1>${escapeHtml(company.legalName??company.clinicName??'Clinic')}</h1><p>${escapeHtml(company.address??'')}</p><p>${escapeHtml([company.email,company.phone].filter(Boolean).join(' · '))}</p><p>${identifiers}</p><p class="subtitle">${escapeHtml(subtitle)}</p></header>${content}${company.bankDetails?`<section><h2>Payment details</h2><p>${escapeHtml(company.bankDetails)}</p></section>`:''}${style.terms?`<section><h2>Terms</h2><p>${escapeHtml(style.terms)}</p></section>`:''}<footer>${escapeHtml(style.footer)}</footer></body></html>`;
}
export async function renderFinancialPdfLocal(document:FinancialDocument,template:FinancialTemplate={}):Promise<Buffer> {
 const html=renderFinancialHtml(document,template);assert(Buffer.byteLength(html)<=1024*1024,'DOCUMENT_SIZE','Document exceeds render budget');
 const browser=await chromium.launch({headless:true,chromiumSandbox:process.env.PDF_CHROMIUM_SANDBOX!=='false',args:['--disable-dev-shm-usage','--disable-background-networking']});
 try {const context=await browser.newContext({javaScriptEnabled:false,serviceWorkers:'block'});await context.route('**/*',route=>route.abort());const page=await context.newPage();await page.setContent(html,{waitUntil:'domcontentloaded',timeout:15000});return await page.pdf({format:'A4',printBackground:true,preferCSSPageSize:true});}
 finally{await browser.close();}
}
export async function renderFinancialPdf(document:FinancialDocument,template:FinancialTemplate={}):Promise<Buffer> {
 const socketPath=process.env.PDF_RENDERER_SOCKET;
 assert(socketPath||process.env.NODE_ENV!=='production','PDF_ISOLATION','Production PDF rendering requires the isolated renderer socket',503);
 if(!socketPath)return renderFinancialPdfLocal(document,template);
 const payload=JSON.stringify({document,template});assert(Buffer.byteLength(payload)<=1024*1024,'DOCUMENT_SIZE','Document exceeds render budget');
 return new Promise<Buffer>((accept,reject)=>{const req=request({socketPath,path:'/render',method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)},timeout:35000},res=>{let size=0;const chunks:Buffer[]=[];res.on('data',(chunk:Buffer)=>{size+=chunk.length;if(size>10*1024*1024){req.destroy(new Error('PDF exceeds output budget'));return;}chunks.push(chunk);});res.on('end',()=>{if(res.statusCode!==200){reject(new Error('Isolated PDF rendering failed'));return;}accept(Buffer.concat(chunks));});res.on('error',reject);});req.on('error',reject);req.on('timeout',()=>req.destroy(new Error('PDF renderer timed out')));req.end(payload);});
}
