/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import {useEffect,useRef,useState} from 'react';
import {api,errorMessage} from '@/lib/api';
import {Alert,Icon} from './ui';
export function AiDraft({task,input,onAccept}:{task:string;input:Record<string,unknown>;onAccept:(text:string)=>void}){
 const[open,setOpen]=useState(false);const[text,setText]=useState('');const[draft,setDraft]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[provenance,setProvenance]=useState('');const[recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),mounted=useRef(true);
 // Leaving the page releases the microphone immediately and discards the unfinished dictation.
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;const media=recorder.current;recorder.current=null;if(media&&media.state!=='inactive')media.stop();stream.current?.getTracks().forEach(track=>track.stop());stream.current=null}},[]);
 const prepare=async()=>{setBusy(true);setError('');try{const result=await api<{text:string;provenance?:{model?:string;promptVersion?:string}}>('/ai/draft',{method:'POST',body:{task:task==='consultation'?'note':'reply',text,...(input.patientId?{patientId:input.patientId}:{})}});setDraft(result.text);setProvenance([result.provenance?.model,result.provenance?.promptVersion].filter(Boolean).join(' · '))}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};
 const record=async()=>{if(recording){recorder.current?.stop();setRecording(false);return}try{const audio=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){audio.getTracks().forEach(x=>x.stop());return}stream.current=audio;const media=new MediaRecorder(audio);const chunks:BlobPart[]=[];recorder.current=media;media.ondataavailable=e=>chunks.push(e.data);media.onstop=async()=>{audio.getTracks().forEach(x=>x.stop());if(stream.current===audio)stream.current=null;if(!mounted.current)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',new Blob(chunks,{type:media.mimeType}),'dictation.webm');const result=await api<{text:string}>('/ai/transcribe',{method:'POST',body:form});setText(result.text)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};media.start();setRecording(true)}catch(e){setError(errorMessage(e))}};
 return <section className="ai-draft"><button type="button" className="text-button" onClick={()=>setOpen(!open)}><Icon name="spark" size={16}/>{open?'Hide writing assistance':'Writing assistance'}</button>{open&&<div><p>Provide approved source notes or dictate your own observations. Review the draft before adding it to this document.</p>{error&&<Alert>{error}</Alert>}<label className="form-field">Source notes<textarea rows={5} value={text} onChange={e=>setText(e.target.value)}/></label><div className="button-row">{task==='consultation'&&<button type="button" className="button secondary" onClick={record} disabled={busy}>{recording?'Stop dictation':'Dictate notes'}</button>}<button className="button secondary" type="button" disabled={busy||!text.trim()||recording} onClick={prepare}>{busy?'Preparing draft…':'Prepare draft'}</button></div>{draft&&<><label className="form-field">Draft for your review<textarea rows={7} value={draft} onChange={e=>setDraft(e.target.value)}/></label><small>{provenance}</small><div className="button-row"><button className="button primary" type="button" onClick={()=>{onAccept(draft);setDraft('')}}>Add reviewed draft</button><button className="button secondary" type="button" onClick={()=>setDraft('')}>Discard draft</button></div></>}</div>}</section>
}
