/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import {api,errorMessage,setCsrf} from '@/lib/api';
import type {Session} from '@/lib/types';
import {safeNextPath} from '@/lib/records';
import {useSession} from './session';
import {Alert,Icon,Mark} from './ui';
export function AuthForm({mode}:{mode:'login'|'register'|'setup'}){const router=useRouter();const{reload}=useSession();const[values,setValues]=useState<Record<string,string>>(mode==='setup'?{timezone:'Asia/Kolkata',currency:'INR'}:{});const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[configured,setConfigured]=useState<boolean|null>(null);useEffect(()=>{api<{configured:boolean}>('/auth/status').then(v=>setConfigured(v.configured)).catch(()=>{})},[]);const update=(key:string,v:string)=>setValues({...values,[key]:v});return <div className="auth-layout"><div className="auth-story"><Link className="brand" href="/"><Mark/><span>ClinicsCMS<span className="brand-sub">Care, in order.</span></span></Link><div className="auth-story-copy"><span className="auth-cross"><Icon name="services" size={48}/></span><h1>Less between you<br/>and better care.</h1><p>One place for your clinic’s people, appointments, and next steps.</p></div><span className="auth-story-footer">Built around the rhythm of your clinic.</span></div><main className="auth-panel"><Link className="back-link" href="/">Back to clinic website</Link><div className="auth-box"><h1>{mode==='login'?'Welcome back':mode==='register'?'Your care, connected':'Set up your clinic'}</h1><p>{mode==='login'?'Sign in to your secure workspace.':mode==='register'?'Create your patient account. Your clinic will verify and connect existing records.':'Create the installation owner account using the setup token from your server administrator.'}</p>{configured===false&&mode==='login'&&<Alert kind="info">This installation needs an owner. <Link href="/setup">Set up the clinic</Link></Alert>}{configured&&mode==='setup'?<Alert kind="info">This installation has already been configured. <Link href="/login">Sign in</Link></Alert>:(notice?<Alert kind="info">{notice}</Alert>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data=await api<Session>(`/auth/${mode==='setup'?'bootstrap':mode}`,{method:'POST',body:Object.fromEntries(Object.entries(values).filter(([,v])=>v!==''))});setCsrf(data.csrfToken);const signedIn=await reload();
// Registration answers the same way for an address that already has an account, without signing in; that person receives an email instead.
if(!signedIn&&mode==='register'){setValues({});setNotice('Check your email to continue.');return}router.replace(safeNextPath(new URLSearchParams(window.location.search).get('next'))||(data.user.roles.every(x=>x==='patient')?'/portal':'/workspace'))}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}}>{error&&<Alert>{error}</Alert>}{mode!=='login'&&<label className="form-field">Your full name<input autoComplete="name" required value={values.name||''} onChange={e=>update('name',e.target.value)}/></label>}<label className="form-field">Email address<input type="email" autoComplete="email" required value={values.email||''} onChange={e=>update('email',e.target.value)}/></label><label className="form-field">Password<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?undefined:12} required value={values.password||''} onChange={e=>update('password',e.target.value)}/>{mode!=='login'&&<small>Use at least 12 characters.</small>}</label>{mode==='login'&&<label className="form-field">Authenticator or recovery code <small>For accounts with two-step verification.</small><input autoComplete="one-time-code" value={values.totp||''} onChange={e=>update('totp',e.target.value)}/></label>}{mode==='setup'&&<><label className="form-field">Installation token<input type="password" required autoComplete="off" value={values.token||''} onChange={e=>update('token',e.target.value)}/></label><label className="form-field">Clinic name<input required value={values.clinicName||''} onChange={e=>update('clinicName',e.target.value)}/></label><div className="form-grid"><label className="form-field">Timezone<input required value={values.timezone} onChange={e=>update('timezone',e.target.value)}/></label><label className="form-field">Currency<input required maxLength={3} value={values.currency} onChange={e=>update('currency',e.target.value.toUpperCase())}/></label></div></>}<button className="button primary auth-submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create patient account':'Create clinic'}</button></form>)}{mode==='login'&&<Link className="text-button" href="/reset-password">Forgot password?</Link>}<div className="auth-switch">{mode==='login'?<>New patient? <Link href="/register">Create an account</Link></>:<>Already have an account? <Link href="/login">Sign in</Link></>}</div><p className="auth-security"><Icon name="security" size={15}/>Your session stays private on this device.</p></div></main></div>}
export function MfaEnrollment(){const{reload,logout}=useSession();const[setup,setSetup]=useState<{secret:string;uri:string}|null>(null);const[codes,setCodes]=useState<string[]>([]);const[code,setCode]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);return <div className="mfa-gate"><div className="panel"><Icon name="security" size={32}/><h1>Secure your staff account</h1><p>Add this account to your authenticator app, then enter its six-digit code. Staff access requires two-step verification.</p>{error&&<Alert>{error}</Alert>}{codes.length?<><Alert kind="success">Two-step verification is enabled.</Alert><h2>Save your recovery codes</h2><p>Store these in a password manager. Each can be used once if your authenticator is unavailable.</p><div className="recovery-codes">{codes.map(c=><code key={c}>{c}</code>)}</div><button className="button primary" onClick={()=>reload()}>I saved my recovery codes</button></>:setup?<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await api<{recoveryCodes:string[]}>('/auth/mfa/confirm',{method:'POST',body:{code}});setCodes(result.recoveryCodes)}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}}><label className="form-field">Authenticator setup key<code className="secret-key">{setup.secret}</code></label><a href={setup.uri} className="text-button">Open authenticator app</a><label className="form-field">Verification code<input required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label><button className="button primary" disabled={busy}>{busy?'Verifying…':'Enable verification'}</button></form>:<button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{setSetup(await api('/auth/mfa/begin',{method:'POST'}))}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}}>Set up authenticator</button>}<button className="text-button" onClick={()=>logout()}>Sign out</button></div></div>}
