/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import {useEffect,useId,useState,useRef} from 'react';
import dynamic from 'next/dynamic';
import {api,apiPage,displayName,errorMessage} from '@/lib/api';
import {listPath,cleanValues} from '@/lib/records';
import type {Field,RecordData} from '@/lib/types';
import {Icon} from './ui';
import {useClinicTime} from './session';
import {wallTime,wallTimeCandidates} from '@/lib/datetime';
const RichEditor=dynamic(()=>import('./rich-editor'),{ssr:false,loading:()=> <div className="editor-loading">Preparing writing tools…</div>});
export {cleanValues,updateValues} from '@/lib/records';
export function FieldInput({field,value,onChange,patientId,branchId,publicContent=false}:{field:Field;value:unknown;onChange:(v:unknown)=>void;patientId?:string;branchId?:string;publicContent?:boolean}){
 // Staff directory references are a short list; record references are searched on the server (see ReferencePicker).
 const directory=Boolean(field.reference?.startsWith('@'));const[choices,setChoices]=useState<RecordData[]>([]);const[referenceError,setReferenceError]=useState('');const[referenceLoading,setReferenceLoading]=useState(directory);
 useEffect(()=>{if(!field.reference||!directory){setReferenceLoading(false);return}let alive=true;setChoices([]);setReferenceError('');setReferenceLoading(true);api<RecordData[]>('/directory').then(v=>field.reference==='@doctors'?v.filter(x=>Array.isArray(x.roles)&&x.roles.includes('doctor')):v).then(v=>{if(alive)setChoices(v)}).catch(e=>{if(alive)setReferenceError(errorMessage(e))}).finally(()=>{if(alive)setReferenceLoading(false)});return()=>{alive=false}},[field.reference,directory]);
 // Unique per form instance: nested rows and sub-forms reuse field keys.
 const id=`${useId()}field-${field.key}`;
 if(field.type==='json'&&['allergies','medicines','diagnosis','branchIds'].includes(field.key))return <StringList field={field} value={value} onChange={onChange}/>;
 if(field.type==='json'&&['roles','categories','schemaTypes','columns','participantIds','employeeIds'].includes(field.key))return <MultiChoice field={field} value={value} onChange={onChange}/>;
 if(field.type==='json'&&['medications','citations','adjustments','translations','navigation'].includes(field.key))return <StructuredRows field={field} value={value} onChange={onChange}/>;
 if(field.type==='json'&&field.key==='salary')return <SalaryInput value={value} onChange={onChange}/>;
 if(field.type==='json'&&['observations','emergencyContact','features'].includes(field.key))return <ObjectInput field={field} value={value} onChange={onChange}/>;
 if(field.type==='blocks')return <div className="form-field full"><label>{field.label}</label><RichEditor value={Array.isArray(value)?value:[]} onChange={onChange} patientId={patientId} publicContent={publicContent}/></div>;
 if(field.type==='datetime-local')return <DateTimeInput field={field} value={value} onChange={onChange} branchId={branchId}/>;
 if(field.type==='lines')return <InvoiceLines value={value} onChange={onChange}/>;
 if(field.key==='seo')return <SeoFields value={(value||{}) as Record<string,unknown>} onChange={onChange}/>;
 if(field.key==='design')return <TemplateFields value={(value||{}) as Record<string,unknown>} onChange={onChange}/>;
 if(field.type==='boolean')return <label className={`form-field checkbox-field ${field.full?'full':''}`}><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/><span>{field.label}{field.hint&&<small>{field.hint}</small>}</span></label>;
 return <div className={`form-field ${field.full||field.type==='textarea'||field.type==='json'?'full':''}`}><label htmlFor={id}>{field.label}{field.required&&<span aria-hidden="true" className="required"> *</span>}</label>{field.type==='json'?<JsonField id={id} value={value} onChange={onChange} required={field.required}/>:field.type==='textarea'?<textarea id={id} value={String(value??'')} required={field.required} rows={3} onChange={e=>onChange(e.target.value)}/>:field.reference&&!directory?<ReferencePicker id={id} field={field} value={value} onChange={onChange}/>:field.type==='select'?<select id={id} value={String(value??'')} aria-busy={referenceLoading} required={field.required} onChange={e=>onChange(field.key==='weekday'?Number(e.target.value):e.target.value)}><option value="">{referenceLoading?'Loading options…':`Choose ${field.label.toLowerCase()}`}</option>{field.reference&&value&&!choices.some(choice=>choice.id===String(value))?<option value={String(value)}>{referenceLoading?'Current selection · loading details…':'Current selection · not in this list'}</option>:null}{field.reference?choices.map(x=><option key={x.id} value={x.id}>{displayName(x)}</option>):field.options?.map(x=><option key={x} value={x}>{x.replaceAll('-',' ')}</option>)}</select>:<input id={id} type={field.type||'text'} step={field.type==='number'?'any':undefined} required={field.required} min={field.min} max={field.max} autoComplete={field.type==='password'?'new-password':'off'} value={String(value??'')} onChange={e=>onChange(field.type==='number'?e.target.value===''?'':Number(e.target.value):e.target.value)}/>} {field.key==='socialImage'&&<PublicImageUpload onUploaded={onChange}/>} {field.hint&&<small>{field.hint}</small>}{referenceLoading&&<small role="status">Loading {field.label.toLowerCase()} options… Your current selection is retained.</small>}{referenceError&&<small className="error-text">Unable to load options: {referenceError}</small>}</div>
}
function JsonField({id,value,onChange,required}:{id:string;value:unknown;onChange:(v:unknown)=>void;required?:boolean}){const [text,setText]=useState(JSON.stringify(value??[],null,2));const[error,setError]=useState('');return <><textarea id={id} className="code-input" rows={5} value={text} required={required} onChange={e=>{setText(e.target.value);try{const data=JSON.parse(e.target.value);onChange(data);setError('');e.target.setCustomValidity('')}catch{setError('Enter valid JSON before saving.');e.target.setCustomValidity('Enter valid JSON before saving.')}}}/>{error&&<small className="error-text">{error}</small>}</>}
export function FormFields({fields,values,onChange,publicContent=false,branchId}:{fields:Field[];values:Record<string,unknown>;onChange:(v:Record<string,unknown>)=>void;publicContent?:boolean;branchId?:string}){return <div className="form-grid">{fields.map(f=><FieldInput key={f.key} field={f} value={values[f.key]} onChange={v=>onChange({...values,[f.key]:v})} patientId={String(values.patientId||'')} branchId={values.branchId?String(values.branchId):branchId} publicContent={publicContent}/>)}</div>}
export function initialValues(fields:Field[],record?:RecordData,branchId?:string){return Object.fromEntries(fields.map(f=>[f.key,record?.[f.key]??(f.key==='branchId'?branchId||'main':f.default??(f.type==='boolean'?false:''))]))}
function InvoiceLines({value,onChange}:{value:unknown;onChange:(v:unknown)=>void}){const rows=(Array.isArray(value)&&value.length?value:[{description:'',quantity:'1',unitPrice:'0',taxRate:'0',discount:'0'}]) as Record<string,string>[];const change=(i:number,key:string,v:string)=>onChange(rows.map((x,j)=>i===j?{...x,[key]:v}:x));return <div className="form-field full"><label>Invoice items</label><div className="table-scroll"><table className="line-table"><thead><tr><th>Description</th><th>Quantity</th><th>Unit price</th><th>Tax %</th><th>Discount</th><th><span className="sr-only">Remove</span></th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{['description','quantity','unitPrice','taxRate','discount'].map(k=><td key={k}><input aria-label={`${k} item ${i+1}`} required={k==='description'||k==='quantity'||k==='unitPrice'} inputMode={k==='description'?'text':'decimal'} value={r[k]||''} onChange={e=>change(i,k,e.target.value)}/></td>)}<td><button className="icon-button" type="button" disabled={rows.length===1} onClick={()=>onChange(rows.filter((_,j)=>i!==j))} aria-label={`Remove item ${i+1}`}><Icon name="close" size={16}/></button></td></tr>)}</tbody></table></div><button type="button" className="text-button" onClick={()=>onChange([...rows,{description:'',quantity:'1',unitPrice:'0',taxRate:'0',discount:'0'}])}><Icon name="plus" size={15}/> Add item</button><small>Final totals are calculated by the server using exact decimal arithmetic.</small></div>}
export function SeoFields({value,onChange}:{value:Record<string,unknown>;onChange:(v:unknown)=>void}){const update=(k:string,v:unknown)=>onChange({...value,[k]:v});return <fieldset className="full seo-panel"><legend>Search &amp; social</legend><div className="form-grid">{[{key:'title',label:'Search title',hint:'Aim for a clear title of about 50–60 characters.'},{key:'description',label:'Search description',type:'textarea'},{key:'canonical',label:'Canonical URL',hint:'Absolute public URL; leave blank to use this page.'},{key:'socialTitle',label:'Social title'},{key:'socialDescription',label:'Social description',type:'textarea'},{key:'socialImage',label:'Social image URL',hint:'1200 × 630 works well for link previews.'},{key:'socialImageAlt',label:'Social image alt text'},{key:'indexable',label:'Allow search indexing',type:'boolean'},{key:'schemaTypes',label:'Schema types',type:'json',hint:'For example ["MedicalWebPage", "Article"].'},{key:'translations',label:'Translation links',type:'json',hint:'[{"locale":"en-IN","slug":"about"}]'},{key:'schema',label:'Additional structured data',type:'json',hint:'JSON-LD data must describe content visible on this page.'}].map(f=><FieldInput key={f.key} field={f as Field} value={value[f.key]} onChange={v=>update(f.key,v)}/>)}</div><div className="search-preview"><small>Search preview</small><h3>{String(value.title||'Your page title')}</h3><p>{String(value.description||'Add a useful description so people understand what this page offers.')}</p></div><div className="social-preview"><div className="social-preview-art"><Icon name="services" size={36}/></div><div><small>Social preview</small><strong>{String(value.socialTitle||value.title||'Your page title')}</strong><p>{String(value.socialDescription||value.description||'The description people see when this page is shared.')}</p></div></div></fieldset>}
function TemplateFields({value,onChange}:{value:Record<string,unknown>;onChange:(v:unknown)=>void}){return <fieldset className="full template-designer"><legend>Document design</legend><div className="designer-split"><div><label className="form-field">Accent colour<input type="color" value={String(value.accent||'#25645d')} onChange={e=>onChange({...value,accent:e.target.value})}/></label><FieldInput field={{key:'font',label:'Typeface',type:'select',options:['system','serif','mono']}} value={value.font||'system'} onChange={v=>onChange({...value,font:v})}/><FieldInput field={{key:'showLogo',label:'Show clinic logo',type:'boolean'}} value={value.showLogo} onChange={v=>onChange({...value,showLogo:v})}/><FieldInput field={{key:'footer',label:'Footer',type:'textarea'}} value={value.footer} onChange={v=>onChange({...value,footer:v})}/><FieldInput field={{key:'terms',label:'Payment terms',type:'textarea'}} value={value.terms} onChange={v=>onChange({...value,terms:v})}/><FieldInput field={{key:'columns',label:'Table columns',type:'json'}} value={value.columns} onChange={v=>onChange({...value,columns:v})}/></div><div className="paper-preview" style={{borderTopColor:String(value.accent||'#25645d'),fontFamily:value.font==='serif'?'Georgia, serif':value.font==='mono'?'monospace':'inherit'}}><small>Template preview · sample values</small><div className="paper-head"><div><strong>Clinic business name</strong><p>Address and registration details</p></div><h3 style={{color:String(value.accent||'#25645d')}}>Invoice</h3></div><p>Billed to<br/><strong>Sample patient</strong></p><table><thead><tr><th>Service</th><th>Total</th></tr></thead><tbody><tr><td>Consultation</td><td>1,000.00</td></tr></tbody></table><div className="paper-total">Total 1,000.00</div><p>{String(value.terms||'Payment terms')}</p><footer>{String(value.footer||'Document footer')}</footer></div></div></fieldset>}

function PublicImageUpload({onUploaded}:{onUploaded:(v:string)=>void}){const[message,setMessage]=useState('');const[alt,setAlt]=useState('');return <div><input aria-label="Public image accessibility description" placeholder="Describe the image before uploading" value={alt} onChange={e=>setAlt(e.target.value)}/><label className="text-button">Upload a public image<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setMessage('Uploading…');try{if(!alt.trim())throw new Error('Enter an image description first.');const body=new FormData();body.append('file',file);body.append('alt',alt.trim());const result=await api<{id:string;url?:string}>('/public-assets',{method:'POST',body});onUploaded(result.url||`/api/v1/public/assets/${encodeURIComponent(result.id)}`);setMessage('Image uploaded.')}catch(err){setMessage(errorMessage(err))}finally{e.target.value=''}}}/></label>{message&&<small role="status">{message}</small>}</div>}

function DateTimeInput({field,value,onChange,branchId}:{field:Field;value:unknown;onChange:(v:unknown)=>void;branchId?:string}){const {timezone}=useClinicTime(branchId);const id=`${useId()}field-${field.key}`;const[wall,setWall]=useState(value?wallTime(String(value),timezone):'');const[choices,setChoices]=useState<string[]>([]);const[error,setError]=useState('');const ref=useRef<HTMLInputElement>(null);useEffect(()=>{if(value)setWall(wallTime(String(value),timezone))},[timezone]);return <div className="form-field"><label htmlFor={id}>{field.label}{field.required?' *':''}</label><input ref={ref} id={id} type="datetime-local" required={field.required} value={wall} onChange={e=>{const text=e.target.value;setWall(text);const candidates=wallTimeCandidates(text,timezone);setChoices(candidates);const message=!text?'':!candidates.length?'This local time does not exist because the clocks change. Choose another time.':candidates.length>1?'This time occurs twice. Select its UTC offset below.':'';setError(message);e.target.setCustomValidity(message);onChange(candidates.length===1?candidates[0]:'')}}/><small>{branchId?'Branch':'Clinic'} time · {timezone}</small>{choices.length>1&&<select aria-label={`${field.label} UTC offset`} required onChange={e=>{onChange(e.target.value);ref.current?.setCustomValidity('');setError('')}} defaultValue=""><option value="">Choose clock occurrence</option>{choices.map(c=><option value={c} key={c}>{new Intl.DateTimeFormat('en',{timeZone:timezone,hour:'2-digit',minute:'2-digit',timeZoneName:'longOffset'}).format(new Date(c))}</option>)}</select>}{error&&<small className="error-text">{error}</small>}</div>}

function StringList({field,value,onChange}:{field:Field;value:unknown;onChange:(v:unknown)=>void}){const[text,setText]=useState(Array.isArray(value)?value.join('\n'):'');return <label className="form-field full">{field.label}<textarea rows={3} value={text} onChange={e=>{setText(e.target.value);onChange(e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}}/><small>One item per line.</small></label>}
const choiceOptions:Record<string,string[]>={roles:['admin','manager','doctor','nurse','receptionist','accountant','hr','editor','employee'],categories:['security','operations','appointments','messages','clinical','finance','hr','content'],schemaTypes:['WebSite','WebPage','MedicalClinic','Person','IndividualPhysician','Service','Offer','MedicalWebPage','Article','BlogPosting','FAQPage','AboutPage','ContactPage','CollectionPage','ItemList','WebApplication','Organization','SoftwareApplication','BreadcrumbList'],columns:['description','quantity','unitPrice','discount','tax','total']};
function MultiChoice({field,value,onChange}:{field:Field;value:unknown;onChange:(v:unknown)=>void}){const[options,setOptions]=useState<{id:string;label:string}[]>((choiceOptions[field.key]||[]).map(id=>({id,label:id})));const[error,setError]=useState('');useEffect(()=>{if(field.key==='participantIds'||field.key==='employeeIds')api<RecordData[]>(field.key==='participantIds'?'/directory':'/records/employees?limit=500').then(rows=>setOptions(rows.map(x=>({id:x.id,label:displayName(x)})))).catch(e=>setError(errorMessage(e)))},[field.key]);const selected=Array.isArray(value)?value as string[]:[];return <fieldset className="choice-field full"><legend>{field.label}{field.required?' *':''}</legend>{error&&<small className="error-text">{error}</small>}<div className="choice-grid">{options.map(option=><label className="checkbox-field" key={option.id}><input type="checkbox" checked={selected.includes(option.id)} onChange={e=>onChange(e.target.checked?[...selected,option.id]:selected.filter(v=>v!==option.id))}/><span>{option.label.replace(/([a-z])([A-Z])/g,'$1 $2')}</span></label>)}</div>{!options.length&&!error&&<small>No eligible people are available.</small>}</fieldset>}
const rowDefinitions:Record<string,Field[]>={medications:[{key:'name',label:'Medicine',required:true},{key:'dose',label:'Dose',required:true},{key:'route',label:'Route',required:true},{key:'frequency',label:'Frequency',required:true},{key:'duration',label:'Duration',required:true},{key:'instructions',label:'Instructions'}],citations:[{key:'title',label:'Source title',required:true},{key:'url',label:'Source URL',required:true}],adjustments:[{key:'employeeId',label:'Employee',type:'select',reference:'employees',required:true},{key:'label',label:'Description',required:true},{key:'amount',label:'Amount',required:true},{key:'kind',label:'Adjustment type',type:'select',options:['earning','deduction'],required:true}],translations:[{key:'locale',label:'Language / locale',required:true},{key:'slug',label:'Translated page slug',required:true}],navigation:[{key:'label',label:'Link label',required:true},{key:'href',label:'Page path',required:true}],salaryItems:[{key:'label',label:'Description',required:true},{key:'amount',label:'Amount',required:true}]};
function StructuredRows({field,value,onChange}:{field:Field;value:unknown;onChange:(v:unknown)=>void}){const rows=Array.isArray(value)?value as Record<string,unknown>[]:[];const fields=rowDefinitions[field.key]||rowDefinitions.salaryItems;return <fieldset className="structured-rows full"><legend>{field.label}</legend>{rows.map((row,i)=><div className="structured-row" key={i}><div className="form-grid">{fields.map(f=><FieldInput key={f.key} field={{...f,key:`${f.key}-row-${i}`}} value={row[f.key]} onChange={v=>onChange(rows.map((r,j)=>i===j?{...r,[f.key]:v}:r))}/>)}</div><button type="button" className="text-button" onClick={()=>onChange(rows.filter((_,j)=>j!==i))}>Remove {field.key==='medications'?'medicine':'item'}</button></div>)}<button type="button" className="button secondary" onClick={()=>onChange([...rows,Object.fromEntries(fields.filter(f=>f.required).map(f=>[f.key,f.options?.[0]||'']))])}><Icon name="plus" size={15}/>Add {field.key==='medications'?'medicine':field.key==='citations'?'source':'item'}</button></fieldset>}
function SalaryInput({value,onChange}:{value:unknown;onChange:(v:unknown)=>void}){const salary=(value||{currency:'USD',base:'0',earnings:[],deductions:[]}) as Record<string,unknown>;return <fieldset className="structured-rows full"><legend>Salary structure</legend><div className="form-grid"><FieldInput field={{key:'currency',label:'Currency',required:true}} value={salary.currency} onChange={v=>onChange({...salary,currency:v})}/><FieldInput field={{key:'base',label:'Base salary',required:true}} value={salary.base} onChange={v=>onChange({...salary,base:v})}/><StructuredRows field={{key:'earnings',label:'Additional earnings'}} value={salary.earnings} onChange={v=>onChange({...salary,earnings:v})}/><StructuredRows field={{key:'deductions',label:'Deductions'}} value={salary.deductions} onChange={v=>onChange({...salary,deductions:v})}/></div></fieldset>}
function ObjectInput({field,value,onChange}:{field:Field;value:unknown;onChange:(v:unknown)=>void}){const object=(value&&typeof value==='object'?value:{}) as Record<string,unknown>;const fields:Field[]=field.key==='observations'?[{key:'bloodPressure',label:'Blood pressure (mmHg)'},{key:'pulse',label:'Pulse (bpm)',type:'number',min:0,max:500},{key:'temperature',label:'Temperature (°C)',type:'number',min:20,max:50},{key:'weight',label:'Weight (kg)',type:'number',min:0,max:1000},{key:'height',label:'Height (cm)',type:'number',min:0,max:300}]:field.key==='emergencyContact'?[{key:'name',label:'Contact name'},{key:'phone',label:'Contact phone',type:'tel'},{key:'relationship',label:'Relationship'}]:['ai','publicTools','onlinePayments','payroll'].map(key=>({key,label:key.replace(/([A-Z])/g,' $1'),type:'boolean'}));return <fieldset className="structured-rows full"><legend>{field.label}</legend><FormFields fields={fields} values={object} onChange={v=>onChange(cleanValues(v))}/></fieldset>}

/** Accessible search combobox for record references: debounced server search (20 results), and the current value's label loaded by id. */
function referenceLabel(row:RecordData,date:(value:string,options?:Intl.DateTimeFormatOptions)=>string){const name=displayName(row);if(name&&name!==row.id)return name;const when=row.startsAt||row.createdAt;const kind=String(row.kind||'Record').replaceAll('-',' ');return when?`${kind[0].toUpperCase()}${kind.slice(1)} · ${date(String(when),{dateStyle:'medium',timeStyle:'short'})}`:name}
/** Up to 20 matches; follows a server cursor a few times because a page can be short while more records follow. */
async function searchReferences(collection:string,text:string):Promise<RecordData[]>{const rows:RecordData[]=[];let after='';for(let request=0;request<4&&rows.length<20;request++){const page=await apiPage(listPath(collection,{q:text,limit:20-rows.length,order:'desc',after}));rows.push(...page.data);const next=page.next||'';if(!next||next===after)break;after=next}return rows}
function ReferencePicker({id,field,value,onChange}:{id:string;field:Field;value:unknown;onChange:(v:unknown)=>void}){
 const time=useClinicTime(),collection=field.reference!,selected=value===undefined||value===null?'':String(value),listId=`${id}-options`,input=useRef<HTMLInputElement>(null),labels=useRef(new Map<string,string>());
 const[label,setLabel]=useState(''),[labelState,setLabelState]=useState<'ready'|'loading'|'missing'>('ready'),[text,setText]=useState(''),[editing,setEditing]=useState(false),[open,setOpen]=useState(false),[options,setOptions]=useState<RecordData[]>([]),[active,setActive]=useState(-1),[searching,setSearching]=useState(false),[error,setError]=useState('');
 const describe=(row:RecordData)=>{const text=referenceLabel(row,time.date);labels.current.set(row.id,text);return text};
 useEffect(()=>{if(!selected){setLabel('');setLabelState('ready');return}const known=labels.current.get(selected);if(known!==undefined){setLabel(known);setLabelState('ready');return}let alive=true;setLabelState('loading');api<RecordData>(`/records/${encodeURIComponent(collection)}/${encodeURIComponent(selected)}`).then(row=>{if(alive){setLabel(describe(row));setLabelState('ready')}}).catch(()=>{if(alive)setLabelState('missing')});return()=>{alive=false}
 // describe only reads the clinic date format.
 },[selected,collection]);
 useEffect(()=>{if(!open)return;let alive=true;setSearching(true);setError('');const timer=setTimeout(()=>{searchReferences(collection,text).then(rows=>{if(alive){setOptions(rows);setActive(rows.length?0:-1)}}).catch(e=>{if(alive){setOptions([]);setError(errorMessage(e))}}).finally(()=>{if(alive)setSearching(false)})},text?250:0);return()=>{alive=false;clearTimeout(timer)}},[open,text,collection]);
 useEffect(()=>{input.current?.setCustomValidity(field.required&&!selected?`Choose ${field.label.toLowerCase()} from the list.`:'')},[field.required,field.label,selected]);
 const close=()=>{setOpen(false);setEditing(false);setText('');setActive(-1)};
 const choose=(row:RecordData)=>{setLabel(describe(row));setLabelState('ready');close();onChange(row.id)};
 const placeholder=labelState==='loading'?'Loading the current selection…':labelState==='missing'?'Current selection is unavailable':`Search ${field.label.toLowerCase()}`;
 return <div className="reference-picker"><div className="reference-input"><input ref={input} id={id} type="text" role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={listId} aria-activedescendant={open&&active>=0?`${listId}-${active}`:undefined} aria-required={field.required||undefined} aria-busy={labelState==='loading'||searching} autoComplete="off" maxLength={100} placeholder={placeholder} value={editing?text:label}
  onChange={e=>{setText(e.target.value);setEditing(true);setOpen(true)}} onClick={()=>{if(!open){setEditing(true);setOpen(true)}}} onBlur={close}
  onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();if(!open){setEditing(true);setOpen(true)}else setActive(i=>Math.min(options.length-1,i+1))}else if(e.key==='ArrowUp'){if(open){e.preventDefault();setActive(i=>Math.max(0,i-1))}}else if(e.key==='Enter'){if(open){e.preventDefault();if(options[active])choose(options[active])}}else if(e.key==='Escape'&&open){e.preventDefault();e.stopPropagation();close()}}}/>
  {!field.required&&selected&&<button type="button" className="text-button" onClick={()=>{labels.current.delete(selected);onChange('');input.current?.focus()}}>Clear<span className="sr-only"> {field.label.toLowerCase()}</span></button>}
  {open&&<ul className="reference-options" role="listbox" id={listId} aria-label={field.label}>{options.map((row,index)=><li key={row.id} id={`${listId}-${index}`} role="option" aria-selected={row.id===selected} className={index===active?'active':''} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(row)}>{referenceLabel(row,time.date)}</li>)}</ul>}</div>
  {open&&<small role="status">{searching?'Searching…':error?`Unable to search: ${error}`:options.length?`${options.length} ${options.length===1?'match':'matches'}${options.length===20?' shown; type to narrow the list':''}. Use the arrow keys to choose.`:'No matches.'}</small>}
 </div>
}
