/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {api,apiPage,action,errorMessage} from '@/lib/api';
import {listPath,mergeRecords,nextCursor,sortCreated} from '@/lib/records';
import type {RecordData,Field} from '@/lib/types';
import {useSession,useClinicTime} from './session';
import {Alert,Empty,Icon,Loading,Status} from './ui';
import {Blocks} from './blocks';
import {FormFields} from './forms';
import {Chat} from './chat';
import {NotificationPreferences} from './settings';
import './secondary-pages.css';
export const portalSections=[['appointments','Visits'],['documents','Documents'],['invoices','Invoices'],['results','Results'],['conversations','Messages'],['notifications','Notifications'],['preferences','Preferences']] as const;
const portalPage=25;
/** Only the patient records linked to this account; never a clinic-wide patient list. */
function useLinkedPatients(onError?:(message:string)=>void){const{session}=useSession();const ids=(session?.user.patientIds||[]).join(',');const[patients,setPatients]=useState<RecordData[]|null>(null);
 useEffect(()=>{let active=true;if(!ids){setPatients([]);return}void Promise.allSettled(ids.split(',').map(id=>api<RecordData>(`/records/patients/${encodeURIComponent(id)}`))).then(results=>{if(!active)return;setPatients(results.flatMap(result=>result.status==='fulfilled'?[result.value]:[]));const failed=results.find(result=>result.status==='rejected');if(failed&&failed.status==='rejected')onError?.(errorMessage(failed.reason))});return()=>{active=false}
 // onError is a display callback; reload only when the linked records change.
 },[ids]);return patients}
function PortalTabs({section}:{section:string}){return <nav className="portal-tabs tabs" aria-label="Patient portal sections">{portalSections.map(([id,label])=><Link key={id} href={`/portal/${id}`} className={section===id?'active':''} aria-current={section===id?'page':undefined}>{label}</Link>)}</nav>}
export function Portal({section='appointments'}:{section?:string}){
 const time=useClinicTime();const{session}=useSession();const[data,setData]=useState<RecordData[]>([]);const patients=useLinkedPatients();const[loading,setLoading]=useState(true);const[loadingMore,setLoadingMore]=useState(false);const[cursor,setCursor]=useState('');const[error,setError]=useState('');
 useEffect(()=>{let active=true;setData([]);setError('');setCursor('');if(['conversations','preferences'].includes(section))return;setLoading(true);void apiPage(listPath(section,{order:'desc',limit:portalPage})).then(page=>{if(active){setData(page.data);setCursor(nextCursor(page,portalPage))}}).catch(e=>{if(active)setError(errorMessage(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[section]);
 const loadMore=async()=>{if(!cursor||loadingMore)return;setLoadingMore(true);try{const page=await apiPage(listPath(section,{order:'desc',limit:portalPage,after:cursor}));setData(current=>mergeRecords(current,page.data));setCursor(nextCursor(page,portalPage))}catch(e){setError(errorMessage(e))}finally{setLoadingMore(false)}};
 const sorted=useMemo(()=>section==='appointments'?[...data].sort((a,b)=>String(b.startsAt||'').localeCompare(String(a.startsAt||''))||b.id.localeCompare(a.id)):sortCreated(data,true),[data,section]);
 const label=portalSections.find(x=>x[0]===section)?.[1]||'Records';
 return <><div className="page-heading"><div><span className="date-line">Your patient portal</span><h1>Hello, {session?.user.name.split(' ')[0]}.</h1><p>Your visits, documents, and conversations with the clinic.</p></div><Link href="/booking" className="button primary"><Icon name="calendar" size={17}/>Request a visit</Link></div>{!session?.user.patientIds.length&&<Alert kind="info">Your account is ready. Your clinic will verify your identity before connecting any existing patient records.</Alert>}<div className="portal-patients">{(patients||[]).map(p=><div key={p.id}><span className="avatar">{String(p.name).slice(0,1)}</span><span><strong>{String(p.name)}</strong><small>Verified patient record</small></span></div>)}</div><PortalTabs section={section}/>{error&&<Alert>{error}</Alert>}{section==='conversations'?<Chat basePath="/portal/conversations"/>:section==='preferences'?<section className="panel settings-panel"><NotificationPreferences/></section>:<section className="panel portal-records">{loading?<Loading/>:!data.length?<Empty title={`No ${label.toLowerCase()} to show`} description="Your clinic will make new information available here when it is ready."/>:sorted.map(r=><Link className="portal-record" key={r.id} href={`/portal/${section}/${encodeURIComponent(r.id)}`}><span className="portal-record-icon"><Icon name={section==='appointments'?'calendar':section==='invoices'?'invoices':'notes'}/></span><span><strong>{String(r.title||r.number||r.reason||r.kind||'Clinic record')}</strong><small>{time.date(String(r.startsAt||r.createdAt),{dateStyle:'medium',timeStyle:'short'})} · {time.timezone}</small></span><Status value={r.status||r.reviewState||'available'}/><Icon name="arrow" size={17}/></Link>)}{cursor&&!loading&&<button type="button" className="button secondary" disabled={loadingMore} aria-busy={loadingMore} onClick={()=>void loadMore()}>{loadingMore?'Loading more…':'Show more'}</button>}</section>}{section==='appointments'&&Boolean(patients?.length)&&<div className="care-path"><Icon name="notes" size={27}/><div><strong>Share a little before your visit.</strong><p>Add the information you would like your care team to review.</p></div><Link className="button secondary" href="/portal/intake">Prepare visit notes</Link></div>}</>
}
// Keep record identifiers, signing integrity and delivery internals out of patient-facing details.
function patientDetailField(key:string){return key!=='id'&&!/Ids?$/.test(key)&&!/(hash|checksum|fingerprint|integrity)/i.test(key)&&!['version','renderVersion','content','snapshot','snapshots','signedSnapshot','audit','revisions','released','scanStatus','idempotencyKey','createdBy','updatedBy','signedBy','reviewedBy','releasedBy','actionCompletedBy','assignedTo','createdByName'].includes(key)}
function patientDetailValue(value:unknown):unknown{if(Array.isArray(value))return value.map(patientDetailValue);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>patientDetailField(key)).map(([key,item])=>[key,patientDetailValue(item)]));return value}
export function PortalRecordPage({section,id}:{section:string;id:string}){
 const[record,setRecord]=useState<RecordData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const time=useClinicTime();const label=portalSections.find(x=>x[0]===section)?.[1]||'Records';
 useEffect(()=>{let active=true;setLoading(true);setError('');setRecord(null);void api<RecordData>(`/records/${section}/${encodeURIComponent(id)}`).then(result=>{if(active){setRecord(result);if(section==='notifications')void action('notifications.read',{id}).catch(()=>{})}}).catch(e=>{if(active)setError(errorMessage(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[section,id]);
 const snapshot=record?.kind==='intake'&&record.snapshot&&typeof record.snapshot==='object'?record.snapshot as Record<string,unknown>:null;
 const format=(key:string,value:unknown)=>{if(/At$/.test(key)&&value&&!Number.isNaN(new Date(String(value)).getTime()))return `${time.date(String(value),{dateStyle:'medium',timeStyle:'short'})} · ${time.timezone}`;return String(value??'—')};
 return <><Link className="page-back" href={`/portal/${section}`}>← {label}</Link><div className="page-heading"><div><span className="date-line">Your patient portal</span><h1>{record?String(record.title||record.number||record.reason||'Your record'):'Your record'}</h1><p>Information shared with you by your clinic.</p></div></div>{error&&<Alert>{error}</Alert>}{loading?<Loading label="Opening your record…"/>:record?<section className="panel record-detail dedicated-record"><div className="detail-meta"><Status value={record.status||record.reviewState||'available'}/></div>{record.content?<Blocks value={record.content}/>:snapshot?.content?<Blocks value={snapshot.content}/>:null}{snapshot&&<dl className="detail-grid intake-summary">{[['allergies','Known allergies'],['medicines','Current medicines']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{Array.isArray(snapshot[key])&&(snapshot[key] as unknown[]).length?(snapshot[key] as unknown[]).map(String).join(', '):'None shared'}</dd></div>)}</dl>}<dl className="detail-grid">{Object.entries(record).filter(([key])=>patientDetailField(key)).map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1')}</dt><dd>{typeof value==='object'?<pre className="json-value">{JSON.stringify(patientDetailValue(value),null,2)}</pre>:format(key,value)}</dd></div>)}</dl>{section==='documents'&&['invoice','payslip','credit-note'].includes(String(record.kind))&&<a className="button primary" href={`/api/v1/documents/${encodeURIComponent(record.id)}/pdf`} download>Download document</a>}</section>:null}</>
}
export function PortalIntakePage(){
 const[error,setError]=useState('');const patients=useLinkedPatients(setError);const router=useRouter();
 return <><Link className="page-back" href="/portal/appointments">← Visits</Link><div className="page-heading"><div><h1>Prepare your visit notes</h1><p>Share the information you would like your care team to review.</p></div></div>{error&&<Alert>{error}</Alert>}{patients===null?<Loading/>:patients.length?<section className="panel dedicated-form"><IntakeForm patients={patients} onDone={()=>router.push('/portal/appointments')}/></section>:<Empty title="Connect your patient record first" description="Your clinic will verify your identity before you can share visit notes."/>}</>
}
function IntakeForm({patients,onDone}:{patients:RecordData[];onDone:()=>void}){const[values,setValues]=useState<Record<string,unknown>>({patientId:patients[0]?.id,content:[],allergies:[],medicines:[]});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const fields:Field[]=[{key:'content',label:'What would you like to discuss?',type:'blocks',full:true},{key:'allergies',label:'Known allergies',type:'json'},{key:'medicines',label:'Current medicines',type:'json'}];return <form className="record-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await action('patients.intake',values);onDone()}catch(err){setError(errorMessage(err));setBusy(false)}}}>{error&&<Alert>{error}</Alert>}<label className="form-field">For patient<select required value={String(values.patientId)} onChange={e=>setValues({...values,patientId:e.target.value})}>{patients.map(p=><option value={p.id} key={p.id}>{String(p.name)}</option>)}</select></label><FormFields fields={fields} values={values} onChange={setValues}/><footer className="form-footer"><span>Your care team will review these notes.</span><Link className="button secondary" href="/portal/appointments">Cancel</Link><button className="button primary" disabled={busy}>{busy?'Saving…':'Share with care team'}</button></footer></form>}
