/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import {useEffect,useRef,useState} from 'react';
import {useCreateBlockNote,createReactBlockSpec} from '@blocknote/react';
import {BlockNoteSchema,defaultBlockSpecs,type PartialBlock} from '@blocknote/core';
import {BlockNoteView} from '@blocknote/shadcn';
import {api,errorMessage} from '@/lib/api';
import './secondary-pages.css';
import '@blocknote/core/fonts/inter.css';
import '@blocknote/shadcn/style.css';
const citation=createReactBlockSpec({type:'citation',propSchema:{title:{default:''},url:{default:''}},content:'none'}, {render:({block,editor})=><div className="citation-block" contentEditable={false}><strong>Source</strong><input aria-label="Source title" placeholder="Source title" value={block.props.title} onChange={e=>editor.updateBlock(block,{props:{title:e.target.value}})}/><input aria-label="Source URL" placeholder="https://…" value={block.props.url} onChange={e=>editor.updateBlock(block,{props:{url:e.target.value}})}/></div>})();
const medicalReview=createReactBlockSpec({type:'medicalReview',propSchema:{reviewer:{default:''},date:{default:''}},content:'inline'}, {render:({block,editor,contentRef})=><aside className="medical-review"><div contentEditable={false}><strong>Clinical review</strong><input aria-label="Reviewer name" placeholder="Reviewer name" value={block.props.reviewer} onChange={e=>editor.updateBlock(block,{props:{reviewer:e.target.value}})}/><input aria-label="Review date" type="date" value={block.props.date} onChange={e=>editor.updateBlock(block,{props:{date:e.target.value}})}/></div><div ref={contentRef}/></aside>})();
const schema=BlockNoteSchema.create({blockSpecs:{...defaultBlockSpecs,citation,medicalReview}});
export default function RichEditor({value,onChange,readOnly=false,patientId,publicContent=false}:{value:unknown[];onChange:(v:unknown[])=>void;readOnly?:boolean;patientId?:string;publicContent?:boolean}){
 const[description,setDescription]=useState('');const[uploadError,setUploadError]=useState('');const[uploading,setUploading]=useState(false);const[uploadNotice,setUploadNotice]=useState('');const descriptionRef=useRef('');descriptionRef.current=description;
 const upload=async(file:File)=>{const body=new FormData();body.append('file',file);const alt=descriptionRef.current.trim();if(publicContent){if(!alt){setUploadError('Add an image description below before uploading.');throw new Error('Add an image description before uploading.')}body.append('alt',alt)}else if(patientId)body.append('patientId',patientId);const result=await api<{id:string;url?:string}>(publicContent?'/public-assets':'/files',{method:'POST',body});return publicContent?{props:{url:result.url||`/api/v1/public/assets/${encodeURIComponent(result.id)}`,caption:alt,name:alt}}:`/api/v1/files/${encodeURIComponent(result.id)}`;};
 const editor=useCreateBlockNote({schema,initialContent:value?.length?value as PartialBlock<typeof schema.blockSchema,typeof schema.inlineContentSchema,typeof schema.styleSchema>[]:undefined,uploadFile:upload});
 const lastValue=useRef(JSON.stringify(value));
 useEffect(()=>{const next=JSON.stringify(value);if(next!==lastValue.current){lastValue.current=next;editor.replaceBlocks(editor.document,value?.length?value as typeof editor.document:[{type:'paragraph'}]);}},[value,editor]);
 return <div className="writing-surface">{!readOnly&&<div className="editor-tools"><span>Type / for writing tools</span><button type="button" className="text-button" onClick={()=>editor.insertBlocks([{type:'citation'}],editor.getTextCursorPosition().block,'after')}>Add source</button><button type="button" className="text-button" onClick={()=>editor.insertBlocks([{type:'medicalReview'}],editor.getTextCursorPosition().block,'after')}>Clinical review</button></div>}{publicContent&&!readOnly&&<div className="public-image-upload"><label className="form-field">Public image description<input value={description} maxLength={500} placeholder="Describe what the image shows" onChange={e=>{setDescription(e.target.value);setUploadError('');setUploadNotice('')}}/><small>Used as accessible image text. Add a description, then choose an image to insert.</small></label><label className="button secondary">{uploading?'Scanning image…':'Choose and insert image'}<input type="file" className="sr-only" accept="image/png,image/jpeg,image/webp" disabled={uploading||!description.trim()} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setUploading(true);setUploadError('');setUploadNotice('');try{const result=await upload(file);if(typeof result==='string')throw new Error('The public image could not be inserted.');editor.insertBlocks([{type:'image',props:result.props}],editor.getTextCursorPosition().block,'after');setDescription('');setUploadNotice('Image inserted with its accessible description.')}catch(err){setUploadError(errorMessage(err))}finally{setUploading(false)}}}/></label>{uploadError&&<p role="alert">{uploadError}</p>}{uploadNotice&&<p role="status">{uploadNotice}</p>}</div>}<BlockNoteView editor={editor} editable={!readOnly} theme="light" filePanel={publicContent?false:undefined} onChange={()=>{lastValue.current=JSON.stringify(editor.document);onChange(editor.document)}}/></div>;
}
