/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import {Suspense,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {api,errorMessage} from '@/lib/api';
import {Alert,Loading,Mark} from './ui';
function Form({mode}:{mode:'verify'|'reset'}){const params=useSearchParams();const token=params.get('token');const[password,setPassword]=useState('');const[email,setEmail]=useState('');const[error,setError]=useState('');const[success,setSuccess]=useState('');const[busy,setBusy]=useState(false);return <main className="invite-page"><div className="panel"><Mark/><h1>{mode==='verify'?'Verify your email':token?'Choose a new password':'Reset your password'}</h1><p>{mode==='verify'?'Confirm this email address for your clinic account.':token?'Use a strong password you have not used elsewhere.':'Enter your email to request a password reset link.'}</p>{error&&<Alert>{error}</Alert>}{success?<><Alert kind="success">{success}</Alert><Link className="button primary" href="/login">Go to sign in</Link></>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{if(token){await api('/auth/consume-token',{method:'POST',body:{token,...(mode==='reset'?{password}:{})}});setSuccess(mode==='reset'?'Password updated. Sign in with your new password.':'Email address verified.')}else{await api('/auth/reset-password',{method:'POST',body:{email}});setSuccess('If an account uses this email, a reset link will be sent.')}}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}}>{mode==='reset'&&(token?<label className="form-field">New password<input type="password" minLength={12} required autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>:<label className="form-field">Email address<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>)}<button className="button primary" disabled={busy||(mode==='verify'&&!token)}>{busy?'Saving…':mode==='verify'?'Verify email':token?'Update password':'Send reset link'}</button></form>}</div></main>}
export function TokenForm({mode}:{mode:'verify'|'reset'}){return <Suspense fallback={<Loading/>}><Form mode={mode}/></Suspense>}
