/* Author: ramanpal singh | URL: https://kwebby.com */
import type {WebsiteImage,WebsiteSection,WebsiteLocation} from '../../../packages/contracts/src/website';
import type {RecordData} from '@/lib/types';
import {DAYS,locationAddress,telHref} from '@/lib/website-display';
export interface WebsiteContentSource {services:RecordData[];doctors:RecordData[];pages:RecordData[];locations?:WebsiteLocation[];currency:string;locale:string}
export function WebsiteImageView({image,className='',eager=false}:{image:WebsiteImage;className?:string;eager?:boolean}){return <img className={className} src={`/api/v1/public/assets/${encodeURIComponent(image.assetId)}`} alt={image.alt} width={image.width??1200} height={image.height??800} loading={eager?'eager':'lazy'} decoding="async"/>;}
export function LocationDetails({location,heading=true}:{location:WebsiteLocation;heading?:boolean}){return <article className="location-details">{location.image&&<WebsiteImageView image={location.image}/>}<div>{heading&&<h3><a href={`/${location.slug}`}>{location.name}</a></h3>}<address>{locationAddress(location)}</address><p><a href={telHref(location.phone)}>{location.displayPhone||location.phone}</a>{location.email&&<> · <a href={`mailto:${location.email}`}>{location.email}</a></>}</p>{location.hours.length>0&&<><h4>Opening hours</h4><dl className="opening-hours">{[...location.hours].sort((a,b)=>(a.day+6)%7-(b.day+6)%7).map(day=><div key={day.day}><dt>{DAYS[day.day]}</dt><dd>{day.closed?'Closed':`${day.opens}–${day.closes}`}</dd></div>)}</dl><small>Local time · {location.timezone}</small></>}{location.exceptions.length>0&&<><h4>Special opening hours</h4><ul>{location.exceptions.map(day=><li key={day.date}>{day.date}{day.label?` · ${day.label}`:''}: {day.closed?'Closed':`${day.opens}–${day.closes}`}</li>)}</ul></>}{location.parking&&<p><strong>Parking and transport</strong><br/>{location.parking}</p>}{location.accessibility&&<p><strong>Accessibility</strong><br/>{location.accessibility}</p>}<div className="button-row">{location.mapsUrl&&<a className="button secondary" href={location.mapsUrl} rel="noopener noreferrer">Get directions</a>}<a className="button primary" href={`/booking?branch=${encodeURIComponent(location.branchId)}`}>Book at this clinic</a></div></div></article>;}
export function WebsiteSections({sections,source}:{sections:WebsiteSection[];source:WebsiteContentSource}){const selected=(rows:RecordData[],section:WebsiteSection)=>section.sourceIds?.length?rows.filter(r=>section.sourceIds!.includes(r.id)):rows;
 return <>{sections.filter(s=>s.enabled).map(section=>{const Heading=section.type==='hero'?'h1':'h2';return <section id={section.id} key={section.id} className={`editable-section section-${section.type} variant-${section.variant}`}><div className="editable-section-intro"><div>{section.eyebrow&&<p className="section-eyebrow">{section.eyebrow}</p>}{section.heading&&<Heading>{section.heading}</Heading>}{section.text&&<p className="section-description">{section.text}</p>}{Boolean(section.buttons?.length)&&<div className="button-row">{section.buttons!.map((b,i)=><a key={i} className={`button ${b.style||'primary'}`} href={b.href}>{b.label}</a>)}</div>}</div>{section.image&&<WebsiteImageView image={section.image} eager={section.type==='hero'}/>}</div>
 {Boolean(section.cards?.length)&&<div className="website-cards">{section.cards!.map(card=><article key={card.id}>{card.image&&<WebsiteImageView image={card.image}/>}<div>{card.eyebrow&&<small>{card.eyebrow}</small>}<h3>{card.heading}</h3>{card.text&&<p>{card.text}</p>}{card.button&&<a className={`button ${card.button.style||'secondary'}`} href={card.button.href}>{card.button.label}</a>}</div></article>)}</div>}
 {!section.cards?.length&&section.type==='services'&&<div className="service-list">{selected(source.services,section).map(s=><article key={s.id}><div><h3>{String(s.name)}</h3><p>{String(s.description||'')}</p></div><div className="service-price">{s.price!==undefined&&<strong>{new Intl.NumberFormat(source.locale,{style:'currency',currency:String(s.currency||source.currency)}).format(Number(s.price))}</strong>}<a href={`/booking?service=${encodeURIComponent(s.id)}`}>Request a visit</a></div></article>)}</div>}
 {!section.cards?.length&&section.type==='doctors'&&<div className="doctor-list">{selected(source.doctors,section).map(d=><article key={d.id}><div className="doctor-initial" aria-hidden="true">{String(d.name).split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h3>{String(d.name)}</h3><p>{String(d.specialty||d.jobTitle||'Clinical team')}</p>{Boolean(d.credentials)&&<p>{String(d.credentials)}</p>}<a href={`/booking?doctor=${encodeURIComponent(d.id)}`}>Request a visit</a></div></article>)}</div>}
 {section.type==='locations'&&<div className="website-locations">{(source.locations??[]).filter(l=>!section.sourceIds?.length||section.sourceIds.includes(l.id)).map(location=><LocationDetails key={location.id} location={location}/>)}</div>}
 {Boolean(section.faqs?.length)&&<div className="website-faqs">{section.faqs!.map(faq=><details key={faq.id}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div>}
 {!section.cards?.length&&section.type==='resources'&&<div className="website-cards">{selected(source.pages.filter(p=>p.kind==='article'||p.kind==='medical'),section).slice(0,6).map(page=><article key={page.id}><div><h3><a href={`/${page.slug}`}>{String(page.title)}</a></h3></div></article>)}</div>}
 </section>})}</>;
}
