/* Author: ramanpal singh | URL: https://kwebby.com */
'use client';
import {useState,useRef,useEffect} from 'react';
import {api,errorMessage} from '@/lib/api';
import type {WebsiteButton,WebsiteImage} from '../../../packages/contracts/src/website';
import {useWebsiteEditor} from './website-editor-context';
import {WebsiteImageView} from './website-sections';

export function TextField({label,value,onChange,multiline=false,type='text',hint,required=false,maxLength}:{label:string;value?:string|number;onChange:(value:string)=>void;multiline?:boolean;type?:string;hint?:string;required?:boolean;maxLength?:number}){return <label className={`form-field ${multiline?'full':''}`}><span>{label}{required?' *':''}</span>{multiline?<textarea aria-label={label} value={value??''} rows={4} onChange={e=>onChange(e.target.value)} required={required} maxLength={maxLength}/>:<input aria-label={label} value={value??''} type={type} onChange={e=>onChange(e.target.value)} required={required} maxLength={maxLength}/>} {hint&&<small>{hint}</small>}</label>;}
export function CheckField({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="checkbox-field"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
export function ImageField({value,onChange,label='Section image'}:{value?:WebsiteImage;onChange:(value:WebsiteImage|undefined)=>void;label?:string}){const {startUpload}=useWebsiteEditor();const latestChange=useRef(onChange);latestChange.current=onChange;const mounted=useRef(true);const releaseRef=useRef<()=>void>(undefined);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;releaseRef.current?.()}},[]);const [alt,setAlt]=useState(value?.alt??'');const latestAlt=useRef(value?.alt??alt);latestAlt.current=value?.alt??alt;const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');return <fieldset className="website-subform"><legend>{label}</legend>{value&&<WebsiteImageView image={value} className="website-image-preview"/>}<TextField label={`${label} description`} value={value?.alt??alt} maxLength={300} onChange={text=>{setAlt(text);if(value)onChange({...value,alt:text})}} hint="Describe what the image shows. Use only images approved for public display."/><div className="button-row"><label className="button secondary">{busy?'Scanning image…':value?'Replace image':'Upload image'}<input className="sr-only" type="file" aria-label={`Upload ${label.toLowerCase()}`} accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const description=value?.alt??alt;if(!description.trim()){setMessage('Enter an image description before uploading.');e.target.value='';return;}setBusy(true);setMessage('');const release=startUpload();releaseRef.current=release;try{const body=new FormData();body.append('file',file);body.append('alt',description);const image=await api<{id:string;alt:string;width:number;height:number}>('/public-assets',{method:'POST',body});if(!mounted.current)return;latestChange.current({assetId:image.id,alt:latestAlt.current,width:image.width,height:image.height});setMessage('Image scanned and ready. Save the website draft to keep this selection.')}catch(error){if(mounted.current)setMessage(errorMessage(error))}finally{release();if(mounted.current){setBusy(false);e.target.value=''}}}}/></label>{value&&<button type="button" className="text-button" onClick={()=>onChange(undefined)}>Remove image</button>}</div><small>PNG, JPEG or WebP · Up to 10 MB · Metadata removed</small>{message&&<p role="status">{message}</p>}</fieldset>;}
export function ButtonFields({value,onChange,label='Button'}:{value:WebsiteButton;onChange:(value:WebsiteButton)=>void;label?:string}){return <div className="form-grid"><TextField label={`${label} label`} value={value.label} maxLength={80} onChange={label=>onChange({...value,label})}/><TextField label={`${label} destination`} value={value.href} onChange={href=>onChange({...value,href})} hint="A path such as /booking, HTTPS URL, tel: or mailto: link."/><label className="form-field"><span>{label} style</span><select value={value.style??'primary'} onChange={e=>onChange({...value,style:e.target.value as 'primary'|'secondary'})}><option value="primary">Primary</option><option value="secondary">Secondary</option></select></label></div>;}
