/* Author: ramanpal singh | URL: https://kwebby.com */
import 'dotenv/config';
import { randomBytes } from 'node:crypto';
import { mkdir,writeFile } from 'node:fs/promises';
import { hash } from 'bcryptjs';
import { createDatabase } from '../packages/persistence/src/index.js';
import { ClinicService } from '../packages/core/src/index.js';
import { entity,asActor,type User } from '../apps/api/src/auth.js';
import { digest } from '../apps/api/src/security.js';
import { assert,type Actor } from '../packages/contracts/src/index.js';

assert(process.env.NODE_ENV!=='production'&&process.env.DEMO_SEED==='true','DEMO','Set DEMO_SEED=true in a development installation to seed fictional records');
const db=createDatabase();await db.initialize();
assert((await db.list('users',{limit:1})).length===0,'DEMO','Demo seed requires an empty installation');
const org=process.env.ORGANIZATION_ID??'clinic',clinic=new ClinicService(db),password=randomBytes(18).toString('base64url'),passwordHash=await hash(password,12);
async function user(id:string,name:string,email:string,roles:User['roles']){const row:User={...entity(org,id),name,email,roles,branchIds:['main'],patientIds:[],passwordHash,status:'active',emailVerified:true,mfaEnabled:false,sessionVersion:1};await db.put('users',row);await db.put('userEmails',{...entity(org,digest(email)),userId:id});return asActor(row);}
const owner=await user('demo-owner','Jamie Morgan','owner@example.test',['owner']);const doctor=await user('demo-doctor','Dr. Alex Reed','doctor@example.test',['doctor']);const reception=await user('demo-reception','Casey Lee','reception@example.test',['receptionist']);const patientUser=await user('demo-patient-account','Sam Taylor','patient@example.test',['patient']);
const paragraph=(text:string)=>[{id:crypto.randomUUID(),type:'paragraph',props:{textColor:'default',backgroundColor:'default',textAlignment:'left'},content:[{type:'text',text,styles:{}}],children:[]}];
await clinic.create('settings',{key:'business',value:{clinicName:'Willow Family Clinic',legalName:'Willow Clinic Demonstration',country:'US',currency:'USD',timezone:'UTC',locale:'en',address:'100 Example Lane · Fictional demonstration',email:'care@example.test',phone:'+1 202 555 0147',businessIds:{registration:'DEMO-ONLY'},bankDetails:'Demonstration — do not transfer funds',fiscalYearStart:1,invoicePrefix:'DEMO',publicBooking:true}},owner);
await clinic.create('settings',{key:'website',value:{siteName:'Willow Family Clinic',origin:'https://example.test',description:'Thoughtful care for everyday life. A fictional clinic for exploring this platform.',locale:'en',socialHandles:{},navigation:[{label:'Our care',href:'/services'},{label:'Your visit',href:'/booking'},{label:'Visit tools',href:'/tools'}]}},owner);
const services=[];for(const [name,price,durationMinutes]of [['General consultation','65.00',30],['Follow-up visit','40.00',20],['Annual wellness visit','95.00',45]] as const)services.push(await clinic.create('services',{branchId:'main',name,description:'Discuss your health and agree on next steps with your clinician.',price,currency:'USD',durationMinutes,public:true,taxRate:'0'},owner));
await clinic.create('employees',{branchId:'main',userId:doctor.id,name:'Dr. Alex Reed',email:'doctor@example.test',jobTitle:'General practitioner',role:'doctor',registrationNumber:'DEMO-ONLY',specialty:'General outpatient care',publicProfile:true,salary:{currency:'USD',base:'5000.00',earnings:[],deductions:[]}},owner);
for(let weekday=0;weekday<7;weekday++)await clinic.create('availability',{branchId:'main',doctorId:doctor.id,weekday,startTime:'08:00',endTime:'18:00',timezone:'UTC',slotMinutes:30},owner);
const patient=await clinic.create('patients',{branchId:'main',name:'Sam Taylor',dateOfBirth:'1990-05-15',email:'patient@example.test',phone:'+1 202 555 0110',allergies:['Penicillin (demonstration record)'],medicines:[]},reception);
const u=await db.get<User>('users',patientUser.id);await db.put('users',{...u!,patientIds:[patient.id],version:u!.version+1,updatedAt:new Date().toISOString()},u!.version);
const today=new Date();today.setUTCHours(14,0,0,0);if(today.getTime()<Date.now()+3600000)today.setUTCDate(today.getUTCDate()+1);
const appointment=await clinic.create('appointments',{branchId:'main',patientId:patient.id,doctorId:doctor.id,startsAt:today.toISOString(),endsAt:new Date(today.getTime()+1800000).toISOString(),reason:'Routine consultation — fictional example',kind:'consultation'},reception);
await clinic.create('encounters',{branchId:'main',patientId:patient.id,doctorId:doctor.id,appointmentId:appointment.id,content:paragraph('Fictional demonstration note. The clinician documents the history, findings, and agreed next steps here.')},doctor);
await clinic.create('tasks',{branchId:'main',title:'Review appointment preparation',assignedTo:doctor.id,patientId:patient.id,priority:'normal',category:'clinical'},doctor);
await clinic.create('results',{branchId:'main',patientId:patient.id,title:'External report awaiting review (demo)',reviewerId:doctor.id,critical:false},doctor);
for(const [name,email,interest]of [['Jordan Parker','jordan@example.test','Interested in a first visit'],['River Ellis','river@example.test','Asked about clinic accessibility']])await clinic.create('leads',{branchId:'main',name,email,source:'website',interest,assignedTo:reception.id,marketingConsent:false},reception);
const template=await clinic.create('templates',{name:'Willow invoice',kind:'invoice',content:[],design:{accent:'#18756b',font:'system',showLogo:true,columns:['description','quantity','unitPrice','tax','total'],footer:'Thank you for choosing Willow Family Clinic.',terms:'Demonstration invoice. No payment is due.'}},owner);await clinic.execute('templates.publish',{id:template.id,expectedVersion:template.version},owner);
const invoice=await clinic.create('invoices',{branchId:'main',patientId:patient.id,currency:'USD',lines:[{description:'General consultation (demo)',quantity:'1',unitPrice:'65.00',taxRate:'0',discount:'0'}],templateId:template.id,notes:[]},owner);await clinic.execute('invoices.issue',{id:invoice.id,expectedVersion:invoice.version},owner);
const employee=await clinic.create('employees',{branchId:'main',userId:reception.id,name:'Casey Lee',email:'reception@example.test',jobTitle:'Patient coordinator',salary:{currency:'USD',base:'3200.00',earnings:[],deductions:[]}},owner);await clinic.create('payroll',{branchId:'main',period:new Date().toISOString().slice(0,7),employeeIds:[employee.id],adjustments:[]},owner);
const conversation=await clinic.create('conversations',{branchId:'main',title:'Front desk coordination',kind:'staff',participantIds:[owner.id,reception.id]},owner);await clinic.execute('conversations.send',{conversationId:conversation.id,body:'Welcome to the demonstration workspace. Every record here is fictional.',idempotencyKey:'demo-welcome-001'},owner);
for(const [title,slug,kind,text] of [['A calmer way to care','home','home','Welcome to Willow Family Clinic. This is a fictional clinic demonstrating the platform. Explore appointments, our services, and tools to prepare for your visit.'],['Care that starts with listening','about','about','Our demonstration team puts clear communication and thoughtful follow-up at the center of each visit.'],['General outpatient care','services','service','Find a service, review the published fee, and request a convenient appointment.'],['Contact our team','contact','contact','Use the appointment form for routine enquiries. For emergencies, contact your local emergency service.']] as const){const page=await clinic.create('pages',{title,slug,kind,locale:'en',content:paragraph(text),seo:{description:text.slice(0,180),indexable:true}},owner);await clinic.execute('pages.publish',{id:page.id,expectedVersion:page.version},owner);}
await mkdir('.runtime',{recursive:true,mode:0o700});await writeFile('.runtime/demo-access.json',JSON.stringify({notice:'Local fictional demonstration only. Never deploy these accounts to production.',url:'http://localhost:3000/login',password,accounts:[owner,doctor,reception,patientUser].map(a=>({name:a.name,email:a.email,roles:a.roles}))},null,2),{mode:0o600});await db.close();console.log('Fictional demo created. Local credentials saved privately in .runtime/demo-access.json.');
